--[[
	ASHGROVE HOUSE installer, PART 2 OF 8.
	Generated by ashgrove/tools/build_installer.py. Don't edit by hand.

	Paste the parts into Studio's Command Bar IN ORDER (1, 2, 3 ...),
	pressing Enter after each. Wait for the Output window to say
	"part 2 of 8 done" before pasting the next one.
	Next: part 3.
]]

local REMOVE_OLD = false
local FINISH = false
local DONE_MESSAGE = "[Ashgrove] part 2 of 8 done. Now paste part 3."
local ROOTS = {
	{ service = {"ReplicatedStorage"}, name = "Ashgrove" },
	{ service = {"ServerScriptService"}, name = "Ashgrove" },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, name = "AshgroveClient" },
}

local FILES = {
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "BellBoard"}, class = "ModuleScript", source = [=[
--[[
	BellBoard: the servants' bells ring for the room an entity is in.

	Imperfect on purpose (Config.bellBoard.ringChance per check), and only
	heard by players near the board: a diegetic tracker you have to go and
	stand by, like Alien: Isolation's motion tracker.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))

local Map = require(script.Parent.Map)
local Registry = require(script.Parent.Entities.Registry)
local Say = require(script.Parent.Say)

local BellBoard = {}

local NAMES = {
	Gallery = "GALLERY",
	Kitchen = "KITCHEN",
	Corridor = "PASSAGE",
	Scullery = "SCULLERY",
	Housekeeper = "HOUSEKEEPER",
	ServantsHall = "SERVANTS' HALL",
	Vault = "CELLAR",
}

local function ring(bell: BasePart, room: string)
	local base = bell.CFrame
	local swing = TweenService:Create(bell, TweenInfo.new(0.12, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut, 5, true), {
		CFrame = base * CFrame.Angles(0, 0, math.rad(25)),
	})
	swing:Play()
	swing.Completed:Once(function()
		bell.CFrame = base
	end)
	Audio.play("bell", bell, 0.6, 60)
	Say.near(bell.Position, Config.bellBoard.hearRadius, `[A bell rings on the board: {NAMES[room] or room}]`, 3, "sound")
end

function BellBoard.start()
	local board = Map.root():WaitForChild("Interact"):FindFirstChild("BellBoard")
	if not board then
		return
	end
	local bells: { [string]: BasePart } = {}
	for _, p in board:GetChildren() do
		local room = p:GetAttribute("Room")
		if p:IsA("BasePart") and room then
			bells[room] = p
		end
	end
	task.spawn(function()
		while true do
			task.wait(Config.bellBoard.checkEvery)
			for _, e in Registry.all() do
				local position = e:position()
				if e.status == "active" and position then
					local room = Map.roomAt(position)
					local bell = room and bells[room]
					if bell and math.random() < Config.bellBoard.ringChance then
						ring(bell, room :: string)
					end
				end
			end
		end
	end)
end

return BellBoard
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Build"}, class = "ModuleScript", source = [=[
--[[
	Build: small part-making helpers shared by House (layout) and Dressing
	(furniture and detail). Everything is anchored and smooth-surfaced.
]]

local Build = {}

function Build.part(parent: Instance, name: string, size: Vector3, cf: CFrame, colour: Color3, material: Enum.Material?): Part
	local p = Instance.new("Part")
	p.Name = name
	p.Anchored = true
	p.Size = size
	p.CFrame = cf
	p.Color = colour
	p.Material = material or Enum.Material.SmoothPlastic
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	p.Parent = parent
	return p
end

-- Axis-aligned box from two corners.
function Build.box(parent: Instance, name: string, x1: number, x2: number, y1: number, y2: number, z1: number, z2: number, colour: Color3, material: Enum.Material?): Part
	local size = Vector3.new(math.abs(x2 - x1), math.abs(y2 - y1), math.abs(z2 - z1))
	local centre = Vector3.new((x1 + x2) / 2, (y1 + y2) / 2, (z1 + z2) / 2)
	return Build.part(parent, name, size, CFrame.new(centre), colour, material)
end

-- A vertical cylinder standing on (x, y, z).
function Build.column(parent: Instance, name: string, x: number, y: number, z: number, height: number, diameter: number, colour: Color3, material: Enum.Material?): Part
	local p = Build.part(parent, name, Vector3.new(height, diameter, diameter), CFrame.new(x, y + height / 2, z) * CFrame.Angles(0, 0, math.rad(90)), colour, material)
	p.Shape = Enum.PartType.Cylinder
	return p
end

-- A cylinder between two points (branches, chains, rails).
function Build.rod(parent: Instance, name: string, a: Vector3, b: Vector3, diameter: number, colour: Color3, material: Enum.Material?): Part
	local length = (b - a).Magnitude
	local dir = (b - a).Unit
	-- lookAt can't use "up" as its up vector when the rod is vertical.
	local upVector = if math.abs(dir.Y) > 0.99 then Vector3.xAxis else Vector3.yAxis
	-- Cylinders run along X: aim X along a->b.
	local cf = CFrame.lookAt((a + b) / 2, b, upVector) * CFrame.Angles(0, math.rad(90), 0)
	local p = Build.part(parent, name, Vector3.new(length, diameter, diameter), cf, colour, material)
	p.Shape = Enum.PartType.Cylinder
	return p
end

-- Cosmetic only: no collisions, invisible to raycasts.
function Build.decor(p: BasePart): BasePart
	p.CanCollide = false
	p.CanQuery = false
	p.CanTouch = false
	return p
end

function Build.invisible(p: BasePart): BasePart
	p.Transparency = 1
	p.CanCollide = false
	p.CanQuery = false
	p.CanTouch = false
	return p
end

function Build.folder(parent: Instance, name: string): Folder
	local existing = parent:FindFirstChild(name)
	if existing and existing:IsA("Folder") then
		return existing
	end
	local f = Instance.new("Folder")
	f.Name = name
	f.Parent = parent
	return f
end

function Build.attributes(inst: Instance, attrs: { [string]: any }?)
	if attrs then
		for k, v in attrs do
			inst:SetAttribute(k, v)
		end
	end
end

function Build.label(p: BasePart, text: string, face: Enum.NormalId, colour: Color3?, font: Enum.Font?)
	local gui = Instance.new("SurfaceGui")
	gui.Face = face
	gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	gui.PixelsPerStud = 40
	gui.LightInfluence = 1
	local t = Instance.new("TextLabel")
	t.Size = UDim2.fromScale(1, 1)
	t.BackgroundTransparency = 1
	t.Text = text
	t.TextScaled = true
	t.Font = font or Enum.Font.Garamond
	t.TextColor3 = colour or Color3.fromRGB(218, 210, 188)
	t.Parent = gui
	gui.Parent = p
end

export type Rng = {
	number: (self: Rng, min: number, max: number) -> number,
	integer: (self: Rng, min: number, max: number) -> number,
}

-- Deterministic random numbers, so the dressing comes out the same every
-- build (nothing jumps around between edits). A small LCG, so it runs the
-- same outside Roblox too (the offline checks).
function Build.random(seed: number): Rng
	local state = seed % 2147483647
	if state <= 0 then
		state += 2147483646
	end
	local function nextUnit(): number
		state = (state * 48271) % 2147483647
		return state / 2147483647
	end
	return {
		number = function(_self, min: number, max: number): number
			return min + (max - min) * nextUnit()
		end,
		integer = function(_self, min: number, max: number): number
			return math.min(max, min + math.floor((max - min + 1) * nextUnit()))
		end,
	} :: any
end

return Build
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Crew"}, class = "ModuleScript", source = [=[
--[[
	Crew: the players. Hits, going down, being revived, being taken by the
	Banshee, party wipes, movement modes and their noise, the flashlight,
	the gold ward, and "committed" actions.

	Health is ours, not the Humanoid's: Config.player.hitsToDown hits put a
	player down, a crewmate revives them, and when nobody is left standing
	the party wipes back to the last checkpoint (Director handles that via
	Crew.wiped).

	A committed action (securing an object, a rite step, a revive) roots the
	player and puts their gun away for its length. The player can't cancel
	it; a hit can.

	Player attributes the client reads: Hits, Downed, Taken, MoveMode,
	Flashlight, LightOn, Battery, HasGold, WardRaised, WardReadyAt,
	CommitLabel, CommitEnds, CommitLength.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))
local Net = require(Shared:WaitForChild("Net"))
local Signal = require(Shared:WaitForChild("Signal"))

local Map = require(script.Parent.Map)
local Noise = require(script.Parent.Noise)
local Say = require(script.Parent.Say)

local Crew = {}

Crew.wiped = Signal.new()
Crew.characterReady = Signal.new() -- (player, character)
Crew.goldLost = Signal.new()

-- Director sets this so every (re)spawn lands at the current checkpoint.
Crew.spawnCFrame = function(_player: Player): CFrame?
	return nil
end

type Commit = { label: string, token: {}, onCancel: (() -> ())? }

type State = {
	hits: number,
	downed: boolean,
	taken: boolean,
	mode: string,
	flashlightOn: boolean,
	suppressUntil: number,
	battery: number,
	aim: Vector3,
	hasGold: boolean,
	wardUntil: number,
	wardReadyAt: number,
	commit: Commit?,
	invulnUntil: number,
	lastRegen: number,
	hipHeight: number,
	light: SpotLight?,
	lightAttachment: Attachment?,
	revivePrompt: ProximityPrompt?,
	goldPart: BasePart?,
}

local states: { [Player]: State } = {}
local wiping = false

local function newState(): State
	return {
		hits = 0,
		downed = false,
		taken = false,
		mode = "walk",
		flashlightOn = false,
		suppressUntil = 0,
		battery = Config.flashlight.battery,
		aim = Vector3.new(0, 0, -1),
		hasGold = false,
		wardUntil = 0,
		wardReadyAt = 0,
		commit = nil,
		invulnUntil = 0,
		lastRegen = 0,
		hipHeight = 2,
	}
end

function Crew.state(player: Player): State?
	return states[player]
end

function Crew.root(player: Player): BasePart?
	local character = player.Character
	return character and character:FindFirstChild("HumanoidRootPart") :: BasePart?
end

function Crew.head(player: Player): BasePart?
	local character = player.Character
	return character and character:FindFirstChild("Head") :: BasePart?
end

local function humanoidOf(player: Player): Humanoid?
	local character = player.Character
	return character and character:FindFirstChildOfClass("Humanoid")
end

-- Standing, in the game, and able to act.
function Crew.isActive(player: Player): boolean
	local s = states[player]
	if not s or s.downed or s.taken then
		return false
	end
	local humanoid = humanoidOf(player)
	return humanoid ~= nil and humanoid.Health > 0 and Crew.root(player) ~= nil
end

-- What entities may go after: active and not inside a sanctuary.
function Crew.isTargetable(player: Player): boolean
	if not Crew.isActive(player) then
		return false
	end
	local root = Crew.root(player)
	return root ~= nil and not Map.isSanctuary(root.Position)
end

function Crew.activePlayers(): { Player }
	local out = {}
	for player in states do
		if Crew.isActive(player) then
			table.insert(out, player)
		end
	end
	return out
end

-- Active players whose character is inside a wing.
function Crew.playersInWing(wing: string, includeDowned: boolean?): { Player }
	local out = {}
	for player, s in states do
		local root = Crew.root(player)
		if root and not s.taken and (includeDowned or Crew.isActive(player)) and Map.wingAt(root.Position) == wing then
			table.insert(out, player)
		end
	end
	return out
end

function Crew.isCommitting(player: Player): boolean
	local s = states[player]
	return s ~= nil and s.commit ~= nil
end

------------------------------------------------------------------ movement

local function refreshSpeed(player: Player)
	local s = states[player]
	local humanoid = humanoidOf(player)
	if not s or not humanoid then
		return
	end
	local p = Config.player
	local speed
	if s.taken or s.commit then
		speed = 0
	elseif s.downed then
		speed = p.downedSpeed
	elseif s.mode == "sprint" then
		speed = p.sprintSpeed
	elseif s.mode == "crouch" then
		speed = p.crouchSpeed
	else
		speed = p.walkSpeed
	end
	humanoid.WalkSpeed = speed
	-- Down, taken or busy: hands are full, so your gun is put away.
	if s.downed or s.taken or s.commit then
		humanoid:UnequipTools()
	end
	humanoid.UseJumpPower = true
	humanoid.JumpPower = if s.downed or s.commit or s.taken then 0 else p.jumpPower
	humanoid.HipHeight = if s.downed then math.max(0.2, s.hipHeight - 1.2) else s.hipHeight
end

------------------------------------------------------------------ flashlight

local function lightOn(s: State): boolean
	return s.flashlightOn and s.battery > 0 and os.clock() >= s.suppressUntil and not s.taken
end

local function updateLight(player: Player)
	local s = states[player]
	if not s then
		return
	end
	local on = lightOn(s)
	if s.light then
		s.light.Enabled = on
	end
	player:SetAttribute("Flashlight", s.flashlightOn)
	player:SetAttribute("LightOn", on)
	player:SetAttribute("Battery", math.floor(s.battery + 0.5))
end

-- Forces the light off for a while (reloading needs both hands).
function Crew.suppressFlashlight(player: Player, seconds: number)
	local s = states[player]
	if not s then
		return
	end
	s.suppressUntil = math.max(s.suppressUntil, os.clock() + seconds)
	updateLight(player)
	task.delay(seconds + 0.05, updateLight, player)
end

function Crew.addBattery(player: Player, amount: number): boolean
	local s = states[player]
	if not s or s.battery >= Config.flashlight.maxBattery - 1 then
		return false
	end
	s.battery = math.min(Config.flashlight.maxBattery, s.battery + amount)
	updateLight(player)
	return true
end

-- Every flashlight currently shining: where from and which way.
function Crew.flashlights(): { { player: Player, origin: Vector3, direction: Vector3 } }
	local out = {}
	for player, s in states do
		if lightOn(s) then
			local head = Crew.head(player)
			if head then
				table.insert(out, { player = player, origin = head.Position, direction = s.aim })
			end
		end
	end
	return out
end

function Crew.aim(player: Player): Vector3
	local s = states[player]
	return if s then s.aim else Vector3.new(0, 0, -1)
end

------------------------------------------------------------------ ward

function Crew.giveGold(player: Player)
	local s = states[player]
	if s then
		s.hasGold = true
		player:SetAttribute("HasGold", true)
		Say.to(player, "Cornelius's gold sovereign. [G] raises it.", 5, "hint")
	end
end

function Crew.isWardRaised(player: Player): boolean
	local s = states[player]
	return s ~= nil and os.clock() < s.wardUntil and Crew.isActive(player)
end

local function raiseWard(player: Player)
	local s = states[player]
	if not s or not s.hasGold or not Crew.isActive(player) then
		return
	end
	local now = os.clock()
	if now < s.wardReadyAt then
		return
	end
	s.wardReadyAt = now + Config.ward.cooldown
	s.wardUntil = now + Config.ward.raiseTime
	player:SetAttribute("WardRaised", true)
	player:SetAttribute("WardReadyAt", workspace:GetServerTimeNow() + Config.ward.cooldown)
	if s.goldPart then
		s.goldPart.Transparency = 0
	end
	task.delay(Config.ward.raiseTime, function()
		player:SetAttribute("WardRaised", false)
		if s.goldPart then
			s.goldPart.Transparency = 1
		end
	end)
end

------------------------------------------------------------------ commit

local function clearCommitAttributes(player: Player)
	player:SetAttribute("CommitLabel", nil)
	player:SetAttribute("CommitEnds", nil)
	player:SetAttribute("CommitLength", nil)
end

-- Starts a committed action. Returns false if the player can't commit
-- right now (already busy, down, taken).
function Crew.commit(player: Player, seconds: number, label: string, onDone: () -> (), onCancel: (() -> ())?): boolean
	local s = states[player]
	if not s or not Crew.isActive(player) or s.commit then
		return false
	end
	local token = {}
	s.commit = { label = label, token = token, onCancel = onCancel }
	player:SetAttribute("CommitLabel", label)
	player:SetAttribute("CommitEnds", workspace:GetServerTimeNow() + seconds)
	player:SetAttribute("CommitLength", seconds)
	refreshSpeed(player)
	task.delay(seconds, function()
		local current = s.commit
		if current and current.token == token then
			s.commit = nil
			clearCommitAttributes(player)
			refreshSpeed(player)
			onDone()
		end
	end)
	return true
end

function Crew.cancelCommit(player: Player)
	local s = states[player]
	local current = s and s.commit
	if not s or not current then
		return
	end
	s.commit = nil
	clearCommitAttributes(player)
	refreshSpeed(player)
	Say.to(player, "Interrupted.", 2, "hint")
	if current.onCancel then
		task.spawn(current.onCancel)
	end
end

------------------------------------------------------------------ hits, down, taken

local function checkWipe()
	if wiping then
		return
	end
	local anyone, anyActive = false, false
	for player in states do
		if player.Parent and player.Character then
			anyone = true
			if Crew.isActive(player) then
				anyActive = true
			end
		end
	end
	if anyone and not anyActive then
		wiping = true
		Crew.wiped:Fire()
	end
end

local function setRevivePrompt(player: Player, enabled: boolean)
	local s = states[player]
	if s and s.revivePrompt then
		s.revivePrompt.Enabled = enabled
	end
end

function Crew.down(player: Player)
	local s = states[player]
	if not s or s.downed or s.taken then
		return
	end
	s.downed = true
	Crew.cancelCommit(player)
	player:SetAttribute("Downed", true)
	refreshSpeed(player)
	setRevivePrompt(player, true)
	Say.to(player, "You're down. A crewmate can get you up.", 6, "story")
	Say.except(player, `{player.DisplayName} is down. Get to them.`, 5, "story")
	checkWipe()
end

function Crew.revive(player: Player)
	local s = states[player]
	if not s or not s.downed or s.taken then
		return
	end
	s.downed = false
	s.hits = Config.player.hitsToDown - 1
	s.invulnUntil = os.clock() + 2
	player:SetAttribute("Downed", false)
	player:SetAttribute("Hits", s.hits)
	setRevivePrompt(player, false)
	refreshSpeed(player)
	Say.all(`{player.DisplayName} is back on their feet.`, 3, "story")
end

function Crew.hit(player: Player, amount: number)
	local s = states[player]
	if not s or not Crew.isActive(player) then
		return
	end
	local now = os.clock()
	if now < s.invulnUntil then
		return
	end
	s.invulnUntil = now + Config.player.hitInvulnerability
	s.hits = math.min(s.hits + amount, Config.player.hitsToDown)
	player:SetAttribute("Hits", s.hits)
	local root = Crew.root(player)
	if root then
		Audio.play("hurt", root, 0.7)
	end
	Crew.cancelCommit(player)
	if s.hits >= Config.player.hitsToDown then
		Crew.down(player)
	end
end

-- Taken by the Banshee: out of the game until the party reaches a
-- sanctuary. Can't be revived in place.
function Crew.take(player: Player)
	local s = states[player]
	if not s or s.taken then
		return
	end
	Crew.cancelCommit(player)
	s.taken = true
	s.downed = false
	player:SetAttribute("Taken", true)
	player:SetAttribute("Downed", false)
	setRevivePrompt(player, false)
	updateLight(player)
	refreshSpeed(player)
	local character = player.Character
	local root = Crew.root(player)
	if character and root then
		root.Anchored = true
		character:PivotTo(CFrame.new(Config.player.takenHoldPosition))
	end
	Net.event("Spectate"):FireClient(player, true)
	Say.except(player, `{player.DisplayName} is gone. Get somewhere safe and they'll come back.`, 6, "story")
	checkWipe()
end

local function placeCharacter(player: Player, cf: CFrame)
	local character = player.Character
	local root = Crew.root(player)
	if character and root then
		root.Anchored = false
		character:PivotTo(cf)
		root.AssemblyLinearVelocity = Vector3.zero
	end
end

function Crew.restoreTaken(at: CFrame)
	local i = 0
	for player, s in states do
		if s.taken then
			i += 1
			s.taken = false
			s.hits = 0
			player:SetAttribute("Taken", false)
			player:SetAttribute("Hits", 0)
			placeCharacter(player, at * CFrame.new(2 * i, 0, 2))
			refreshSpeed(player)
			updateLight(player)
			Net.event("Spectate"):FireClient(player, false)
			Say.all(`{player.DisplayName} stumbles back in out of the dark.`, 4, "story")
		end
	end
end

-- Checkpoint reset after a wipe.
function Crew.resetAll(at: CFrame)
	local i = 0
	for player, s in states do
		s.commit = nil
		clearCommitAttributes(player)
		s.hits = 0
		s.downed = false
		s.taken = false
		s.suppressUntil = 0
		s.invulnUntil = os.clock() + 3
		player:SetAttribute("Hits", 0)
		player:SetAttribute("Downed", false)
		player:SetAttribute("Taken", false)
		setRevivePrompt(player, false)
		placeCharacter(player, at * CFrame.new((i % 4) * 3 - 4.5, 0, math.floor(i / 4) * 3))
		refreshSpeed(player)
		updateLight(player)
		Net.event("Spectate"):FireClient(player, false)
		i += 1
	end
	wiping = false
end

------------------------------------------------------------------ characters

local function onCharacter(player: Player, character: Model)
	local s = states[player]
	if not s then
		return
	end
	s.hits = 0
	s.downed = false
	s.taken = false
	s.commit = nil
	clearCommitAttributes(player)
	player:SetAttribute("Hits", 0)
	player:SetAttribute("Downed", false)
	player:SetAttribute("Taken", false)

	local humanoid = character:WaitForChild("Humanoid") :: Humanoid
	local root = character:WaitForChild("HumanoidRootPart") :: BasePart
	local head = character:WaitForChild("Head") :: BasePart
	s.hipHeight = humanoid.HipHeight
	humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None

	local attachment = Instance.new("Attachment")
	attachment.Name = "AshFlashlight"
	attachment.Position = Vector3.new(0, 0.2, -0.6)
	attachment.Parent = head
	local light = Instance.new("SpotLight")
	light.Name = "AshFlashlight"
	light.Angle = Config.flashlight.angle
	light.Range = Config.flashlight.range
	light.Brightness = Config.flashlight.brightness
	light.Color = Color3.fromRGB(255, 240, 220)
	light.Shadows = true
	light.Face = Enum.NormalId.Front
	light.Enabled = false
	light.Parent = attachment
	s.light = light
	s.lightAttachment = attachment

	local prompt = Instance.new("ProximityPrompt")
	prompt.Name = "Revive"
	prompt.ActionText = "Revive"
	prompt.ObjectText = player.DisplayName
	prompt.HoldDuration = 0.2
	prompt.MaxActivationDistance = 8
	prompt.RequiresLineOfSight = false
	prompt.Enabled = false
	prompt.Parent = root
	prompt.Triggered:Connect(function(rescuer: Player)
		if rescuer == player or not s.downed or s.taken then
			return
		end
		Crew.commit(rescuer, Config.commit.revive, `Getting {player.DisplayName} up`, function()
			Crew.revive(player)
		end)
	end)
	s.revivePrompt = prompt

	local gold = Instance.new("Part")
	gold.Name = "RaisedGold"
	gold.Shape = Enum.PartType.Ball
	gold.Size = Vector3.one * 0.6
	gold.Color = Color3.fromRGB(214, 172, 60)
	gold.Material = Enum.Material.Metal
	gold.CanCollide = false
	gold.CanQuery = false
	gold.Massless = true
	gold.Transparency = 1
	local weld = Instance.new("Weld")
	weld.Part0 = head
	weld.Part1 = gold
	weld.C0 = CFrame.new(-0.8, -0.2, -1.6)
	weld.Parent = gold
	gold.Parent = character
	s.goldPart = gold

	refreshSpeed(player)
	updateLight(player)

	character.ChildAdded:Connect(function(child)
		if child:IsA("Tool") and (s.downed or s.taken or s.commit) then
			task.defer(function()
				humanoid:UnequipTools()
			end)
		end
	end)

	task.spawn(function()
		if not character.Parent then
			character.AncestryChanged:Wait()
		end
		task.wait()
		local cf = Crew.spawnCFrame(player)
		if cf then
			character:PivotTo(cf)
		end
	end)
	Crew.characterReady:Fire(player, character)
end

local function onPlayer(player: Player)
	states[player] = newState()
	player.CameraMode = Enum.CameraMode.LockFirstPerson
	player.CameraMaxZoomDistance = 0.5
	player:SetAttribute("MoveMode", "walk")
	player:SetAttribute("HasGold", false)
	player:SetAttribute("Battery", Config.flashlight.battery)
	player.CharacterAdded:Connect(function(character)
		onCharacter(player, character)
	end)
	if player.Character then
		task.spawn(onCharacter, player, player.Character)
	end
end

------------------------------------------------------------------ start

function Crew.start()
	Net.event("Move").OnServerEvent:Connect(function(player, mode)
		local s = states[player]
		if s and (mode == "walk" or mode == "sprint" or mode == "crouch") then
			s.mode = mode
			player:SetAttribute("MoveMode", mode)
			refreshSpeed(player)
		end
	end)

	Net.event("Flashlight").OnServerEvent:Connect(function(player, on)
		local s = states[player]
		if s and typeof(on) == "boolean" then
			s.flashlightOn = on
			updateLight(player)
		end
	end)

	Net.unreliable("Aim").OnServerEvent:Connect(function(player, direction)
		local s = states[player]
		if not s or typeof(direction) ~= "Vector3" or direction.Magnitude < 0.5 or direction.Magnitude ~= direction.Magnitude then
			return
		end
		s.aim = direction.Unit
		local head = Crew.head(player)
		if head and s.lightAttachment then
			local rel = head.CFrame:VectorToObjectSpace(s.aim)
			local origin = Vector3.new(0, 0.2, -0.6)
			s.lightAttachment.CFrame = CFrame.lookAt(origin, origin + rel)
		end
	end)

	Net.event("Ward").OnServerEvent:Connect(raiseWard)

	Players.PlayerAdded:Connect(onPlayer)
	for _, player in Players:GetPlayers() do
		onPlayer(player)
	end
	Players.PlayerRemoving:Connect(function(player)
		local s = states[player]
		states[player] = nil
		if s and s.hasGold then
			Crew.goldLost:Fire()
		end
		task.defer(checkWipe)
	end)

	-- Footstep noise.
	task.spawn(function()
		local n = Config.player.noise
		while true do
			task.wait(n.sampleEvery)
			for player, s in states do
				local root = Crew.root(player)
				if root and Crew.isActive(player) then
					local v = root.AssemblyLinearVelocity
					local speed = Vector3.new(v.X, 0, v.Z).Magnitude
					if speed > 2 then
						local radius = if s.mode == "sprint" and speed > Config.player.walkSpeed + 2
							then n.sprint
							elseif s.mode == "crouch" then n.crouch
							else n.walk
						Noise.emit(root.Position, radius, "footsteps", player)
					end
				end
			end
		end
	end)

	-- Battery, regeneration in sanctuaries, taken players coming back.
	task.spawn(function()
		local last = os.clock()
		while true do
			task.wait(0.5)
			local now = os.clock()
			local dt = now - last
			last = now
			local safeRoot: BasePart? = nil
			local anyTaken = false
			for player, s in states do
				if lightOn(s) then
					s.battery = math.max(0, s.battery - dt)
					if s.battery <= 0 then
						s.flashlightOn = false
						Say.to(player, "Your torch is dead. Find batteries.", 4, "hint")
					end
					updateLight(player)
				end
				if s.taken then
					anyTaken = true
				end
				local root = Crew.root(player)
				if root and Crew.isActive(player) and Map.isSanctuary(root.Position) then
					safeRoot = root
					if s.hits > 0 and now - s.lastRegen >= Config.player.sanctuaryRegenEvery then
						s.lastRegen = now
						s.hits -= 1
						player:SetAttribute("Hits", s.hits)
					end
				else
					s.lastRegen = now
				end
			end
			if anyTaken and safeRoot then
				Crew.restoreTaken(safeRoot.CFrame)
			end
			checkWipe()
		end
	end)
end

return Crew
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Director"}, class = "ModuleScript", source = [=[
--[[
	Director: Story 1, start to finish. Chapters, objectives, checkpoints,
	story beats and party wipes. Everything else reacts to the systems; this
	is the only file that knows the story's order.

	  I    The Second Crew      van -> hall. Find the camp and the manifest.
	  II   The Portrait Gallery the Dullahan. Secure the spine whip.
	                            First distant keen.
	  III  The Servants' Wing   the Lamp-shy. She mourns in the kitchen;
	                            the first keen. Secure the hollow lantern.
	                            The storm cuts the hall's power.
	  IV   The Cellar Vault     the opened box. Her keen with nothing to
	                            kill. Back to the van; she keeps keening.

	Checkpoints are the chapter starts. A wipe puts everyone back at the
	last one with the ammo they had there.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Config = require(Shared:WaitForChild("Config"))
local Net = require(Shared:WaitForChild("Net"))

local Ashgrove = script.Parent
local Banshee = require(Ashgrove.Banshee)
local BellBoard = require(Ashgrove.BellBoard)
local Crew = require(Ashgrove.Crew)
local Doors = require(Ashgrove.Doors)
local Map = require(Ashgrove.Map)
local Models = require(Ashgrove.Models)
local Pickups = require(Ashgrove.Pickups)
local Reading = require(Ashgrove.Reading)
local Retrieval = require(Ashgrove.Retrieval)
local Rites = require(Ashgrove.Rites)
local Say = require(Ashgrove.Say)
local Shots = require(Ashgrove.Shots)
local Storm = require(Ashgrove.Storm)
local Entity = require(Ashgrove.Entities.Entity)
local Registry = require(Ashgrove.Entities.Registry)
local DullahanBehaviour = require(Ashgrove.Entities.Dullahan)
local LampshyBehaviour = require(Ashgrove.Entities.Lampshy)

local Director = {}

type Objective = { text: string, done: boolean? }

local chapter = 0
local chapterStartedAt = 0
local checkpointName = "Spawn_Van"
local objectives: { Objective } = {}
local flags: { [string]: any } = {}
local wiping = false

local dullahan
local lampshy

local function anyoneIn(wing: string): boolean
	return #Crew.playersInWing(wing) > 0
end

local function anyoneInRoom(room: string): boolean
	for _, player in Crew.activePlayers() do
		local root = Crew.root(player)
		if root and Map.roomAt(root.Position) == room then
			return true
		end
	end
	return false
end

local function setObjectives(list: { Objective })
	objectives = list
	Net.event("Objectives"):FireAllClients(objectives)
end

local function tick(index: number)
	if objectives[index] and not objectives[index].done then
		objectives[index].done = true
		Net.event("Objectives"):FireAllClients(objectives)
	end
end

local function setCheckpoint(name: string)
	checkpointName = name
end

local function card(title: string, subtitle: string)
	Net.event("Chapter"):FireAllClients(title, subtitle)
end

------------------------------------------------------------------ chapters

local enterChapter: (number) -> ()

local function chapterOne()
	setCheckpoint("Spawn_Van")
	card("I. The Second Crew", "Ashgrove House. One night. A storm off the sea.")
	setObjectives({
		{ text = "Go into Ashgrove House" },
		{ text = "Find the first crew's camp in the hall" },
	})
	task.delay(4, function()
		Say.all("Shift sprint, C crouch, F torch, G raise gold, E interact, H help.", 10, "hint")
	end)
end

local function chapterTwo()
	setCheckpoint("Spawn_HallCamp")
	Pickups.roll()
	dullahan:activate()
	card("II. The Portrait Gallery", "Lot 114. The spine whip.")
	setObjectives({
		{ text = "Secure Lot 114, the spine whip (far end of the portrait gallery)" },
		{ text = "Optional: take Cornelius's gold sovereign (case in the hall)" },
	})
end

local function chapterThree()
	setCheckpoint("Spawn_HallCamp")
	Doors.setLocked("ServantsDoor", false)
	Say.all("Okafor's keys were in the tack case. The servants' door is open.", 5, "story")
	lampshy:activate()
	card("III. The Servants' Wing", "Lot 203. The hollow lantern.")
	setObjectives({
		{ text = "Secure Lot 203, the hollow lantern (scullery, servants' wing)" },
		{ text = "Lot 077, the silver comb, is missing. Leave it." },
	})
end

local function chapterFour()
	setCheckpoint("Spawn_Stairwell")
	Doors.setLocked("VaultGate", false)
	Banshee.setNatural(false)
	Say.all("The chain on the cellar gate has rusted through. The way down is open.", 5, "story")
	card("IV. The Cellar Vault", "Lot 001. The sealed box.")
	setObjectives({
		{ text = "Find Lot 001, the sealed box (cellar vault)" },
	})
end

local CHAPTERS = { chapterOne, chapterTwo, chapterThree, chapterFour }

enterChapter = function(n: number)
	if n <= chapter or not CHAPTERS[n] then
		return
	end
	chapter = n
	chapterStartedAt = os.clock()
	CHAPTERS[n]()
end

local function ending()
	if flags.ended then
		return
	end
	flags.ended = true
	setObjectives({ { text = "You got out.", done = true } })
	for _, e in Registry.all() do
		e:retire()
	end
	local door = CFrame.lookAt(Vector3.new(-64, 0, 0), Vector3.new(-130, 0, 0))
	Banshee.ending(door)
	Say.all("[The keening doesn't stop]", 4, "sound")
	task.wait(4)
	Say.all("You're out in the rain, and she's still keening.", 5, "story")
	task.wait(5)
	Say.all("It wasn't about you.", 5, "story")
	task.wait(4)
	-- The first crew's dead van, behind you.
	local lights = Map.root():FindFirstChild("CrewOneHeadlights", true)
	local beam = lights and lights:FindFirstChildOfClass("SpotLight")
	if lights and beam and lights:IsA("BasePart") then
		lights.Material = Enum.Material.Neon
		beam.Enabled = true
		Say.all("[Behind you, the first crew's van flashes its headlights once]", 4, "sound")
		task.wait(0.6)
		beam.Enabled = false
		lights.Material = Enum.Material.Glass
	end
	task.wait(4)
	Net.event("Screen"):FireAllClients("end", "END OF STORY 1\n\nThe box was empty.\nSomebody is wearing what was in it.")
end

------------------------------------------------------------------ story beats

local function onSecured(objectId: string)
	if objectId == "SpineWhip" then
		tick(1)
		Storm.escalate()
		enterChapter(3)
	elseif objectId == "HollowLantern" then
		tick(1)
		Storm.escalate()
		enterChapter(4)
	end
end

local function onInspected(objectId: string, player: Player)
	if objectId ~= "DybbukBox" then
		return
	end
	tick(1)
	Say.all("The seal is broken. The box is empty.", 5, "story")
	task.wait(Config.story.ruleBreakDelay)
	if flags.ended then
		return
	end
	-- The rule-break: she keens with nothing here to kill. It's for one of you.
	local target = if table.find(Crew.playersInWing("Vault"), player) then player else nil
	if Banshee.keen("Vault", { forced = true, target = target }) then
		flags.ruleBreak = true
		setObjectives({ { text = "Nothing down here can die in your place. Keep the custom, or get out." } })
	else
		flags.finale = true
		setObjectives({ { text = "Get everyone back to the van" } })
	end
end

local function onKeenEnded(wing: string, _outcome: string)
	if chapter == 3 and wing == "ServantsWing" and not flags.naturalOn then
		flags.naturalOn = true
		Banshee.setNatural(true)
	end
	if flags.ruleBreak and wing == "Vault" and not flags.finale then
		flags.finale = true
		setObjectives({ { text = "Get everyone back to the van" } })
	end
end

local function storyLoop()
	while not flags.ended do
		task.wait(0.5)
		local now = os.clock()
		if chapter == 1 then
			if anyoneIn("Hall") then
				tick(1)
			end
			if anyoneIn("Gallery") then
				enterChapter(2)
			end
		elseif chapter == 2 then
			if not flags.distant and now - chapterStartedAt >= Config.story.firstDistantDelay then
				flags.distant = true
				Banshee.enableDistant()
				Banshee.distantNow()
			end
		elseif chapter == 3 then
			if not flags.distant then
				flags.distant = true
				Banshee.enableDistant()
			end
			if not flags.kitchenMourning and anyoneInRoom("Kitchen") then
				flags.kitchenMourning = true
				task.delay(Config.story.kitchenMourningDelay, function()
					if not Banshee.mourn(Map.marker("Body_Kitchen").Position, { noteId = "Memo_Kitchen", key = "Kitchen", grace = 6 }) then
						Reading.reveal("Memo_Kitchen")
						flags.firstKeenAt = os.clock() + Config.story.firstKeenDelay
					end
				end)
			end
			if flags.firstKeenAt and not flags.firstKeen and now >= flags.firstKeenAt and anyoneIn("ServantsWing") then
				if Banshee.keen("ServantsWing", { forced = true }) then
					flags.firstKeen = true
				end
			end
		elseif chapter == 4 then
			if flags.finale then
				local everyone = true
				local anyone = false
				for _, player in Players:GetPlayers() do
					local s = Crew.state(player)
					if s and not s.taken then
						anyone = true
						local root = Crew.root(player)
						if not Crew.isActive(player) or not root or Map.wingAt(root.Position) ~= "Van" then
							everyone = false
						end
					end
				end
				if anyone and everyone then
					task.spawn(ending)
				end
			end
		end
	end
end

------------------------------------------------------------------ wipes

local function onWipe()
	if wiping or flags.ended then
		return
	end
	wiping = true
	Net.event("Screen"):FireAllClients("wipe", "The house keeps you.")
	task.wait(3)
	Banshee.reset()
	for _, e in Registry.all() do
		e:reset()
	end
	Doors.clearLockouts()
	Crew.resetAll(Map.marker(checkpointName).CFrame)
	if flags.ruleBreak and not flags.finale then
		-- The vault keen is lost with the wipe; go straight to the escape.
		flags.finale = true
		setObjectives({ { text = "Get everyone back to the van" } })
	end
	Net.event("Screen"):FireAllClients("clear", "")
	Say.all("Back to the last safe place.", 4, "story")
	wiping = false
end

------------------------------------------------------------------ debug

local function onDebug(player: Player, command: any)
	if not RunService:IsStudio() or not Config.debug.studioKeys then
		return
	end
	if command == "next" then
		if chapter == 1 then
			enterChapter(2)
		elseif chapter == 2 then
			Retrieval.forceSecure("SpineWhip")
		elseif chapter == 3 then
			Retrieval.forceSecure("HollowLantern")
		end
		Say.to(player, `[debug] chapter {chapter}`, 3, "hint")
	elseif command == "keen" then
		local root = Crew.root(player)
		local wing = root and Map.wingAt(root.Position)
		if not wing or not Banshee.keen(wing, { forced = true, target = player }) then
			Say.to(player, "[debug] can't keen here (hall, van and grounds never keen)", 3, "hint")
		end
	elseif command == "refill" then
		Crew.addBattery(player, Config.flashlight.maxBattery)
		Say.to(player, "[debug] torch refilled", 2, "hint")
	end
end

------------------------------------------------------------------ start

function Director.start()
	Map.root()
	Storm.start()
	Doors.setup()
	Rites.setup()
	Reading.setup()
	Retrieval.setup()
	for _, objectId in { "SpineWhip", "HollowLantern", "DybbukBox" } do
		Retrieval.setEnabled(objectId, true)
	end

	Crew.spawnCFrame = function()
		return Map.marker(checkpointName).CFrame
	end
	Models.collect()
	Shots.start()
	Crew.start()
	Pickups.setup()

	dullahan = Entity.new("Dullahan", Config.entities.Dullahan, DullahanBehaviour)
	lampshy = Entity.new("Lampshy", Config.entities.Lampshy, LampshyBehaviour)
	Entity.startLoop()
	Banshee.setup()
	BellBoard.start()

	Retrieval.secured:Connect(onSecured)
	Retrieval.inspected:Connect(onInspected)
	Banshee.keenEnded:Connect(onKeenEnded)
	Banshee.keenStarted:Connect(function(wing: string)
		if chapter == 3 and wing == "ServantsWing" then
			flags.firstKeen = true
		end
	end)
	Banshee.mourningEnded:Connect(function(key: string?, disturbed: boolean)
		if key == "Kitchen" and not disturbed and not flags.firstKeenAt then
			flags.firstKeenAt = os.clock() + Config.story.firstKeenDelay
		end
	end)
	Reading.read:Connect(function(noteId: string)
		if noteId == "Manifest" and chapter == 1 then
			tick(2)
		end
	end)
	Crew.wiped:Connect(onWipe)
	Net.event("Debug").OnServerEvent:Connect(onDebug)

	Players.PlayerAdded:Connect(function(player)
		task.delay(2, function()
			Net.event("Objectives"):FireClient(player, objectives)
		end)
	end)

	enterChapter(1)
	task.spawn(storyLoop)
end

return Director
]=] },
}

local function child(parent: Instance, name: string): Instance
	local found = parent:FindFirstChild(name)
	assert(found, `[Ashgrove] expected {parent:GetFullName()}.{name} (paste the parts in order, starting from part 1)`)
	return found :: Instance
end

local function serviceAt(names: { string }): Instance
	local node: Instance = game:GetService(names[1])
	for i = 2, #names do
		node = child(node, names[i])
	end
	return node
end

local function install()
	local ChangeHistoryService = game:GetService("ChangeHistoryService")
	local ok, recording = pcall(function()
		return ChangeHistoryService:TryBeginRecording("Install Ashgrove House")
	end)
	if not ok then
		recording = nil
	end

	-- Remove older installs first.
	if REMOVE_OLD then
		for _, r in ROOTS do
			local old = serviceAt(r.service):FindFirstChild(r.name)
			if old then
				old:Destroy()
			end
		end
	end

	for _, f in FILES do
		local parent = serviceAt(f.service)
		for i = 1, #f.path - 1 do
			parent = child(parent, f.path[i])
		end
		local existing = parent:FindFirstChild(f.path[#f.path])
		if existing then
			existing:Destroy()
		end
		local inst = Instance.new(f.class)
		inst.Name = f.path[#f.path]
		if f.source then
			(inst :: any).Source = f.source
		end
		inst.Parent = parent
	end

	if FINISH then
		for _, name in { "Baseplate", "SpawnLocation" } do
			local leftover = workspace:FindFirstChild(name)
			if leftover and leftover:IsA("BasePart") then
				leftover:Destroy()
			end
		end
		if not workspace:FindFirstChild("AshgroveHouse") then
			require(game:GetService("ServerScriptService").Ashgrove.House).build()
		end
	end

	if recording then
		pcall(function()
			ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
		end)
	end
	print(DONE_MESSAGE)
end

if plugin then
	local toolbar = plugin:CreateToolbar("Ashgrove")
	local button = toolbar:CreateButton("Install", "Install or update Ashgrove House in this place", "")
	button.ClickableWhenViewportHidden = true
	button.Click:Connect(install)
else
	install()
end
