--[[
	ASHGROVE HOUSE installer, PART 4 OF 8.
	Generated by ashgrove/tools/build_installer.py. Don't edit by hand.

	Paste the parts into Studio's Command Bar IN ORDER (1, 2, 3 ...),
	pressing Enter after each. Wait for the Output window to say
	"part 4 of 8 done" before pasting the next one.
	Next: part 5.
]]

local REMOVE_OLD = false
local FINISH = false
local DONE_MESSAGE = "[Ashgrove] part 4 of 8 done. Now paste part 5."
local ROOTS = {
	{ service = {"ReplicatedStorage"}, name = "Ashgrove" },
	{ service = {"ServerScriptService"}, name = "Ashgrove" },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, name = "AshgroveClient" },
}

local FILES = {
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Entities", "Dullahan"}, class = "ModuleScript", source = [=[
--[[
	The Dullahan (portrait gallery). Killable. Lot 114, the spine whip.

	RULE: it sees only what its carried head is facing.

	- Idle: walks the gallery, stopping to hold the head up to portraits
	  and windows. Stay out of the head's view and you can pass behind him.
	- The kill window closes at whip reach (about 12 studs), not contact.
	- Weak point: the head. Hit it and he drops it and gropes blind for
	  Config.blindTime seconds; body shots then kill him. Body shots while
	  he holds the head only stagger him.
	- Gold raised where the head can see it drives him back. No kill.
	- Death: the body falls apart, the head keeps glowing where it rolled
	  for a while (a light source), and the Banshee may come to mourn.
]]

local Debris = game:GetService("Debris")
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))

local Ashgrove = script.Parent.Parent
local Crew = require(Ashgrove.Crew)
local Map = require(Ashgrove.Map)
local Noise = require(Ashgrove.Noise)
local Say = require(Ashgrove.Say)
local Rigs = require(script.Parent.Rigs)

local cfg = Config.entities.Dullahan

local Dullahan = {}

local function flat(v: Vector3): Vector3
	local f = Vector3.new(v.X, 0, v.Z)
	return if f.Magnitude > 1e-4 then f.Unit else Vector3.new(0, 0, -1)
end

local function hasHead(e): boolean
	local d = e.data
	return not d.blind and d.head ~= nil and d.headJoint ~= nil and d.headJoint.Parent ~= nil
end

-- Sets the head's turn on its joint (C0 if the head is the joint's Part1,
-- otherwise C1), from the pose it had when built.
local function poseHead(d)
	local turn = CFrame.Angles(0, d.headYaw or 0, 0)
	if d.headJoint.Part1 == d.head then
		d.headJoint.C0 = d.headBase * turn
	else
		d.headJoint.C1 = d.headBase * turn:Inverse()
	end
end

local function headLook(e): Vector3
	return flat(e.data.head.CFrame.LookVector)
end

-- Turns the carried head towards a world direction, at `rate` radians/s.
local function turnHeadTowards(e, direction: Vector3, dt: number, rate: number)
	if not hasHead(e) then
		return
	end
	local rel = e.root.CFrame:VectorToObjectSpace(flat(direction))
	local target = math.clamp(math.atan2(-rel.X, -rel.Z), math.rad(-150), math.rad(150))
	local current = e.data.headYaw or 0
	local step = math.clamp(target - current, -rate * dt, rate * dt)
	e.data.headYaw = current + step
	poseHead(e.data)
end

local function headSees(e, player: Player, range: number): boolean
	if not hasHead(e) then
		return false
	end
	local head = Crew.head(player)
	if not head then
		return false
	end
	local from = e.data.head.Position
	local offset = head.Position - from
	if offset.Magnitude > range then
		return false
	end
	local inCone = headLook(e):Dot(flat(offset)) >= math.cos(math.rad(cfg.fieldOfView / 2))
	return inCone and e:canSee(from, player, range)
end

local function findTarget(e): Player?
	local best, bestDistance = nil, math.huge
	for _, player in e:targets() do
		local d = e:distanceTo(player)
		if d < bestDistance and (d <= cfg.touchRange or headSees(e, player, cfg.sightRange)) then
			best, bestDistance = player, d
		end
	end
	return best
end

local function startHunt(e, player: Player)
	local d = e.data
	local wasHunting = e.state == "Hunt" or e.state == "Windup" or e.state == "Recover"
	d.target = player
	d.lastSeen = os.clock()
	local root = Crew.root(player)
	d.lastSeenPos = if root then root.Position else e.root.Position
	if not wasHunting then
		Say.to(player, "[The head turns towards you]", 3, "sound")
		Audio.play("dullahanBreath", e.root, 0.8)
	end
	e:setState("Hunt")
end

local function alert(e, position: Vector3)
	e.data.alertPos = position
	e:setState("Alert")
end

local function dropHead(e)
	local d = e.data
	if not hasHead(e) or not d.canDropHead then
		return
	end
	d.headJoint:Destroy()
	d.headJoint = nil
	d.blind = true
	d.bodyHits = 0
	local head: BasePart = d.head
	head.Massless = false
	head.CanCollide = true
	head.AssemblyLinearVelocity = flat(e.root.CFrame.LookVector) * 6 + Vector3.new(0, 8, 0)
	pcall(function()
		head:SetNetworkOwner(nil)
	end)
	Audio.play("headDrop", head, 0.8)
	Noise.emit(head.Position, 25, "impact")
	e.animOverride = "blind"
	e:setState("Blind")
end

local function returnHead(e)
	local d = e.data
	local head: BasePart = d.head
	if not head or not head.Parent or not e.root then
		return
	end
	head.CanCollide = false
	head.Massless = true
	head.AssemblyLinearVelocity = Vector3.zero
	d.headYaw = 0
	local joint = d.headTemplate:Clone()
	joint.Parent = head
	d.headJoint = joint
	poseHead(d)
	d.blind = false
	e.animOverride = nil
	Say.near(e.root.Position, 60, "[He finds his head]", 3, "sound")
end

local function repel(e, from: Vector3)
	e.data.repelFrom = from
	e:setState("Repelled")
	Say.near(e.root.Position, 50, "[He recoils from the gold]", 3, "sound")
end

------------------------------------------------------------------ behaviour

function Dullahan.build(e)
	local model, root, humanoid, parts = Rigs.dullahan()
	local joint = parts.headJoint
	e.data.head = parts.head
	e.data.headJoint = joint
	-- Kept to put the head back after it's been shot out of his hands.
	e.data.headTemplate = joint:Clone()
	e.data.headBase = if joint.Part1 == parts.head then joint.C0 else joint.C1
	e.data.canDropHead = parts.head ~= root
	e.data.headYaw = 0
	e.data.route = Map.markers("Dullahan_Route_")
	e.data.routeIndex = 1
	e.data.routeDir = 1
	e.data.pauseUntil = 0
	e.data.nextTrace = os.clock() + 15
	return model, root, humanoid
end

function Dullahan.step(e, dt: number)
	local d = e.data
	local now = os.clock()
	local root: BasePart = e.root

	-- Traces before contact: a whip-crack that carries out of the gallery.
	if now >= d.nextTrace and (e.state == "Idle" or e.state == "Alert") then
		d.nextTrace = now + 20 + math.random() * 20
		Audio.play("dullahanWhip", root, 0.5, 200)
		Say.near(root.Position, 160, "[A whip-crack, somewhere down the gallery]", 3, "sound")
	end

	-- Gold he can see drives him back.
	if hasHead(e) and e.state ~= "Repelled" then
		for _, player in Crew.activePlayers() do
			if Crew.isWardRaised(player) and headSees(e, player, Config.ward.range) then
				local r = Crew.root(player)
				if r then
					repel(e, r.Position)
				end
				break
			end
		end
	end

	local state = e.state
	if state == "Idle" then
		local seen = findTarget(e)
		if seen then
			startHunt(e, seen)
			return
		end
		local route = d.route
		if #route == 0 then
			e:stop()
			return
		end
		local stop: BasePart = route[d.routeIndex]
		local offset = stop.Position - root.Position
		if Vector3.new(offset.X, 0, offset.Z).Magnitude < 3 then
			e:stop()
			if d.pauseUntil == 0 then
				d.pauseUntil = now + cfg.idlePauseMin + math.random() * (cfg.idlePauseMax - cfg.idlePauseMin)
			end
			local look = stop:GetAttribute("Look")
			if typeof(look) == "Vector3" then
				turnHeadTowards(e, look - root.Position, dt, 1.5)
			end
			if now >= d.pauseUntil then
				d.pauseUntil = 0
				local nextIndex = d.routeIndex + d.routeDir
				if nextIndex < 1 or nextIndex > #route then
					d.routeDir = -d.routeDir
					nextIndex = d.routeIndex + d.routeDir
				end
				d.routeIndex = math.clamp(nextIndex, 1, #route)
			end
		else
			e:moveTo(stop.Position, cfg.walkSpeed)
			-- The head sweeps slowly while he walks.
			local sweep = math.sin(now * 0.6) * 0.9
			turnHeadTowards(e, root.CFrame:VectorToWorldSpace(CFrame.Angles(0, sweep, 0).LookVector), dt, 1.2)
		end
	elseif state == "Alert" then
		local seen = findTarget(e)
		if seen then
			startHunt(e, seen)
			return
		end
		local goal: Vector3 = d.alertPos or root.Position
		turnHeadTowards(e, goal - root.Position, dt, 2.5)
		if (Vector3.new(goal.X - root.Position.X, 0, goal.Z - root.Position.Z)).Magnitude > 4 then
			e:moveTo(goal, cfg.walkSpeed)
		else
			e:stop()
		end
		if e:inState() > cfg.searchTime then
			e:setState("Idle")
		end
	elseif state == "Hunt" then
		local target: Player? = d.target
		if not e:canTarget(target) then
			alert(e, d.lastSeenPos or root.Position)
			return
		end
		local targetRoot = Crew.root(target :: Player) :: BasePart
		if headSees(e, target :: Player, cfg.sightRange) or e:distanceTo(target :: Player) <= cfg.touchRange then
			d.lastSeen = now
			d.lastSeenPos = targetRoot.Position
		elseif now - (d.lastSeen or 0) > cfg.loseTargetAfter then
			alert(e, d.lastSeenPos)
			return
		end
		turnHeadTowards(e, targetRoot.Position - root.Position, dt, 5)
		local distance = e:distanceTo(target :: Player)
		if distance <= cfg.whipRange and e:canSee(root.Position, target :: Player, cfg.whipRange + 2) then
			e:stop()
			e:face(targetRoot.Position)
			Say.to(target :: Player, "[The whip draws back]", 2, "sound")
			e:setState("Windup")
		else
			e:moveTo(targetRoot.Position, cfg.huntSpeed)
		end
	elseif state == "Windup" then
		local target: Player? = d.target
		if target and Crew.root(target) then
			e:face((Crew.root(target) :: BasePart).Position)
		end
		if e:inState() >= cfg.windupTime then
			e:action("attack")
			Audio.play("dullahanWhip", root, 1, 200)
			Say.near(root.Position, 80, "[CRACK]", 2, "sound")
			if target and e:canTarget(target) and e:distanceTo(target) <= cfg.whipRange + 1.5 and e:canSee(root.Position, target, cfg.whipRange + 3) then
				Crew.hit(target, 1)
			end
			e:setState("Recover")
		end
	elseif state == "Recover" then
		e:stop()
		if e:inState() >= cfg.recoverTime then
			if e:canTarget(d.target) then
				e:setState("Hunt")
			else
				alert(e, d.lastSeenPos or root.Position)
			end
		end
	elseif state == "Stagger" then
		e:stop()
		if e:inState() >= cfg.staggerTime then
			if e:canTarget(d.target) then
				startHunt(e, d.target)
			else
				alert(e, d.lastSeenPos or root.Position)
			end
		end
	elseif state == "Blind" then
		-- Groping towards the last thing he heard.
		local goal: Vector3? = d.gropeTo
		if goal and (Vector3.new(goal.X - root.Position.X, 0, goal.Z - root.Position.Z)).Magnitude > 3 then
			e:moveTo(goal, 5)
		else
			e:stop()
		end
		if e:inState() >= cfg.blindTime then
			returnHead(e)
			local seen = findTarget(e)
			if seen then
				startHunt(e, seen)
			else
				alert(e, d.lastSeenPos or root.Position)
			end
		end
	elseif state == "Repelled" then
		local from: Vector3 = d.repelFrom or root.Position
		turnHeadTowards(e, from - root.Position, dt, 4)
		local away = flat(root.Position - from)
		e:moveTo(root.Position + away * 10, cfg.huntSpeed)
		if e:inState() >= cfg.repelTime then
			if e:canTarget(d.target) then
				e:setState("Hunt")
			else
				e:setState("Idle")
			end
		end
	end
end

function Dullahan.onShot(e, part: BasePart, shooter: Player, _position: Vector3)
	local d = e.data
	local hitbox = part:GetAttribute("Hitbox")
	if hitbox == "Head" and hasHead(e) then
		d.target = shooter
		d.lastSeen = os.clock()
		dropHead(e)
		Say.to(shooter, "Hit the head. He's blind. Now.", 3, "hint")
		Say.near(e.root.Position, 80, "[The head hits the floor and rolls]", 3, "sound")
		return
	end
	if d.blind then
		d.bodyHits = (d.bodyHits or 0) + 1
		if d.bodyHits >= cfg.bodyHitsToKillWhileBlind then
			e:banish(shooter)
		else
			Say.near(e.root.Position, 60, "[He staggers]", 2, "sound")
		end
		return
	end
	if not d.taughtBody then
		d.taughtBody = true
		Say.to(shooter, "Body shots don't stop him.", 3, "hint")
	end
	d.target = shooter
	d.lastSeen = os.clock()
	local r = Crew.root(shooter)
	d.lastSeenPos = if r then r.Position else e.root.Position
	e:setState("Stagger")
end

function Dullahan.onNoise(e, noise, sameWing: boolean)
	local d = e.data
	if e.state == "Blind" then
		if sameWing then
			d.gropeTo = noise.position
		end
		return
	end
	if e.state == "Idle" or e.state == "Alert" then
		if sameWing then
			alert(e, noise.position)
		end
	end
end

function Dullahan.onAgitate(e, position: Vector3)
	if e.state == "Idle" then
		alert(e, position)
	end
end

function Dullahan.onBanish(e, model: Model, _killer: Player?)
	local d = e.data
	local head: BasePart? = d.head
	local position = model:GetPivot().Position
	-- The head stays, still glowing, where it rolled.
	if head and d.canDropHead then
		if d.headJoint then
			d.headJoint:Destroy()
		end
		head.Massless = false
		head.CanCollide = true
		head.CanQuery = false
		head:SetAttribute("LightRadius", cfg.headGlowRadius)
		head.Parent = Map.interact("Glows")
		pcall(function()
			head:SetNetworkOwner(nil)
		end)
		Debris:AddItem(head, cfg.headGlowTime)
	end
	-- The body comes apart.
	local root = model:FindFirstChild("HumanoidRootPart") :: BasePart?
	if root then
		root.Anchored = true
		root.CanCollide = false
	end
	for _, p in model:GetDescendants() do
		if p:IsA("WeldConstraint") or p:IsA("JointInstance") then
			p:Destroy()
		elseif p:IsA("BasePart") and p ~= root then
			p.CanCollide = true
			p.CanQuery = false
		end
	end
	task.delay(5, function()
		for _, p in model:GetDescendants() do
			if p:IsA("BasePart") then
				TweenService:Create(p, TweenInfo.new(3), { Transparency = 1 }):Play()
			end
		end
		task.delay(3, function()
			model:Destroy()
		end)
	end)
	for _, player in Players:GetPlayers() do
		local r = Crew.root(player)
		if r and (r.Position - position).Magnitude < 120 then
			Say.to(player, "[He comes apart. The head keeps glowing.]", 4, "sound")
		end
	end
end

return Dullahan
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Entities", "Entity"}, class = "ModuleScript", source = [=[
--[[
	Entity: what every killable entity shares. A behaviour module (Dullahan,
	Lampshy) supplies the rule; this supplies the body, the binding and
	the movement.

	The binding (direction doc, section 6):
	  - killing a manifestation BANISHES it back into its object. It
	    re-forms at its spawn after Config.entities.reformMin..Max seconds
	  - securing the object (Retrieval) removes it for the rest of the story
	  - every banish fires Registry.died, which the Banshee counts as a death

	status: "dormant" (not in the story yet) | "active" | "banished" | "secured"

	Entities never leave their wing, and never target players who are in a
	sanctuary or outside the wing.

	A behaviour module provides:
	  build(e) -> (Model, root: BasePart, Humanoid)   e.data is fresh
	  step(e, dt)
	  onShot(e, part, shooter, position)
	  onNoise(e, noise)?   onAgitate(e, position)?   onBanish(e, model, killer)?
]]

local Players = game:GetService("Players")
local PathfindingService = game:GetService("PathfindingService")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local Config = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Config"))

local Ashgrove = script.Parent.Parent
local Crew = require(Ashgrove.Crew)
local Map = require(Ashgrove.Map)
local Models = require(Ashgrove.Models)
local Noise = require(Ashgrove.Noise)
local Shots = require(Ashgrove.Shots)
local Registry = require(script.Parent.Registry)

local Entity = {}
Entity.__index = Entity

local entityFolder: Folder? = nil
local function folder(): Folder
	if not entityFolder or not entityFolder.Parent then
		local f = Instance.new("Folder")
		f.Name = "Entities"
		f.Parent = Map.root()
		entityFolder = f
	end
	return entityFolder :: Folder
end

function Entity.new(id: string, cfg: { [string]: any }, behaviour: { [string]: any })
	local self = setmetatable({
		id = id,
		cfg = cfg,
		wing = cfg.wing,
		behaviour = behaviour,
		status = "dormant",
		model = nil :: Model?,
		root = nil :: BasePart?,
		humanoid = nil :: Humanoid?,
		state = "Idle",
		stateAt = 0,
		data = {} :: { [string]: any },
		reformAt = 0,
		waypoints = nil :: { PathWaypoint }?,
		waypointIndex = 0,
		pathGoal = Vector3.zero,
		pathAt = 0,
		pathBusy = false,
		anim = nil :: Models.Animations?,
		animOverride = nil :: string?,
	}, Entity)
	Registry.add(self)
	return self
end

function Entity:setState(name: string)
	if self.state ~= name then
		self.state = name
		self.stateAt = os.clock()
	end
end

function Entity:inState(): number
	return os.clock() - self.stateAt
end

function Entity:position(): Vector3?
	return if self.root then self.root.Position else nil
end

-- Brings a dormant entity into the story.
function Entity:activate()
	if self.status == "dormant" then
		self:spawn()
	end
end

function Entity:spawn()
	local marker = Map.marker(self.id .. "_Spawn")
	self.data = {}
	self.waypoints = nil
	local model, root, humanoid = self.behaviour.build(self)
	model:SetAttribute("EntityId", self.id)
	model:PivotTo(marker.CFrame)
	-- Stand it on the floor whatever its size (your model may be taller
	-- or shorter than the greybox).
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	params.FilterDescendantsInstances = { model }
	local floor = workspace:Raycast(marker.Position + Vector3.new(0, 2, 0), Vector3.new(0, -30, 0), params)
	if floor then
		local box, size = model:GetBoundingBox()
		local bottom = box.Position.Y - size.Y / 2
		model:PivotTo(model:GetPivot() + Vector3.new(0, floor.Position.Y + 0.05 - bottom, 0))
	end
	model.Parent = folder()
	root:SetNetworkOwner(nil)
	self.model, self.root, self.humanoid = model, root, humanoid
	self.anim = Models.animations(model, self.id)
	self.animOverride = nil

	-- Your gun's damage is the confirmed hit (see Shots). Health is topped
	-- straight back up: Ashgrove's monsters die by their rules, not by HP.
	local lastHealth = humanoid.Health
	humanoid.HealthChanged:Connect(function(health)
		if health < lastHealth - 0.01 and self.humanoid == humanoid then
			humanoid.Health = humanoid.MaxHealth
			lastHealth = humanoid.MaxHealth
			Shots.onDamaged(self)
		else
			lastHealth = health
		end
	end)
	self.status = "active"
	self.state = ""
	self:setState("Idle")
	if self.behaviour.onSpawn then
		self.behaviour.onSpawn(self)
	end
	Registry.formed:Fire(self)
end

local function fadeOut(model: Model, seconds: number)
	for _, p in model:GetDescendants() do
		if p:IsA("BasePart") then
			p.CanCollide = false
			p.CanQuery = false
			TweenService:Create(p, TweenInfo.new(seconds), { Transparency = 1 }):Play()
		end
	end
	task.delay(seconds, function()
		model:Destroy()
	end)
end

-- Killed: back into its object for a while.
function Entity:banish(killer: Player?)
	if self.status ~= "active" or not self.root or not self.model then
		return
	end
	local position = self.root.Position
	local model = self.model :: Model
	model:SetAttribute("EntityId", nil)
	self.status = "banished"
	self.model, self.root, self.humanoid = nil, nil, nil
	self.waypoints = nil
	local e = Config.entities
	self.reformAt = os.clock() + e.reformMin + math.random() * (e.reformMax - e.reformMin)
	if self.behaviour.onBanish then
		self.behaviour.onBanish(self, model, killer)
	else
		fadeOut(model, 1)
	end
	Registry.died:Fire(self, position, killer)
end

-- Its object is in a warded crate: gone for the rest of the story.
function Entity:secure()
	if self.model then
		local model = self.model :: Model
		model:SetAttribute("EntityId", nil)
		fadeOut(model, 1.5)
	end
	self.model, self.root, self.humanoid = nil, nil, nil
	self.status = "secured"
end

-- Checkpoint reset: back to its spawn, unaware.
function Entity:reset()
	if self.status == "active" then
		if self.model then
			self.model:Destroy()
		end
		self.model, self.root, self.humanoid = nil, nil, nil
		self:spawn()
	end
end

-- Despawn without killing (story end).
function Entity:retire()
	if self.model then
		fadeOut(self.model :: Model, 1.5)
	end
	self.model, self.root, self.humanoid = nil, nil, nil
	self.status = "secured"
end

------------------------------------------------------------------ senses

function Entity:ignoreList(): { Instance }
	local list: { Instance } = { Map.interact("Glows") }
	if self.model then
		table.insert(list, self.model)
	end
	for _, player in Players:GetPlayers() do
		if player.Character then
			table.insert(list, player.Character)
		end
	end
	return list
end

-- Can a point see this player's head, with nothing in between?
function Entity:canSee(from: Vector3, player: Player, maxRange: number): boolean
	local head = Crew.head(player)
	local character = player.Character
	if not head or not character then
		return false
	end
	local offset = head.Position - from
	if offset.Magnitude > maxRange then
		return false
	end
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	local ignore: { Instance } = { Map.interact("Glows") }
	if self.model then
		table.insert(ignore, self.model)
	end
	params.FilterDescendantsInstances = ignore
	local hit = workspace:Raycast(from, offset, params)
	return hit == nil or hit.Instance:IsDescendantOf(character)
end

-- Players it may go after: targetable and inside its wing.
function Entity:targets(): { Player }
	local out = {}
	for _, player in Crew.playersInWing(self.wing) do
		if Crew.isTargetable(player) then
			table.insert(out, player)
		end
	end
	return out
end

function Entity:distanceTo(player: Player): number
	local root = Crew.root(player)
	if not root or not self.root then
		return math.huge
	end
	return (root.Position - self.root.Position).Magnitude
end

function Entity:nearestTarget(): Player?
	local best, bestDistance = nil, math.huge
	for _, player in self:targets() do
		local d = self:distanceTo(player)
		if d < bestDistance then
			best, bestDistance = player, d
		end
	end
	return best
end

function Entity:canTarget(player: Player?): boolean
	if not player or not Crew.isTargetable(player) then
		return false
	end
	local root = Crew.root(player)
	return root ~= nil and Map.wingAt(root.Position) == self.wing
end

------------------------------------------------------------------ movement

local function clearTo(self, goal: Vector3): boolean
	local from = self.root.Position
	local to = Vector3.new(goal.X, from.Y, goal.Z)
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	params.FilterDescendantsInstances = self:ignoreList()
	return workspace:Raycast(from, to - from, params) == nil
end

function Entity:moveTo(goal: Vector3, speed: number)
	local humanoid, root = self.humanoid, self.root
	if not humanoid or not root then
		return
	end
	humanoid.WalkSpeed = speed
	if Map.wingAt(goal) ~= self.wing then
		self:stop()
		return
	end
	if clearTo(self, goal) then
		self.waypoints = nil
		humanoid:MoveTo(goal)
		return
	end
	local now = os.clock()
	if not self.pathBusy and (self.waypoints == nil or now - self.pathAt > 1 or (self.pathGoal - goal).Magnitude > 4) then
		self.pathBusy = true
		self.pathAt = now
		self.pathGoal = goal
		local from = root.Position
		task.spawn(function()
			local path = PathfindingService:CreatePath({
				AgentRadius = self.cfg.agentRadius or 2,
				AgentHeight = self.cfg.agentHeight or 6,
				AgentCanJump = false,
			})
			local ok = pcall(function()
				path:ComputeAsync(from, goal)
			end)
			if ok and path.Status == Enum.PathStatus.Success then
				self.waypoints = path:GetWaypoints()
				self.waypointIndex = 2
			else
				self.waypoints = nil
			end
			self.pathBusy = false
		end)
	end
	local waypoints = self.waypoints
	if waypoints and waypoints[self.waypointIndex] then
		local wp = waypoints[self.waypointIndex].Position
		local flat = Vector3.new(wp.X - root.Position.X, 0, wp.Z - root.Position.Z)
		if flat.Magnitude < 2.5 and self.waypointIndex < #waypoints then
			self.waypointIndex += 1
			wp = waypoints[self.waypointIndex].Position
		end
		humanoid:MoveTo(wp)
	end
end

function Entity:stop()
	if self.humanoid and self.root then
		self.humanoid.WalkSpeed = 0
		self.humanoid:MoveTo(self.root.Position)
	end
end

-- Turn the body to face a point (only while stopped).
function Entity:face(point: Vector3)
	local root = self.root
	if root then
		local flat = Vector3.new(point.X, root.Position.Y, point.Z)
		if (flat - root.Position).Magnitude > 0.1 then
			root.CFrame = CFrame.lookAt(root.Position, flat)
		end
	end
end

-- A one-off animation (Config.models[id].animations), e.g. "attack".
function Entity:action(name: string)
	if self.anim then
		self.anim.action(name)
	end
end

function Entity:shot(part: BasePart, shooter: Player, position: Vector3)
	if self.status == "active" then
		self.behaviour.onShot(self, part, shooter, position)
	end
end

function Entity:agitate(position: Vector3)
	if self.status == "active" and self.behaviour.onAgitate then
		self.behaviour.onAgitate(self, position)
	end
end

------------------------------------------------------------------ loop

local function playerNear(position: Vector3, radius: number): boolean
	for _, player in Players:GetPlayers() do
		local root = Crew.root(player)
		if root and (root.Position - position).Magnitude < radius then
			return true
		end
	end
	return false
end

function Entity.startLoop()
	Noise.emitted:Connect(function(noise: Noise.Noise)
		for _, e in Registry.all() do
			if e.status == "active" and e.root and e.behaviour.onNoise then
				local hearing = noise.radius * (e.cfg.hearingMultiplier or 1)
				local sameWing = Map.wingAt(noise.position) == e.wing
				if (sameWing or noise.kind == "gunshot") and (noise.position - e.root.Position).Magnitude <= hearing then
					e.behaviour.onNoise(e, noise, sameWing)
				end
			end
		end
	end)

	task.spawn(function()
		local last = os.clock()
		while true do
			task.wait(Config.entities.stepInterval)
			local now = os.clock()
			local dt = now - last
			last = now
			for _, e in Registry.all() do
				if e.status == "active" then
					if not e.model or not e.model.Parent or not e.root then
						-- Lost its body (destroyed by something else): re-form later.
						e.status = "banished"
						e.model, e.root, e.humanoid = nil, nil, nil
						e.reformAt = now + Config.entities.reformMin
					else
						if Map.wingAt(e.root.Position) ~= e.wing then
							-- Strayed out of its wing: walk home.
							e.humanoid:MoveTo(Map.marker(e.id .. "_Spawn").Position)
						end
						local ok, err = pcall(e.behaviour.step, e, dt)
						if not ok then
							warn(`[Ashgrove] {e.id} step failed: {err}`)
						end
						if e.anim and e.root then
							local v = e.root.AssemblyLinearVelocity
							local speed = Vector3.new(v.X, 0, v.Z).Magnitude
							e.anim.loop(e.animOverride or (if speed > 10 then "run" elseif speed > 0.5 then "walk" else "idle"))
						end
					end
				elseif e.status == "banished" and now >= e.reformAt then
					local spawnAt = Map.marker(e.id .. "_Spawn").Position
					if playerNear(spawnAt, Config.entities.reformClearRadius) then
						e.reformAt = now + 10
					else
						e:spawn()
					end
				end
			end
		end
	end)
end

return Entity
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Entities", "Lampshy"}, class = "ModuleScript", source = [=[
--[[
	The Lamp-shy (servants' wing). Killable. Lot 203, the hollow lantern.

	PLACEHOLDER for open decision #1 in docs/ASHGROVE_DIRECTION.md: Story 1
	needs a second, cheaper killable entity with a different approach from
	the Dullahan. Swap the rig and the name when the team picks one; keep
	a one-sentence rule.

	RULE: it only moves while it's out of the light.

	- Hunts by sound: walking carries a short way, sprinting a long way,
	  crouching not at all.
	- In any light (a torch beam, a lamp, a glow, a lightning flash) it
	  freezes completely. Reloading turns your torch off, so a lone player
	  can't light it and reload at the same time. Two players can.
	- Kill: one shot while it's lit. In the dark the shot finds nothing.
	- Death: it collapses into a pale glowing shape, a light source that
	  lasts a few minutes.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))

local Ashgrove = script.Parent.Parent
local Crew = require(Ashgrove.Crew)
local Light = require(Ashgrove.Light)
local Map = require(Ashgrove.Map)
local Say = require(Ashgrove.Say)
local Rigs = require(script.Parent.Rigs)

local cfg = Config.entities.Lampshy

local Lampshy = {}

local function isLit(e): boolean
	return Light.isLit(e.root.Position + Vector3.new(0, 0.5, 0), { e.model })
end

local function hunt(e, player: Player)
	e.data.target = player
	e.data.lastHeard = os.clock()
	if e.state ~= "Hunt" then
		Audio.play("lampshyChitter", e.root, 0.8)
		e:setState("Hunt")
	end
end

-- The route marker furthest from a point, that isn't lit.
local function darkestRetreat(e, from: Vector3): Vector3
	local best, bestDistance = e.root.Position, -1
	for _, m in e.data.route do
		local d = (m.Position - from).Magnitude
		if d > bestDistance and not Light.isLit(m.Position, { e.model }) then
			best, bestDistance = m.Position, d
		end
	end
	return best
end

function Lampshy.build(e)
	local model, root, humanoid = Rigs.lampshy()
	e.data.route = Map.markers("Lampshy_Route_")
	e.data.nextTrace = os.clock() + 10
	e.data.nextWanderRoll = os.clock() + 10
	return model, root, humanoid
end

function Lampshy.onSpawn(e)
	e:setState("Feed")
end

function Lampshy.step(e, _dt: number)
	local d = e.data
	local now = os.clock()
	local root: BasePart = e.root

	-- A light on it tells it exactly where the light came from.
	local beamPlayer = Light.beamOn(root.Position + Vector3.new(0, 0.5, 0), nil, { e.model })
	if beamPlayer and e:canTarget(beamPlayer) and e.state ~= "Hunt" then
		hunt(e, beamPlayer)
	end

	if isLit(e) then
		if not d.frozen then
			d.frozen = true
			if e.state == "Hunt" or e.state == "Retreat" then
				Say.near(root.Position, 40, "[It stops dead in the light]", 2, "sound")
			end
		end
		e:stop()
		return
	end
	d.frozen = false

	-- Anyone close enough to touch, it knows about.
	for _, player in e:targets() do
		if e:distanceTo(player) <= cfg.touchRange then
			hunt(e, player)
			break
		end
	end

	local state = e.state
	if state == "Feed" or state == "Idle" then
		e:stop()
		if now >= d.nextTrace then
			d.nextTrace = now + 18 + math.random() * 14
			Audio.play("lampshyChitter", root, 0.4)
			Say.near(root.Position, 35, "[Wet chewing, somewhere in the dark]", 3, "sound")
		end
		if now >= d.nextWanderRoll then
			d.nextWanderRoll = now + 10
			if math.random() < cfg.idleWanderChance and #d.route > 0 then
				d.wanderTo = d.route[math.random(1, #d.route)].Position
				e:setState("Wander")
			end
		end
	elseif state == "Wander" then
		local goal: Vector3 = d.wanderTo or root.Position
		if (Vector3.new(goal.X - root.Position.X, 0, goal.Z - root.Position.Z)).Magnitude < 3 or e:inState() > 25 then
			e:setState("Feed")
		else
			e:moveTo(goal, cfg.wanderSpeed)
		end
	elseif state == "Hunt" then
		local target: Player? = d.target
		if not e:canTarget(target) or now - (d.lastHeard or 0) > cfg.loseTargetAfter then
			d.target = nil
			d.wanderTo = Map.marker("Lampshy_Spawn").Position
			e:setState("Wander")
			return
		end
		local targetRoot = Crew.root(target :: Player) :: BasePart
		if e:distanceTo(target :: Player) <= cfg.lungeRange then
			e:action("attack")
			Audio.play("lampshyLunge", root, 1)
			Say.near(root.Position, 40, "[It lunges]", 2, "sound")
			Crew.hit(target :: Player, 1)
			d.retreatTo = darkestRetreat(e, targetRoot.Position)
			e:setState("Retreat")
		else
			e:moveTo(targetRoot.Position, cfg.speed)
		end
	elseif state == "Retreat" then
		e:moveTo(d.retreatTo or root.Position, cfg.speed)
		if e:inState() >= cfg.retreatTime then
			if e:canTarget(d.target) then
				d.lastHeard = now
				e:setState("Hunt")
			else
				e:setState("Feed")
			end
		end
	end
end

function Lampshy.onShot(e, _part: BasePart, shooter: Player, _position: Vector3)
	if isLit(e) then
		e:banish(shooter)
	else
		Say.to(shooter, "Nothing. It isn't there in the dark. Get a light on it.", 3, "hint")
		if e:canTarget(shooter) then
			hunt(e, shooter)
		end
	end
end

function Lampshy.onNoise(e, noise, sameWing: boolean)
	if not sameWing then
		return
	end
	local source: Player? = noise.source
	if source and e:canTarget(source) then
		if e.state == "Hunt" and e.data.target ~= source then
			-- Keeps the nearer quarry.
			local current = e.data.target
			if current and e:canTarget(current) and e:distanceTo(current) < e:distanceTo(source) then
				e.data.lastHeard = os.clock()
				return
			end
		end
		hunt(e, source)
	end
end

function Lampshy.onAgitate(e, _position: Vector3)
	local nearest = e:nearestTarget()
	if nearest then
		hunt(e, nearest)
	end
end

function Lampshy.onBanish(e, model: Model, _killer: Player?)
	local position = model:GetPivot().Position
	for _, p in model:GetDescendants() do
		if p:IsA("BasePart") then
			p.Anchored = true
			p.CanCollide = false
			p.CanQuery = false
			if p.Name ~= "HumanoidRootPart" then
				p.Material = Enum.Material.Neon
				p.Color = Color3.fromRGB(226, 222, 206)
				p.Transparency = 0.3
			end
		end
	end
	local pale = Color3.fromRGB(230, 226, 210)
	Map.addGlow(position, cfg.glowRadius, cfg.glowTime, pale)
	task.delay(cfg.glowTime - 4, function()
		for _, p in model:GetDescendants() do
			if p:IsA("BasePart") then
				TweenService:Create(p, TweenInfo.new(4), { Transparency = 1 }):Play()
			end
		end
		task.delay(4, function()
			model:Destroy()
		end)
	end)
	for _, player in Players:GetPlayers() do
		local r = Crew.root(player)
		if r and (r.Position - position).Magnitude < 80 then
			Say.to(player, "[It folds up on itself and glows, pale, where it fell]", 4, "sound")
		end
	end
end

return Lampshy
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Entities", "Registry"}, class = "ModuleScript", source = [=[
--[[
	Registry: every killable entity in the game, by id, plus the signals
	other systems listen to.

	  died(entity, position, killer)   a manifestation was killed (banished).
	                                   The Banshee treats this as a death.
	  formed(entity)                   it re-formed at its object.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Signal = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Signal"))

local Registry = {}

Registry.died = Signal.new()
Registry.formed = Signal.new()

local entities: { [string]: any } = {}
local order: { any } = {}

function Registry.add(entity: any)
	entities[entity.id] = entity
	table.insert(order, entity)
end

function Registry.get(id: string): any
	return entities[id]
end

function Registry.all(): { any }
	return order
end

-- The entity a part belongs to, if any (for bullets).
function Registry.fromPart(part: Instance): any
	local node: Instance? = part
	while node and node ~= workspace do
		local id = node:GetAttribute("EntityId")
		if id and node:IsA("Model") then
			return entities[id]
		end
		node = node.Parent
	end
	return nil
end

function Registry.activeInWing(wing: string): { any }
	local out = {}
	for _, e in order do
		if e.status == "active" and e.wing == wing then
			table.insert(out, e)
		end
	end
	return out
end

return Registry
]=] },
}

local function child(parent: Instance, name: string): Instance
	local found = parent:FindFirstChild(name)
	assert(found, `[Ashgrove] expected {parent:GetFullName()}.{name} (paste the parts in order, starting from part 1)`)
	return found :: Instance
end

local function serviceAt(names: { string }): Instance
	local node: Instance = game:GetService(names[1])
	for i = 2, #names do
		node = child(node, names[i])
	end
	return node
end

local function install()
	local ChangeHistoryService = game:GetService("ChangeHistoryService")
	local ok, recording = pcall(function()
		return ChangeHistoryService:TryBeginRecording("Install Ashgrove House")
	end)
	if not ok then
		recording = nil
	end

	-- Remove older installs first.
	if REMOVE_OLD then
		for _, r in ROOTS do
			local old = serviceAt(r.service):FindFirstChild(r.name)
			if old then
				old:Destroy()
			end
		end
	end

	for _, f in FILES do
		local parent = serviceAt(f.service)
		for i = 1, #f.path - 1 do
			parent = child(parent, f.path[i])
		end
		local existing = parent:FindFirstChild(f.path[#f.path])
		if existing then
			existing:Destroy()
		end
		local inst = Instance.new(f.class)
		inst.Name = f.path[#f.path]
		if f.source then
			(inst :: any).Source = f.source
		end
		inst.Parent = parent
	end

	if FINISH then
		for _, name in { "Baseplate", "SpawnLocation" } do
			local leftover = workspace:FindFirstChild(name)
			if leftover and leftover:IsA("BasePart") then
				leftover:Destroy()
			end
		end
		if not workspace:FindFirstChild("AshgroveHouse") then
			require(game:GetService("ServerScriptService").Ashgrove.House).build()
		end
	end

	if recording then
		pcall(function()
			ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
		end)
	end
	print(DONE_MESSAGE)
end

if plugin then
	local toolbar = plugin:CreateToolbar("Ashgrove")
	local button = toolbar:CreateButton("Install", "Install or update Ashgrove House in this place", "")
	button.ClickableWhenViewportHidden = true
	button.Click:Connect(install)
else
	install()
end
