--[[
	ASHGROVE HOUSE installer, PART 1 OF 8.
	Generated by ashgrove/tools/build_installer.py. Don't edit by hand.

	Paste the parts into Studio's Command Bar IN ORDER (1, 2, 3 ...),
	pressing Enter after each. Wait for the Output window to say
	"part 1 of 8 done" before pasting the next one.
	Next: part 2.
]]

local REMOVE_OLD = true
local FINISH = false
local DONE_MESSAGE = "[Ashgrove] part 1 of 8 done. Now paste part 2."
local ROOTS = {
	{ service = {"ReplicatedStorage"}, name = "Ashgrove" },
	{ service = {"ServerScriptService"}, name = "Ashgrove" },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, name = "AshgroveClient" },
}

local FILES = {
	{ service = {"ReplicatedStorage"}, path = {"Ashgrove"}, class = "Folder", source = nil },
	{ service = {"ReplicatedStorage"}, path = {"Ashgrove", "Audio"}, class = "ModuleScript", source = [=[
--[[
	Plays a sound from Config.sounds by key. Empty ids are skipped, so
	every call is safe before audio has been picked.

	Parent the sound to a part or attachment for 3D sound, or to
	SoundService for a flat one. On the server, a sound played in the
	workspace is heard by everyone.
]]

local Debris = game:GetService("Debris")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Config = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Config"))

local Audio = {}

function Audio.id(key: string): string
	return (Config.sounds :: any)[key] or ""
end

function Audio.play(key: string, parent: Instance, volume: number?, maxDistance: number?): Sound?
	local id = Audio.id(key)
	if id == "" then
		return nil
	end
	local sound = Instance.new("Sound")
	sound.Name = key
	sound.SoundId = id
	sound.Volume = volume or 0.6
	sound.RollOffMaxDistance = maxDistance or 120
	sound.Parent = parent
	sound:Play()
	Debris:AddItem(sound, 30)
	return sound
end

-- Looping sound that stays until destroyed.
function Audio.loop(key: string, parent: Instance, volume: number?): Sound?
	local id = Audio.id(key)
	if id == "" then
		return nil
	end
	local sound = Instance.new("Sound")
	sound.Name = key
	sound.SoundId = id
	sound.Volume = volume or 0.5
	sound.Looped = true
	sound.Parent = parent
	sound:Play()
	return sound
end

return Audio
]=] },
	{ service = {"ReplicatedStorage"}, path = {"Ashgrove", "Config"}, class = "ModuleScript", source = [=[
--[[
	Every tuning number in the game, in one place.

	Values are the starting values from docs/ASHGROVE_DIRECTION.md. They are
	meant to be tuned in playtests; change them here, not in the systems.

	Sound ids are left empty on purpose: paste Creator Store ids in
	(e.g. "rbxassetid://123"). Empty ids are skipped silently, and every
	sound that carries gameplay information also shows an on-screen
	caption, so the game is fully playable before any audio exists.
]]

local Config = {}

-- Distances are in studs (1 stud = 0.28 m). Times are in seconds.

Config.player = {
	walkSpeed = 12,
	sprintSpeed = 19,
	crouchSpeed = 6,
	downedSpeed = 2,
	jumpPower = 40,

	hitsToDown = 3,
	hitInvulnerability = 1.2, -- after a hit, so one swing can't land twice
	sanctuaryRegenEvery = 20, -- one hit healed per this many seconds, sanctuaries only

	-- How far footsteps carry. Entities hear anything inside the radius.
	noise = {
		walk = 12,
		sprint = 38,
		crouch = 0,
		sampleEvery = 0.5,
	},

	-- Where a player taken by the Banshee is held until they come back.
	takenHoldPosition = Vector3.new(0, -300, 0),
}

-- YOUR GUN. Ashgrove doesn't have a gun of its own: it watches yours.
-- See ServerScriptService.Ashgrove.Shots (how hits are noticed) and
-- .Hooks (the three calls your gun can make for exact results).
Config.integration = {
	-- How a hit on a monster is noticed:
	--   "auto"   watch monster Humanoids for damage from your gun (the
	--            body part is worked out from where the shooter aimed). If
	--            your gun turns out never to damage Humanoids, switch to
	--            "click" by itself after a few shots, with a warning.
	--   "damage" damage only.   "click" every click is a hit along the aim.
	--   "hooks"  only Hooks.reportHit (most exact; wire it into your gun).
	hitDetection = "auto",
	gunshotNoise = 220, -- how far a shot is heard; carries through a wing
	clickRange = 400,
	-- Reloading needs both hands: the torch goes off for this long when the
	-- player presses the reload key with a tool out. 0 to turn it off.
	reloadKey = Enum.KeyCode.R,
	reloadTorchOff = 2.5,
}

-- YOUR MODELS. For each monster, Ashgrove looks for a Model with one of
-- these names (case and spaces ignored) in ServerStorage.AshgroveModels,
-- then ReplicatedStorage.AshgroveModels, then anywhere in Workspace or
-- ServerStorage. Found: it's used. Not found: the greybox body is used.
-- Animation ids are optional ("rbxassetid://..."); empty ones are skipped.
Config.models = {
	Dullahan = {
		names = { "Dullahan", "AH_Ent_Dullahan" },
		-- The part he carries and sees through. Falls back to any part
		-- whose name contains "head".
		headPart = "CarriedHead",
		animations = { idle = "", walk = "", run = "", attack = "", blind = "" },
	},
	Lampshy = {
		names = { "Lampshy", "Lamp-shy", "AH_Ent_Lampshy" },
		animations = { idle = "", walk = "", run = "", attack = "" },
	},
	Banshee = {
		names = { "Banshee", "AH_Ent_Banshee" },
		kneelDrop = 0.8, -- how far she sinks to "kneel" when mourning (greybox: 2.4)
		animations = { idle = "", keen = "", mourn = "" },
	},
}

Config.flashlight = {
	battery = 300, -- seconds of on-time
	maxBattery = 300,
	angle = 45, -- SpotLight cone, visual
	range = 60,
	brightness = 3,
	-- Gameplay cone: what counts as "in your light" for entities.
	beamHalfAngle = 20,
	litRange = 60,
}

Config.ward = {
	raiseTime = 2,
	cooldown = 10,
	range = 45,
}

-- Committed actions: once started you can't cancel them, and a hit
-- interrupts them. The player is rooted and can't shoot meanwhile.
Config.commit = {
	secure = 4,
	secureWhileEntityActive = 7,
	rite = 1.5,
	revive = 4,
}

Config.storm = {
	-- Lightning interval range per storm level. Each secured object raises
	-- the level by one.
	lightning = {
		[0] = { min = 14, max = 30 },
		[1] = { min = 10, max = 24 },
		[2] = { min = 8, max = 18 },
		[3] = { min = 6, max = 14 },
	},
	flashWindow = 0.35, -- how long a flash counts as "lit" for gameplay
	powerCutLevel = 2, -- at this level the hall's work lamp fails
	rainVolume = { [0] = 0.35, [1] = 0.45, [2] = 0.55, [3] = 0.65 },
}

Config.entities = {
	-- A banished entity re-forms at its object after this long, unless the
	-- object has been secured.
	reformMin = 360,
	reformMax = 600,
	reformClearRadius = 30, -- never re-form with a player this close
	stepInterval = 0.1,

	Dullahan = {
		displayName = "the Dullahan",
		wing = "Gallery",
		walkSpeed = 7,
		huntSpeed = 11,
		fieldOfView = 70, -- degrees, centred on where the carried head faces
		sightRange = 90,
		touchRange = 4, -- always notices a player this close
		whipRange = 12, -- the kill window closes here, not at contact
		windupTime = 0.7,
		recoverTime = 1.2,
		blindTime = 3, -- after the head is shot out of his hands
		bodyHitsToKillWhileBlind = 2,
		staggerTime = 0.4,
		repelTime = 4,
		loseTargetAfter = 4,
		searchTime = 6,
		headGlowTime = 120, -- the dropped head keeps glowing after death
		headGlowRadius = 10,
		idlePauseMin = 3,
		idlePauseMax = 6,
	},

	-- PLACEHOLDER: decision #1 in the direction doc is still open. This is
	-- the "freezes in light" minor entity used to make Story 1 playable.
	Lampshy = {
		displayName = "the Lamp-shy",
		wing = "ServantsWing",
		speed = 16,
		wanderSpeed = 8,
		hearingMultiplier = 1,
		touchRange = 8,
		lungeRange = 3.5,
		retreatTime = 3,
		loseTargetAfter = 6,
		glowRadius = 14, -- its body glows after death
		glowTime = 180,
		idleWanderChance = 0.25,
	},
}

Config.banshee = {
	-- Her colour. Reserved: no other asset or effect may use it.
	colour = Color3.fromRGB(150, 174, 158),

	doomWindowMin = 60,
	doomWindowMax = 90,
	minGapBetweenKeens = 240,
	naturalKeenMin = 15 * 60,
	naturalKeenMax = 25 * 60,
	distantMin = 120,
	distantMax = 240,
	mournTime = 45,
	-- Mourning is safe to approach quietly: crouched, you can get this
	-- close; walking or sprinting, she notices you much further out.
	disturbRadius = 15,
	disturbRadiusCrouched = 4,
	aftermathGrace = 10, -- after a death she's come to mourn, she ignores you this long
	disturbLightRange = 35,
	disturbShotRadius = 60,
	leaveLockout = 120, -- a wing you fled a keen from stays shut this long
	takeRevealTime = 2.5,
	agitateEvery = 10,
}

Config.story = {
	firstDistantDelay = 240, -- after the gallery chapter starts
	mournDullahanDeaths = true, -- she grieves the Dullahan's first death
	kitchenMourningDelay = 5,
	firstKeenDelay = 60, -- after the kitchen mourning ends
	ruleBreakDelay = 6, -- after the sealed box is inspected
}

Config.pickups = {
	ammoAmount = 6,
	batteryAmount = 120,
	-- How many candidates in each group are live per run (Always pickups
	-- are extra). Each extra player adds extraPerPlayer, rounded.
	groups = {
		Gallery = 1,
		ServantsWing = 2,
		Vault = 1,
		Batteries = 2,
	},
	extraPerPlayer = 0.5,
}

Config.bellBoard = {
	checkEvery = 2,
	ringChance = 0.35, -- imperfect on purpose
	hearRadius = 45,
}

Config.sounds = {
	rain = "",
	thunder = "",
	gunshot = "",
	reload = "",
	dryFire = "",
	hurt = "",
	keen = "", -- the game's signature sound
	keenDistant = "",
	bansheeTake = "",
	dullahanWhip = "",
	dullahanBreath = "",
	headDrop = "",
	lampshyChitter = "",
	lampshyLunge = "",
	bell = "",
	riteStep = "",
	secure = "",
	pickup = "",
	heartbeat = "",
}

Config.debug = {
	-- Studio only: F6 next chapter, F7 force a keen where you stand,
	-- F8 refill ammo and battery.
	studioKeys = true,
}

return Config
]=] },
	{ service = {"ReplicatedStorage"}, path = {"Ashgrove", "Net"}, class = "ModuleScript", source = [=[
--[[
	Every remote the game uses, created by the server on first require and
	looked up by the client. Names are listed here so both sides agree.

	Client -> server
	  Shot(origin, direction)   Reload()   Flashlight(on)   Move(mode)
	  Aim(direction)*           Ward()     Debug(command)
	Server -> client
	  Caption(text, seconds, style)
	  Note(noteId)   Objectives(list)   Chapter(title, subtitle)
	  Keen(state, info)   Lightning(strength)   Screen(kind, text)
	  Spectate(on)

	* unreliable: sent ten times a second, a lost packet doesn't matter.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")

local RELIABLE = {
	"Shot",
	"Reload",
	"Flashlight",
	"Move",
	"Ward",
	"Debug",
	"Caption",
	"Note",
	"Objectives",
	"Chapter",
	"Keen",
	"Lightning",
	"Screen",
	"Spectate",
}
local UNRELIABLE = { "Aim" }

local FOLDER_NAME = "AshgroveNet"

local Net = {}

local folder: Folder
if RunService:IsServer() then
	local existing = ReplicatedStorage:FindFirstChild(FOLDER_NAME)
	if existing then
		existing:Destroy()
	end
	folder = Instance.new("Folder")
	folder.Name = FOLDER_NAME
	for _, name in RELIABLE do
		local remote = Instance.new("RemoteEvent")
		remote.Name = name
		remote.Parent = folder
	end
	for _, name in UNRELIABLE do
		local remote = Instance.new("UnreliableRemoteEvent")
		remote.Name = name
		remote.Parent = folder
	end
	folder.Parent = ReplicatedStorage
else
	folder = ReplicatedStorage:WaitForChild(FOLDER_NAME) :: Folder
end

function Net.event(name: string): RemoteEvent
	return folder:WaitForChild(name) :: RemoteEvent
end

function Net.unreliable(name: string): UnreliableRemoteEvent
	return folder:WaitForChild(name) :: UnreliableRemoteEvent
end

return Net
]=] },
	{ service = {"ReplicatedStorage"}, path = {"Ashgrove", "Notes"}, class = "ModuleScript", source = [=[
--[[
	Every readable text in Story 1. A note part in the map carries a NoteId
	attribute that matches a key here.

	Three layers, per the direction doc:
	  Cornelius   catalogue cards: WHAT each object is and how it behaves
	  First crew  voice memos: WHAT WENT WRONG (rules taught by mistakes)
	  The dead    memos only readable while the Banshee mourns there

	The full arc these seed is in docs/ASHGROVE_STORY.md.

	The auction house and every name here are invented. Keep it that way:
	no real people, brands or places' logos.
]]

export type Note = {
	title: string,
	body: string,
}

local Notes: { [string]: Note } = {
	Manifest = {
		title = "Retrieval manifest, crew 2",
		body = [[PELLAM & SLOANE, AUCTIONEERS
Estate of C. Ashgrove. Retrieval, second attempt.

Crew 1 (Okafor, Pruitt, Wren) lost contact on night one. Find them. Then finish the job.

LOT 114  Spine whip, in tack case. Portrait gallery.
LOT 203  Hollow lantern. Servants' wing, scullery.
LOT 077  Silver comb. Servants' wing. CASE FOUND EMPTY. Do not search for it.
LOT 001  Wine cabinet ("the sealed box"). Cellar vault. SEALED. Do not open.

Secure each lot in a warded crate where you find it. Crates are on site.
Read Mr Ashgrove's catalogue cards before you touch anything.]],
	},

	Card_Dullahan = {
		title = "Catalogue card: Lot 114",
		body = [[THE RIDER'S WHIP. West of Ireland. Bought 1991.

The whip is a spine. He came with it.

He carries his own head and sees only what the head is facing. Stand where it is not looking and he will walk past you.

He kills from the length of the whip, not from arm's reach.

Gold. Any gold. Hold it up where the head can see it and he will not come near. It will not stop him for long.

- C.A.]],
	},

	Card_Lampshy = {
		title = "Catalogue card: Lot 203",
		body = [[THE HOLLOW LANTERN. From a mining family's estate. Bought 1987.

The thing that came with it lives in the dark and feeds there. It will not move while a light is on it. Not an inch.

It moves the moment the light leaves it.

Never trim the wick and look away at the same time.

- C.A.]],
	},

	Card_Banshee = {
		title = "Catalogue card: Lot 077",
		body = [[THE COMB. Silver, Irish. Eighteenth century.

Listed for completeness. The comb is not in its case and I no longer look for it.

She came with it, or it came with her.

She does not hunt. She keens before a death and grieves after one. If she keens near you, something must die, or you must leave.

The servants kept the old customs. The housekeeper's book has them.

- C.A.]],
	},

	Card_Gold = {
		title = "Catalogue card: pocket piece",
		body = [[GOLD SOVEREIGN. Not for sale. My own.

I carry it into the gallery. Raise it where the head can see it.

- C.A.]],
	},

	Memo_Hall = {
		title = "Voice memo: Okafor (crew 1)",
		body = [["Night one. Generator's running, so we've got the lamp in the hall. Nothing's coming in here. Hall's fine.

Case 114 in the gallery is empty. The whip's at the far end on the floor. Pruitt says something's walking down there.

Nobody goes in without a light. Nobody goes in alone."]],
	},

	Memo_Gallery = {
		title = "Voice memo: Pruitt (crew 1)",
		body = [["It doesn't look at you. The head does. It carries the head, and the head's what sees.

If the head's turned away you can walk right past it.

I put two in its chest and it didn't care. It cared when I hit the head. It dropped it. It went feeling around on the floor like a man who's lost his glasses.

Then it found it again."]],
	},

	Memo_Kitchen = {
		title = "Voice memo: Wren (crew 1), whispering",
		body = [["She's in the kitchen with Okafor. She isn't doing anything. She's just... crying over him.

The lantern thing came out of the scullery when Okafor's torch died. I got my light on it and it stopped dead. Didn't even twitch. Then Okafor went to reload and it was on him.

She was wailing before it happened. Before. Like she knew.

I'm going for the van."]],
	},

	Customs = {
		title = "The housekeeper's book",
		body = [[When the keening is heard in the house:

Stop the clock, so the hour is kept.
Cover the glass, so no soul is caught in it.
Open the window, so it may go.

Do all three before she is done, and she will take no one from that room.

Each room keeps the custom once. After that it is only a room.]],
	},

	Bells = {
		title = "Note pinned under the bell board",
		body = [[Each bell rings for its room.

Mr Ashgrove says the bells ring by themselves now. We have stopped answering them. We still look at which one rings.

- Mrs Dunne, housekeeper]],
	},

	Grave_Receipt = {
		title = "Sexton's chit, nailed to the spade",
		body = [[Plot 11. Dig to the usual depth and leave it open.

Paid in full, in gold, in advance.

Do not fill it until she stops.

- C. Ashgrove]],
	},

	Vault_Ledger = {
		title = "Cornelius Ashgrove's ledger, last entry",
		body = [[The box is the only thing I have bought that I would sell back.

What is in it was somebody once. It wants to be somebody again. It does not want a room, or a house. It wants a person.

If the seal is broken, it is already wearing someone.

- C.A.]],
	},
}

return Notes
]=] },
	{ service = {"ReplicatedStorage"}, path = {"Ashgrove", "Signal"}, class = "ModuleScript", source = [=[
--[[
	Minimal signal used between server systems so they don't have to
	require each other in a circle. Handlers run in their own thread.
]]

export type Connection = { Disconnect: () -> () }

local Signal = {}
Signal.__index = Signal

function Signal.new()
	return setmetatable({ handlers = {} :: { (...any) -> () } }, Signal)
end

function Signal:Connect(fn: (...any) -> ()): Connection
	table.insert(self.handlers, fn)
	return {
		Disconnect = function()
			local i = table.find(self.handlers, fn)
			if i then
				table.remove(self.handlers, i)
			end
		end,
	}
end

function Signal:Fire(...: any)
	for _, fn in table.clone(self.handlers) do
		task.spawn(fn, ...)
	end
end

return Signal
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove"}, class = "Script", source = [=[
--[[
	Ashgrove House (server entry). Builds the greybox if the place has no
	"AshgroveHouse" model yet, sets up first-person play, and starts Story 1.

	Everything this script needs is its children. See ashgrove/README.md
	for where each piece goes in Studio.
]]

local Players = game:GetService("Players")
local StarterPlayer = game:GetService("StarterPlayer")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Config = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Config"))

StarterPlayer.CameraMode = Enum.CameraMode.LockFirstPerson
StarterPlayer.CameraMaxZoomDistance = 0.5
StarterPlayer.EnableMouseLockOption = false
StarterPlayer.CharacterWalkSpeed = Config.player.walkSpeed
StarterPlayer.CharacterUseJumpPower = true
StarterPlayer.CharacterJumpPower = Config.player.jumpPower
Players.RespawnTime = 3

-- The Baseplate template's floor (y -16..0) would fill the cellar vault,
-- and its spawn would drop players into the courtyard.
for _, name in { "Baseplate", "SpawnLocation" } do
	local leftover = workspace:FindFirstChild(name)
	if leftover and leftover:IsA("BasePart") then
		leftover:Destroy()
	end
end

if not workspace:FindFirstChild("AshgroveHouse") then
	require(script.House).build()
end

require(script.Director).start()
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Banshee"}, class = "ModuleScript", source = [=[
--[[
	The Banshee. Unkillable, and never a chaser.

	CORE RULE: when she keens, someone nearby will die soon. If nothing
	else dies, one of you will.

	States
	  Hidden    not in the world. Distant keening may be heard.
	  Mourning  kneeling at a site of death. Safe, unless disturbed: getting
	            within Config.banshee.disturbRadius, a torch on her face, or
	            a gunshot nearby turns her grief into a keen.
	  Keening   the storm goes silent and a doom window opens. Resolved by:
	              fulfil  an entity dies in the wing
	              leave   every player gets out of the wing (the wing is
	                      then shut for a while: Doors.lockout)
	              rite    the wing's wake custom is kept (Rites)
	            Otherwise, when the window closes:
	  Taking    she is in front of the one she faced, and takes them.

	Guarantees (direction doc, section 9): she never chases or patrols;
	she's always heard before she's seen; no more than one keen per wing
	visit, none in sanctuaries, none within minGapBetweenKeens of the last.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")
local TweenService = game:GetService("TweenService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))
local Net = require(Shared:WaitForChild("Net"))
local Signal = require(Shared:WaitForChild("Signal"))

local Crew = require(script.Parent.Crew)
local Doors = require(script.Parent.Doors)
local Light = require(script.Parent.Light)
local Map = require(script.Parent.Map)
local Models = require(script.Parent.Models)
local Noise = require(script.Parent.Noise)
local Reading = require(script.Parent.Reading)
local Registry = require(script.Parent.Entities.Registry)
local Rigs = require(script.Parent.Entities.Rigs)
local Rites = require(script.Parent.Rites)
local Say = require(script.Parent.Say)
local Storm = require(script.Parent.Storm)

local cfg = Config.banshee

local KEEN_WINGS = { "Gallery", "ServantsWing", "Vault" }

local Banshee = {}

Banshee.keenStarted = Signal.new() -- (wing, target)
Banshee.keenEnded = Signal.new() -- (wing, outcome, victim?)
Banshee.mourningEnded = Signal.new() -- (key?, disturbed)

type Keen = {
	wing: string,
	target: Player,
	startedAt: number,
	endsAt: number,
	forced: boolean,
	lastAgitate: number,
}

type Mourning = {
	position: Vector3,
	wing: string,
	endsAt: number,
	graceUntil: number,
	key: string?,
}

local model: Model
local facePart: BasePart
local chestPart: BasePart
local anims: Models.Animations
local kneelDrop = 2.4
local state = "Hidden"
local keen: Keen? = nil
local mourning: Mourning? = nil
local keenSound: Sound? = nil

local distantEnabled = false
local nextDistantAt = math.huge
local naturalEnabled = false
local nextNaturalAt = math.huge
local lastKeenEnd = -math.huge
local taughtKeen = false
local taughtMourning = false

local visits: { [string]: { occupied: boolean, keened: boolean } } = {}
local mournedWings: { [string]: boolean } = {}

for _, wing in KEEN_WINGS do
	visits[wing] = { occupied = false, keened = false }
end

------------------------------------------------------------------ presence

local function eachPart(fn: (BasePart) -> ())
	for _, p in model:GetDescendants() do
		if p:IsA("BasePart") and p.Name ~= "Root" then
			fn(p)
		end
	end
end

local function show(cf: CFrame, pose: string)
	local placed = if pose == "kneel" then cf * CFrame.new(0, -kneelDrop, 0) * CFrame.Angles(math.rad(-14), 0, 0) else cf
	anims.loop(if pose == "kneel" then "mourn" elseif state == "Keening" or state == "Ending" then "keen" else "idle")
	model:PivotTo(placed)
	eachPart(function(p)
		p.Transparency = 1
	end)
	model.Parent = Map.root()
	eachPart(function(p)
		TweenService:Create(p, TweenInfo.new(1.2), { Transparency = p:GetAttribute("BaseTransparency") or 0 }):Play()
	end)
end

local function hide(seconds: number?)
	local t = seconds or 1
	eachPart(function(p)
		TweenService:Create(p, TweenInfo.new(t), { Transparency = 1 }):Play()
	end)
	local token = model:GetAttribute("HideToken") or 0
	model:SetAttribute("HideToken", token + 1)
	task.delay(t, function()
		if model:GetAttribute("HideToken") == token + 1 and state == "Hidden" then
			model.Parent = ServerStorage
		end
	end)
end

local function floorBelow(position: Vector3): Vector3
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	local ignore: { Instance } = { model, Map.interact("Glows") }
	for _, player in Players:GetPlayers() do
		if player.Character then
			table.insert(ignore, player.Character)
		end
	end
	local entities = Map.root():FindFirstChild("Entities")
	if entities then
		table.insert(ignore, entities)
	end
	params.FilterDescendantsInstances = ignore
	local hit = workspace:Raycast(position + Vector3.new(0, 3, 0), Vector3.new(0, -24, 0), params)
	return if hit then hit.Position else position
end

local function faceTowards(at: Vector3, towards: Vector3): CFrame
	local flatTarget = Vector3.new(towards.X, at.Y, towards.Z)
	if (flatTarget - at).Magnitude < 0.1 then
		return CFrame.new(at)
	end
	return CFrame.lookAt(at, flatTarget)
end

-- Where she stands to keen at a target: a marker in the wing at a
-- readable distance, preferring one with a clear line to them.
local function keenSpot(wing: string, target: Player): CFrame
	local markers = Map.markers("BansheeKeen_" .. wing .. "_")
	local root = Crew.root(target)
	if #markers == 0 or not root then
		local at = if root then root.Position + root.CFrame.LookVector * 20 else Vector3.zero
		return faceTowards(floorBelow(at), if root then root.Position else at)
	end
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	params.FilterDescendantsInstances = { model, Map.interact("Glows") }
	local best, bestScore = markers[1], -math.huge
	for _, m in markers do
		local offset = root.Position - m.Position
		local distance = offset.Magnitude
		local score = -math.abs(distance - 28)
		local hit = workspace:Raycast(m.Position + Vector3.new(0, 8, 0), root.Position - (m.Position + Vector3.new(0, 8, 0)), params)
		local character = target.Character
		if hit == nil or (character and hit.Instance:IsDescendantOf(character)) then
			score += 40
		end
		if score > bestScore then
			best, bestScore = m, score
		end
	end
	return faceTowards(best.Position, root.Position)
end

------------------------------------------------------------------ rules

function Banshee.canKeen(wing: string, forced: boolean?): boolean
	if state == "Keening" or state == "Taking" or state == "Ending" then
		return false
	end
	if forced then
		return true
	end
	if not visits[wing] then
		return false -- the hall, the van and the grounds are never keened
	end
	if os.clock() - lastKeenEnd < cfg.minGapBetweenKeens then
		return false
	end
	if visits[wing].keened then
		return false
	end
	return #Crew.playersInWing(wing) > 0
end

local function scheduleNatural()
	nextNaturalAt = os.clock() + cfg.naturalKeenMin + math.random() * (cfg.naturalKeenMax - cfg.naturalKeenMin)
end

local function stopKeenSound()
	if keenSound then
		local s = keenSound
		keenSound = nil
		TweenService:Create(s, TweenInfo.new(1.5), { Volume = 0 }):Play()
		task.delay(1.6, function()
			s:Destroy()
		end)
	end
end

local function endMourning(disturbed: boolean)
	local m = mourning
	mourning = nil
	if state == "Mourning" then
		state = "Hidden"
		if not disturbed then
			hide(2)
		end
	end
	if m then
		Banshee.mourningEnded:Fire(m.key, disturbed)
	end
end

local function resolve(outcome: string, victim: Player?)
	local k = keen
	if not k then
		return
	end
	keen = nil
	state = "Hidden"
	Rites.setActive(k.wing, false)
	Storm.silence(false)
	stopKeenSound()
	lastKeenEnd = os.clock()
	Net.event("Keen"):FireAllClients("end", { outcome = outcome })
	if outcome == "fulfilled" then
		Say.all("[The keening stops.] Something died. She turns away.", 5, "story")
	elseif outcome == "left" then
		Say.all("[The keening fades behind you.] You got out. That wing won't let you back in for a while.", 6, "story")
		Doors.lockout(k.wing)
	elseif outcome == "rite" then
		Say.all("[The keening breaks off.] The custom is kept. She takes no one from that room.", 6, "story")
	end
	hide(1.5)
	if naturalEnabled then
		scheduleNatural()
	end
	Banshee.keenEnded:Fire(k.wing, outcome, victim)
end

local function take()
	local k = keen
	if not k then
		return
	end
	-- The one she faced, if still in the wing; otherwise whoever's closest.
	local victim: Player? = nil
	local inWing = Crew.playersInWing(k.wing, true)
	if table.find(inWing, k.target) then
		victim = k.target
	else
		local herPos = model:GetPivot().Position
		local best = math.huge
		for _, player in inWing do
			local root = Crew.root(player)
			local d = if root then (root.Position - herPos).Magnitude else math.huge
			if d < best then
				victim, best = player, d
			end
		end
	end
	if not victim then
		resolve("left")
		return
	end
	state = "Taking"
	local root = Crew.root(victim)
	if root then
		local at = floorBelow(root.Position + root.CFrame.LookVector * 4)
		model:PivotTo(faceTowards(at, root.Position))
	end
	Say.to(victim, "[She is right in front of you]", cfg.takeRevealTime, "sound")
	task.wait(cfg.takeRevealTime)
	if keen ~= k then
		return
	end
	Audio.play("bansheeTake", chestPart, 1, 300)
	Crew.take(victim)
	Say.all("[A scream, and then nothing]", 4, "sound")
	resolve("taken", victim)
end

-- Starts a keen in a wing. opts.target picks who she faces; opts.forced
-- skips the frequency rules (story beats); opts.at keeps her where she is.
function Banshee.keen(wing: string, opts: { target: Player?, forced: boolean?, at: CFrame?, duration: number? }?): boolean
	local o = opts or {}
	if not Banshee.canKeen(wing, o.forced) then
		return false
	end
	local target = o.target
	if not target or not table.find(Crew.playersInWing(wing, true), target) then
		local candidates = Crew.playersInWing(wing)
		if #candidates == 0 then
			candidates = Crew.playersInWing(wing, true)
		end
		if #candidates == 0 then
			return false
		end
		target = candidates[math.random(1, #candidates)]
	end
	local victimTarget = target :: Player
	if mourning then
		endMourning(true)
	end
	local now = os.clock()
	local duration = o.duration or (cfg.doomWindowMin + math.random() * (cfg.doomWindowMax - cfg.doomWindowMin))
	keen = {
		wing = wing,
		target = victimTarget,
		startedAt = now,
		endsAt = now + duration,
		forced = o.forced == true,
		lastAgitate = now,
	}
	state = "Keening"
	if visits[wing] then
		visits[wing].keened = true
	end

	show(o.at or keenSpot(wing, victimTarget), "stand")
	Storm.silence(true)
	stopKeenSound()
	keenSound = Audio.loop("keen", chestPart, 1)
	if keenSound then
		keenSound.RollOffMaxDistance = 400
	end
	Say.all("[A keening rises. The storm goes quiet.]", 5, "sound")
	Say.to(victimTarget, "She is facing you.", 6, "story")
	Say.except(victimTarget, `She is facing {victimTarget.DisplayName}.`, 6, "story")
	if not taughtKeen then
		taughtKeen = true
		task.delay(3, function()
			Say.all("Something here has to die, or you have to get out. Or keep the old custom, if the room has one.", 8, "hint")
		end)
	end
	Net.event("Keen"):FireAllClients("start", {
		wing = wing,
		target = victimTarget.UserId,
		targetName = victimTarget.DisplayName,
		endsAt = workspace:GetServerTimeNow() + duration,
		length = duration,
	})
	Rites.setActive(wing, true)
	local root = Crew.root(victimTarget)
	for _, e in Registry.activeInWing(wing) do
		e:agitate(if root then root.Position else e:position())
	end
	Banshee.keenStarted:Fire(wing, victimTarget)
	return true
end

-- Kneels at a site of death. opts.noteId reveals a note there; opts.grace
-- is how long she ignores people already close (an aftermath).
function Banshee.mourn(position: Vector3, opts: { noteId: string?, key: string?, duration: number?, grace: number? }?): boolean
	local o = opts or {}
	if state ~= "Hidden" then
		return false
	end
	local wing = Map.wingAt(position)
	if not wing or not visits[wing] then
		return false
	end
	state = "Mourning"
	mourning = {
		position = position,
		wing = wing,
		endsAt = os.clock() + (o.duration or cfg.mournTime),
		graceUntil = os.clock() + (o.grace or 0),
		key = o.key,
	}
	mournedWings[wing] = true
	local spot = floorBelow(position + Vector3.new(-2.5, 0, 2.5))
	show(faceTowards(spot, position), "kneel")
	if o.noteId then
		Reading.reveal(o.noteId)
	end
	Say.near(position, 140, "[Soft weeping, somewhere close]", 4, "sound")
	if not taughtMourning then
		taughtMourning = true
		task.delay(3, function()
			Say.all("She hasn't noticed you. Crouch to get close, and keep your torch off her face.", 8, "hint")
		end)
	end
	return true
end

local function disturb(player: Player?)
	local m = mourning
	if not m then
		return
	end
	local at = model:GetPivot()
	endMourning(true)
	local root = player and Crew.root(player)
	if player and root and Banshee.canKeen(m.wing) then
		local standing = faceTowards(floorBelow(at.Position + Vector3.new(0, 2.4, 0)), root.Position)
		Say.to(player, "You disturbed her.", 3, "story")
		Banshee.keen(m.wing, { target = player, at = standing })
	else
		Say.near(m.position, 80, "[A shriek, and she's gone]", 3, "sound")
		hide(0.4)
	end
end

function Banshee.distantNow()
	local quiet: { string } = {}
	for _, wing in KEEN_WINGS do
		if #Crew.playersInWing(wing, true) == 0 then
			table.insert(quiet, wing)
		end
	end
	local wing = if #quiet > 0 then quiet[math.random(1, #quiet)] else KEEN_WINGS[math.random(1, #KEEN_WINGS)]
	local markers = Map.markers("BansheeKeen_" .. wing .. "_")
	if #markers > 0 then
		local emitter = Instance.new("Part")
		emitter.Anchored = true
		emitter.CanCollide = false
		emitter.CanQuery = false
		emitter.Transparency = 1
		emitter.Size = Vector3.one
		emitter.Position = markers[math.random(1, #markers)].Position + Vector3.new(0, 8, 0)
		emitter.Parent = Map.interact("Glows")
		Audio.play("keenDistant", emitter, 0.6, 500)
		task.delay(12, function()
			emitter:Destroy()
		end)
	end
	for _, player in Players:GetPlayers() do
		local root = Crew.root(player)
		if not root or Map.wingAt(root.Position) ~= wing then
			Say.to(player, "[Keening, far off in the house]", 4, "sound")
		end
	end
end

function Banshee.enableDistant()
	if not distantEnabled then
		distantEnabled = true
		nextDistantAt = os.clock() + cfg.distantMin + math.random() * (cfg.distantMax - cfg.distantMin)
	end
end

function Banshee.setNatural(on: boolean)
	naturalEnabled = on
	if on then
		scheduleNatural()
	else
		nextNaturalAt = math.huge
	end
end

function Banshee.isKeening(): boolean
	return state == "Keening" or state == "Taking"
end

function Banshee.isMourning(): boolean
	return state == "Mourning"
end

-- Checkpoint wipe: she goes, the storm comes back, nothing carries over.
function Banshee.reset()
	if keen then
		Rites.setActive(keen.wing, false)
		Net.event("Keen"):FireAllClients("end", { outcome = "reset" })
	end
	keen = nil
	mourning = nil
	stopKeenSound()
	Storm.silence(false)
	state = "Hidden"
	hide(0.1)
	lastKeenEnd = os.clock()
	for _, v in visits do
		v.occupied = false
		v.keened = false
	end
	if naturalEnabled then
		scheduleNatural()
	end
end

-- Story 1's last image: she keeps keening after you've crossed into the
-- rain. It wasn't about you.
function Banshee.ending(at: CFrame)
	keen = nil
	mourning = nil
	state = "Ending"
	naturalEnabled = false
	distantEnabled = false
	show(at, "stand")
	Storm.silence(true)
	stopKeenSound()
	keenSound = Audio.loop("keen", chestPart, 1)
end

------------------------------------------------------------------ loop

function Banshee.setup()
	model, facePart, chestPart = Rigs.banshee()
	anims = Models.animations(model, "Banshee")
	if Models.find("Banshee") then
		kneelDrop = Config.models.Banshee.kneelDrop
	end
	model.Parent = ServerStorage

	Registry.died:Connect(function(entity, position: Vector3)
		if state == "Keening" and keen and (entity.wing == keen.wing or Map.wingAt(position) == keen.wing) then
			resolve("fulfilled")
			task.delay(2.5, function()
				Banshee.mourn(position, { key = entity.id, duration = 30, grace = cfg.aftermathGrace })
			end)
		elseif state == "Hidden" and distantEnabled and Config.story.mournDullahanDeaths and not mournedWings[entity.wing] then
			task.delay(3, function()
				Banshee.mourn(position, { key = entity.id, duration = 30, grace = cfg.aftermathGrace })
			end)
		end
	end)

	Rites.completed:Connect(function(_site, wing: string)
		if keen and keen.wing == wing then
			resolve("rite")
		end
	end)

	Noise.emitted:Connect(function(noise)
		if state == "Mourning" and mourning and noise.kind == "gunshot" and os.clock() >= mourning.graceUntil then
			if (noise.position - model:GetPivot().Position).Magnitude <= cfg.disturbShotRadius then
				disturb(noise.source)
			end
		end
	end)

	Players.PlayerRemoving:Connect(function(player)
		if keen and keen.target == player then
			local others = Crew.playersInWing(keen.wing, true)
			if #others > 0 then
				keen.target = others[1]
			end
		end
	end)

	task.spawn(function()
		while true do
			task.wait(0.25)
			local now = os.clock()

			for wing, v in visits do
				local occupied = #Crew.playersInWing(wing, true) > 0
				if occupied and not v.occupied then
					v.keened = false
				end
				v.occupied = occupied
			end

			if state == "Mourning" and mourning then
				local face = facePart
				local herPos = model:GetPivot().Position
				local disturber: Player? = nil
				local listening = now >= mourning.graceUntil
				for _, player in Crew.activePlayers() do
					local root = Crew.root(player)
					local radius = if player:GetAttribute("MoveMode") == "crouch" then cfg.disturbRadiusCrouched else cfg.disturbRadius
					if listening and root and (root.Position - herPos).Magnitude <= radius then
						disturber = player
						break
					end
				end
				if listening and not disturber and face then
					disturber = Light.beamOn(face.Position, cfg.disturbLightRange, { model })
				end
				if disturber then
					disturb(disturber)
				elseif now >= mourning.endsAt then
					endMourning(false)
				end
			elseif state == "Keening" and keen then
				local k = keen
				if #Crew.playersInWing(k.wing, true) == 0 then
					resolve("left")
				elseif now >= k.endsAt then
					task.spawn(take)
				elseif now - k.lastAgitate >= cfg.agitateEvery then
					k.lastAgitate = now
					local root = Crew.root(k.target)
					for _, e in Registry.activeInWing(k.wing) do
						e:agitate(if root then root.Position else e:position())
					end
				end
			elseif state == "Hidden" then
				if distantEnabled and now >= nextDistantAt then
					nextDistantAt = now + cfg.distantMin + math.random() * (cfg.distantMax - cfg.distantMin)
					Banshee.distantNow()
				end
				if naturalEnabled and now >= nextNaturalAt then
					local bestWing, bestCount = nil, 0
					for _, wing in KEEN_WINGS do
						local count = #Crew.playersInWing(wing)
						if count > bestCount and Banshee.canKeen(wing) then
							bestWing, bestCount = wing, count
						end
					end
					if bestWing and Banshee.keen(bestWing) then
						-- scheduled again when it resolves
						nextNaturalAt = math.huge
					else
						nextNaturalAt = now + 20
					end
				end
			end
		end
	end)
end

return Banshee
]=] },
}

local function child(parent: Instance, name: string): Instance
	local found = parent:FindFirstChild(name)
	assert(found, `[Ashgrove] expected {parent:GetFullName()}.{name} (paste the parts in order, starting from part 1)`)
	return found :: Instance
end

local function serviceAt(names: { string }): Instance
	local node: Instance = game:GetService(names[1])
	for i = 2, #names do
		node = child(node, names[i])
	end
	return node
end

local function install()
	local ChangeHistoryService = game:GetService("ChangeHistoryService")
	local ok, recording = pcall(function()
		return ChangeHistoryService:TryBeginRecording("Install Ashgrove House")
	end)
	if not ok then
		recording = nil
	end

	-- Remove older installs first.
	if REMOVE_OLD then
		for _, r in ROOTS do
			local old = serviceAt(r.service):FindFirstChild(r.name)
			if old then
				old:Destroy()
			end
		end
	end

	for _, f in FILES do
		local parent = serviceAt(f.service)
		for i = 1, #f.path - 1 do
			parent = child(parent, f.path[i])
		end
		local existing = parent:FindFirstChild(f.path[#f.path])
		if existing then
			existing:Destroy()
		end
		local inst = Instance.new(f.class)
		inst.Name = f.path[#f.path]
		if f.source then
			(inst :: any).Source = f.source
		end
		inst.Parent = parent
	end

	if FINISH then
		for _, name in { "Baseplate", "SpawnLocation" } do
			local leftover = workspace:FindFirstChild(name)
			if leftover and leftover:IsA("BasePart") then
				leftover:Destroy()
			end
		end
		if not workspace:FindFirstChild("AshgroveHouse") then
			require(game:GetService("ServerScriptService").Ashgrove.House).build()
		end
	end

	if recording then
		pcall(function()
			ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
		end)
	end
	print(DONE_MESSAGE)
end

if plugin then
	local toolbar = plugin:CreateToolbar("Ashgrove")
	local button = toolbar:CreateButton("Install", "Install or update Ashgrove House in this place", "")
	button.ClickableWhenViewportHidden = true
	button.Click:Connect(install)
else
	install()
end
