--[[
	ASHGROVE HOUSE installer, PART 8 OF 8.
	Generated by ashgrove/tools/build_installer.py. Don't edit by hand.

	Paste the parts into Studio's Command Bar IN ORDER (1, 2, 3 ...),
	pressing Enter after each. Wait for the Output window to say
	"part 8 of 8 done" before pasting the next one.
	This is the LAST part: it also builds the house. Then press Play.
]]

local REMOVE_OLD = false
local FINISH = true
local DONE_MESSAGE = "[Ashgrove] Installed. Press Play. (Studio keys: F6 next chapter, F7 keen, F8 refill.)"
local ROOTS = {
	{ service = {"ReplicatedStorage"}, name = "Ashgrove" },
	{ service = {"ServerScriptService"}, name = "Ashgrove" },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, name = "AshgroveClient" },
}

local FILES = {
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Shots"}, class = "ModuleScript", source = [=[
--[[
	Shots: notices YOUR gun hitting Ashgrove's monsters, without needing to
	know how your gun works.

	Three sources, combined (Config.integration.hitDetection):
	  1. Click reports. Every left click with a tool out sends the camera's
	     ray here. That's the gunshot NOISE (always), and the aim used to
	     work out which body part was hit.
	  2. Damage. Monster Humanoids have huge health; when your gun damages
	     one, that's the confirmed hit. The part is found along the
	     shooter's last click ray (the Dullahan's head matters), and health
	     is topped back up straight away.
	  3. Hooks.reportHit(player, part, position) from your gun's own code.
	     Exact. Once it's been used, 1 and 2 stop counting hits.

	In "auto" mode, if three click rays hit a monster and none of them ever
	came with damage, your gun clearly doesn't damage Humanoids: Shots
	switches to "click" mode by itself and says so in the Output window.

	Click rays don't know about your wobble. For hits that match your
	bullets exactly, wire Hooks.reportHit.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Config = require(Shared:WaitForChild("Config"))
local Net = require(Shared:WaitForChild("Net"))

local Crew = require(script.Parent.Crew)
local Map = require(script.Parent.Map)
local Noise = require(script.Parent.Noise)
local Registry = require(script.Parent.Entities.Registry)

local cfg = Config.integration

local Shots = {}

type Click = { origin: Vector3, direction: Vector3, at: number }

local mode: string = cfg.hitDetection
local lastClick: { [Player]: Click } = {}
local lastNoise: { [Player]: number } = {}
local damageEverSeen = false
local hooksUsed = false
local undamagedClickHits = 0

local function rayParams(): RaycastParams
	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	local ignore: { Instance } = { Map.interact("Glows") }
	for _, player in Players:GetPlayers() do
		if player.Character then
			table.insert(ignore, player.Character)
		end
	end
	params.FilterDescendantsInstances = ignore
	return params
end

-- First thing along a ray; returns the entity if it's one of ours.
local function castFor(origin: Vector3, direction: Vector3): (any, BasePart?, Vector3?)
	local result = workspace:Raycast(origin, direction.Unit * cfg.clickRange, rayParams())
	if not result then
		return nil, nil, nil
	end
	return Registry.fromPart(result.Instance), result.Instance :: BasePart, result.Position
end

local function apply(entity, part: BasePart, shooter: Player, position: Vector3)
	if entity and entity.status == "active" then
		entity:shot(part, shooter, position)
	end
end

------------------------------------------------------------------ for Hooks

function Shots.reportShot(player: Player, origin: Vector3?)
	local now = os.clock()
	if now - (lastNoise[player] or 0) < 0.15 then
		return
	end
	lastNoise[player] = now
	local head = Crew.head(player)
	local at = origin or (if head then head.Position else nil)
	if at then
		Noise.emit(at, cfg.gunshotNoise, "gunshot", player)
	end
end

function Shots.reportHit(player: Player, part: BasePart, position: Vector3?)
	hooksUsed = true
	local entity = Registry.fromPart(part)
	if entity then
		apply(entity, part, player, position or part.Position)
	end
end

function Shots.reportReload(player: Player, seconds: number?)
	local duration = seconds or cfg.reloadTorchOff
	if duration > 0 then
		Crew.suppressFlashlight(player, duration)
	end
end

------------------------------------------------------------------ damage

-- Entity calls this when its Humanoid loses health.
function Shots.onDamaged(entity)
	damageEverSeen = true
	if hooksUsed or mode == "hooks" or mode == "click" then
		return
	end
	-- Who did it: the most recent click whose ray reaches this entity.
	local now = os.clock()
	local bestPlayer, bestPart, bestPos, bestAt = nil, nil, nil, -math.huge
	for player, click in lastClick do
		if now - click.at < 0.8 and click.at > bestAt then
			local hitEntity, part, position = castFor(click.origin, click.direction)
			if hitEntity == entity and part then
				bestPlayer, bestPart, bestPos, bestAt = player, part, position, click.at
			end
		end
	end
	if not bestPlayer then
		-- Shot from an angle the click ray can't explain (your wobble): blame
		-- the nearest player with a tool out, and call it a body hit.
		local root = entity.root
		local nearest, distance = nil, math.huge
		for _, player in Players:GetPlayers() do
			local character = player.Character
			local r = Crew.root(player)
			if character and r and root and character:FindFirstChildOfClass("Tool") then
				local d = (r.Position - root.Position).Magnitude
				if d < distance then
					nearest, distance = player, d
				end
			end
		end
		if nearest and root then
			apply(entity, root, nearest, root.Position)
		end
		return
	end
	apply(entity, bestPart :: BasePart, bestPlayer, bestPos :: Vector3)
end

------------------------------------------------------------------ clicks

local function onClick(player: Player, origin: any, direction: any)
	if typeof(origin) ~= "Vector3" or typeof(direction) ~= "Vector3" or direction.Magnitude < 0.5 then
		return
	end
	local head = Crew.head(player)
	if not head or (origin - head.Position).Magnitude > 10 or not Crew.isActive(player) then
		return
	end
	local character = player.Character
	if not character or not character:FindFirstChildOfClass("Tool") then
		return
	end
	local now = os.clock()
	lastClick[player] = { origin = origin, direction = direction.Unit, at = now }
	Shots.reportShot(player, origin)

	if hooksUsed or mode == "hooks" or mode == "damage" then
		return
	end
	local entity, part, position = castFor(origin, direction)
	if not entity or not part then
		return
	end
	if mode == "click" then
		apply(entity, part, player, position :: Vector3)
		return
	end
	-- "auto": wait a moment to see whether the gun's own damage arrives.
	task.delay(0.5, function()
		if damageEverSeen or hooksUsed or mode ~= "auto" then
			return
		end
		undamagedClickHits += 1
		if undamagedClickHits >= 3 then
			mode = "click"
			warn("[Ashgrove] Your gun doesn't seem to damage Humanoids, so hits now come from click rays. For exact hits, call Hooks.reportHit from your gun (see ServerScriptService.Ashgrove.Hooks).")
			apply(entity, part, player, position :: Vector3)
		end
	end)
end

function Shots.start()
	Net.event("Shot").OnServerEvent:Connect(onClick)
	Net.event("Reload").OnServerEvent:Connect(function(player)
		local character = player.Character
		if character and character:FindFirstChildOfClass("Tool") then
			Shots.reportReload(player)
		end
	end)
	Players.PlayerRemoving:Connect(function(player)
		lastClick[player] = nil
		lastNoise[player] = nil
	end)
end

return Shots
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Storm"}, class = "ModuleScript", source = [=[
--[[
	Storm: the night's lighting, rain and lightning, and how they change.

	- Lightning is gameplay light. Flashes come at irregular intervals and
	  count as "lit" for Storm.flashWindow seconds (the Lamp-shy freezes).
	- The storm builds: each secured object raises the level. At
	  Config.storm.powerCutLevel the hall's work lamp fails and the hall
	  stops being a sanctuary.
	- When the Banshee keens, the storm goes silent: no rain, no lightning.
	  That silence is the warning.
]]

local Lighting = game:GetService("Lighting")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local SoundService = game:GetService("SoundService")
local TweenService = game:GetService("TweenService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))
local Net = require(Shared:WaitForChild("Net"))

local Map = require(script.Parent.Map)
local Say = require(script.Parent.Say)

local Storm = {}

Storm.level = 0

local silenced = false
local flashUntil = 0
local rain: Sound? = nil

local function setupLighting()
	Lighting.ClockTime = 1
	Lighting.Brightness = 0.3
	Lighting.Ambient = Color3.fromRGB(10, 10, 14)
	Lighting.OutdoorAmbient = Color3.fromRGB(26, 30, 38)
	Lighting.EnvironmentDiffuseScale = 0
	Lighting.EnvironmentSpecularScale = 0.2
	Lighting.GlobalShadows = true
	Lighting.ExposureCompensation = -0.2
	Lighting.FogColor = Color3.fromRGB(20, 24, 30)
	Lighting.FogStart = 0
	Lighting.FogEnd = 260

	for _, child in Lighting:GetChildren() do
		if child:IsA("Sky") or child:IsA("Atmosphere") then
			child:Destroy()
		end
	end
	local sky = Instance.new("Sky")
	sky.StarCount = 0
	sky.CelestialBodiesShown = false
	sky.Parent = Lighting
	local atmosphere = Instance.new("Atmosphere")
	atmosphere.Density = 0.42
	atmosphere.Offset = 0.1
	atmosphere.Color = Color3.fromRGB(40, 46, 56)
	atmosphere.Decay = Color3.fromRGB(20, 22, 28)
	atmosphere.Glare = 0
	atmosphere.Haze = 2
	atmosphere.Parent = Lighting
end

function Storm.isFlashing(): boolean
	return os.clock() < flashUntil
end

function Storm.isSilenced(): boolean
	return silenced
end

local function flash()
	flashUntil = os.clock() + Config.storm.flashWindow
	Net.event("Lightning"):FireAllClients(1)
	task.delay(1 + math.random() * 2.5, function()
		if silenced then
			return
		end
		Audio.play("thunder", SoundService, 0.7)
		Say.all("[Thunder]", 2, "sound")
	end)
end

-- Dressing's living details: failing bulbs and candles (Flicker =
-- "bulb"), the lit attic window that sometimes goes dark (Flicker =
-- "window"), and the lighthouse beam (Spin).
local function animateDetails()
	local bulbs, windows, spinners = {}, {}, {}
	for _, d in Map.root():GetDescendants() do
		if d:IsA("Light") then
			local kind = d:GetAttribute("Flicker")
			if kind == "bulb" then
				table.insert(bulbs, { light = d, base = d.Brightness })
			elseif kind == "window" then
				table.insert(windows, { light = d, base = d.Brightness })
			end
		elseif d:IsA("BasePart") and d:GetAttribute("Spin") then
			table.insert(spinners, d)
		end
	end
	task.spawn(function()
		while true do
			task.wait(0.08)
			for _, b in bulbs do
				local r = math.random()
				b.light.Brightness = if r < 0.06 then 0 elseif r < 0.2 then b.base * 0.4 else b.base
			end
		end
	end)
	for _, w in windows do
		task.spawn(function()
			while true do
				w.light.Enabled = true
				task.wait(20 + math.random() * 40)
				w.light.Enabled = false
				task.wait(4 + math.random() * 10)
			end
		end)
	end
	if #spinners > 0 then
		task.spawn(function()
			local angle = 0
			while true do
				local dt = task.wait(0.05)
				angle += dt * 0.6
				for _, beam in spinners do
					local centre = beam:GetAttribute("SpinCentre")
					if typeof(centre) == "Vector3" then
						beam.CFrame = CFrame.new(centre) * CFrame.Angles(0, angle, 0) * CFrame.new(0, 0, -beam.Size.Z / 2)
					end
				end
			end
		end)
	end
end

function Storm.start()
	setupLighting()
	animateDetails()
	rain = Audio.loop("rain", SoundService, Config.storm.rainVolume[0])
	task.spawn(function()
		while true do
			local range = Config.storm.lightning[math.min(Storm.level, 3)]
			task.wait(range.min + math.random() * (range.max - range.min))
			if not silenced then
				flash()
			end
		end
	end)
end

function Storm.silence(on: boolean)
	silenced = on
	if rain then
		local volume = if on then 0 else Config.storm.rainVolume[math.min(Storm.level, 3)]
		TweenService:Create(rain, TweenInfo.new(if on then 1.5 else 4), { Volume = volume }):Play()
	end
end

-- Turns off every lamp in a power group. Zones powered by that group stop
-- being sanctuaries.
function Storm.cutPower(group: string)
	for _, lamp in Map.interact("Lamps"):GetChildren() do
		if lamp:GetAttribute("PowerGroup") == group then
			lamp:SetAttribute("Powered", false)
			for _, light in lamp:GetDescendants() do
				if light:IsA("Light") then
					light.Enabled = false
				end
			end
			if lamp:IsA("BasePart") then
				lamp.Material = Enum.Material.SmoothPlastic
				lamp.Color = Color3.fromRGB(40, 36, 30)
			end
		end
	end
	for _, zonePart in Map.zonesWithAttribute("PoweredBy", group) do
		zonePart:SetAttribute("Sanctuary", false)
	end
end

function Storm.escalate()
	Storm.level += 1
	if rain and not silenced then
		TweenService:Create(rain, TweenInfo.new(6), { Volume = Config.storm.rainVolume[math.min(Storm.level, 3)] }):Play()
	end
	Say.all("[The storm gets worse]", 3, "sound")
	if Storm.level == Config.storm.powerCutLevel then
		Storm.cutPower("Hall")
		Say.all("The work lamp in the hall gutters out. The hall isn't safe any more.", 6, "story")
	end
end

return Storm
]=] },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, path = {"AshgroveClient"}, class = "LocalScript", source = [=[
--[[
	Ashgrove House (client entry). Starts the HUD, controls, the torch and
	effects, and routes the server's one-off messages to the HUD.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Net = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Net"))

local Controls = require(script.Controls)
local Effects = require(script.Effects)
local Hud = require(script.Hud)
local Torch = require(script.Torch)

Hud.start()
Controls.start(Hud)
Torch.start()
Effects.start(Hud)

Net.event("Caption").OnClientEvent:Connect(Hud.caption)
Net.event("Note").OnClientEvent:Connect(Hud.showNote)
Net.event("Objectives").OnClientEvent:Connect(Hud.setObjectives)
Net.event("Chapter").OnClientEvent:Connect(Hud.chapter)
Net.event("Screen").OnClientEvent:Connect(Hud.screen)
]=] },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, path = {"AshgroveClient", "Controls"}, class = "ModuleScript", source = [=[
--[[
	Controls: keyboard input. Movement modes go to the server, which sets
	speed (and the noise you make). PC keyboard and mouse only for now.
	Shooting and reloading are your gun's; the reload key here only tells
	Ashgrove to put the torch out while you reload.

	  Shift sprint   C crouch   F torch   G gold   Q close note   H help
	  E interact (Roblox prompts)   R (Config.integration.reloadKey) reload
	  Studio only: F6 next chapter, F7 keen here, F8 refill
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Config = require(Shared:WaitForChild("Config"))
local Net = require(Shared:WaitForChild("Net"))

local player = Players.LocalPlayer

local Controls = {}

local sprintHeld = false
local crouched = false
local sentMode = "walk"

local function sendMode()
	local mode = if sprintHeld then "sprint" elseif crouched then "crouch" else "walk"
	if mode ~= sentMode then
		sentMode = mode
		Net.event("Move"):FireServer(mode)
	end
	local character = player.Character
	local humanoid = character and character:FindFirstChildOfClass("Humanoid")
	if humanoid then
		local offset = if mode == "crouch" then Vector3.new(0, -1.6, 0) else Vector3.zero
		TweenService:Create(humanoid, TweenInfo.new(0.25), { CameraOffset = offset }):Play()
	end
end

function Controls.start(hud)
	UserInputService.InputBegan:Connect(function(input, processed)
		if processed then
			return
		end
		local key = input.KeyCode
		if key == Enum.KeyCode.LeftShift or key == Enum.KeyCode.RightShift then
			sprintHeld = true
			crouched = false
			sendMode()
		elseif key == Enum.KeyCode.C or key == Enum.KeyCode.LeftControl then
			crouched = not crouched
			sendMode()
		elseif key == Enum.KeyCode.F then
			Net.event("Flashlight"):FireServer(not player:GetAttribute("Flashlight"))
		elseif key == Config.integration.reloadKey then
			Net.event("Reload"):FireServer()
		elseif key == Enum.KeyCode.G then
			Net.event("Ward"):FireServer()
		elseif key == Enum.KeyCode.Q then
			hud.closeNote()
		elseif key == Enum.KeyCode.H then
			hud.toggleHelp()
		elseif RunService:IsStudio() and Config.debug.studioKeys then
			if key == Enum.KeyCode.F6 then
				Net.event("Debug"):FireServer("next")
			elseif key == Enum.KeyCode.F7 then
				Net.event("Debug"):FireServer("keen")
			elseif key == Enum.KeyCode.F8 then
				Net.event("Debug"):FireServer("refill") -- torch battery
			end
		end
	end)

	UserInputService.InputEnded:Connect(function(input)
		if input.KeyCode == Enum.KeyCode.LeftShift or input.KeyCode == Enum.KeyCode.RightShift then
			sprintHeld = false
			sendMode()
		end
	end)

	local function onCharacter(character: Model)
		sprintHeld = false
		crouched = false
		sentMode = ""
		task.defer(sendMode)
		-- Your own "Revive" prompt is for your crewmates; hide it from you.
		local root = character:WaitForChild("HumanoidRootPart", 10)
		local revive = root and root:WaitForChild("Revive", 10)
		if revive and revive:IsA("ProximityPrompt") then
			revive.MaxActivationDistance = 0
		end
	end
	player.CharacterAdded:Connect(onCharacter)
	if player.Character then
		task.spawn(onCharacter, player.Character)
	end
end

return Controls
]=] },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, path = {"AshgroveClient", "Effects"}, class = "ModuleScript", source = [=[
--[[
	Effects: what the server announces, drawn locally. Lightning, the
	keen's cold grade, rain around you when you're outdoors, and the
	spectator camera for a player the Banshee has taken.
]]

local Lighting = game:GetService("Lighting")
local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Net = require(Shared:WaitForChild("Net"))

local player = Players.LocalPlayer

local Effects = {}

local grade: ColorCorrectionEffect
local rain: ParticleEmitter
local keening = false
local flashing = false
local spectating = false
local spectateIndex = 0

local function lightning()
	if flashing then
		return
	end
	flashing = true
	local savedAmbient = Lighting.Ambient
	local savedOutdoor = Lighting.OutdoorAmbient
	local savedBrightness = Lighting.Brightness
	local function on()
		Lighting.Ambient = Color3.fromRGB(150, 160, 180)
		Lighting.OutdoorAmbient = Color3.fromRGB(190, 200, 220)
		Lighting.Brightness = 3
	end
	local function off()
		Lighting.Ambient = savedAmbient
		Lighting.OutdoorAmbient = savedOutdoor
		Lighting.Brightness = savedBrightness
	end
	on()
	task.wait(0.06)
	off()
	task.wait(0.09)
	on()
	task.wait(0.05)
	off()
	flashing = false
end

-- Rain falls around the camera when there's open sky above it. It stops
-- while she keens, with the storm.
local function startRain()
	local cloud = Instance.new("Part")
	cloud.Name = "AshgroveRain"
	cloud.Anchored = true
	cloud.CanCollide = false
	cloud.CanQuery = false
	cloud.CanTouch = false
	cloud.Transparency = 1
	cloud.Size = Vector3.new(70, 1, 70)
	rain = Instance.new("ParticleEmitter")
	rain.Texture = "rbxasset://textures/particles/sparkles_main.dds"
	rain.EmissionDirection = Enum.NormalId.Bottom
	rain.Rate = 700
	rain.Lifetime = NumberRange.new(0.5, 0.7)
	rain.Speed = NumberRange.new(90, 110)
	rain.Size = NumberSequence.new(0.12)
	rain.Squash = NumberSequence.new(3)
	rain.Transparency = NumberSequence.new(0.45)
	rain.Color = ColorSequence.new(Color3.fromRGB(170, 185, 200))
	rain.LightInfluence = 1
	rain.Parent = cloud
	cloud.Parent = workspace.CurrentCamera

	local params = RaycastParams.new()
	params.FilterType = Enum.RaycastFilterType.Exclude
	task.spawn(function()
		while true do
			task.wait(0.3)
			local camera = workspace.CurrentCamera
			if cloud.Parent ~= camera then
				cloud.Parent = camera
			end
			local at = camera.CFrame.Position
			cloud.CFrame = CFrame.new(at + Vector3.new(0, 35, 0))
			local character = player.Character
			params.FilterDescendantsInstances = if character then { character, cloud } else { cloud }
			local roof = workspace:Raycast(at, Vector3.new(0, 120, 0), params)
			rain.Enabled = roof == nil and not keening
		end
	end)
end

local function keen(state: string)
	keening = state == "start"
	local goal = if state == "start"
		then { TintColor = Color3.fromRGB(196, 214, 214), Saturation = -0.55, Brightness = -0.06, Contrast = 0.12 }
		else { TintColor = Color3.new(1, 1, 1), Saturation = 0, Brightness = 0, Contrast = 0 }
	TweenService:Create(grade, TweenInfo.new(if state == "start" then 1.5 else 3), goal):Play()
end

local function others(): { Player }
	local list = {}
	for _, other in Players:GetPlayers() do
		if other ~= player and other.Character and not other:GetAttribute("Taken") then
			table.insert(list, other)
		end
	end
	return list
end

local function watchNext()
	local list = others()
	if #list == 0 then
		return
	end
	spectateIndex = spectateIndex % #list + 1
	local character = list[spectateIndex].Character
	local humanoid = character and character:FindFirstChildOfClass("Humanoid")
	if humanoid then
		workspace.CurrentCamera.CameraSubject = humanoid
	end
end

local function spectate(on: boolean)
	spectating = on
	if on then
		watchNext()
	else
		local character = player.Character
		local humanoid = character and character:FindFirstChildOfClass("Humanoid")
		if humanoid then
			workspace.CurrentCamera.CameraSubject = humanoid
		end
	end
end

function Effects.start(hud)
	grade = Instance.new("ColorCorrectionEffect")
	grade.Name = "AshgroveKeenGrade"
	grade.Parent = Lighting
	startRain()

	Net.event("Lightning").OnClientEvent:Connect(function()
		task.spawn(lightning)
	end)
	Net.event("Keen").OnClientEvent:Connect(function(state: string, info)
		keen(state)
		hud.keen(state, info or {})
	end)
	Net.event("Spectate").OnClientEvent:Connect(spectate)

	UserInputService.InputBegan:Connect(function(input, processed)
		if spectating and not processed and input.UserInputType == Enum.UserInputType.MouseButton1 then
			watchNext()
		end
	end)
end

return Effects
]=] },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, path = {"AshgroveClient", "Hud"}, class = "ModuleScript", source = [=[
--[[
	Hud: everything on screen. Built in code so there's nothing to import.

	Reads the player attributes the server sets (Battery, LightOn, HasGold,
	WardReadyAt, Commit*, Downed, Taken, Hits)
	every frame, and exposes calls for one-off events (captions, notes,
	chapter cards, keens, full-screen states).

	Kept deliberately quiet: no health bar, no minimap, no timer on a keen.
	No crosshair or ammo counter either: those are your gun's.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Config = require(Shared:WaitForChild("Config"))
local Notes = require(Shared:WaitForChild("Notes"))

local player = Players.LocalPlayer

local Hud = {}

local PAPER = Color3.fromRGB(226, 218, 196)
local DIM = Color3.fromRGB(150, 146, 136)
local INK = Color3.fromRGB(16, 15, 14)
local BODY_FONT = Enum.Font.SourceSans
local TITLE_FONT = Enum.Font.Garamond

local gui: ScreenGui
local batteryFill: Frame
local goldLabel: TextLabel
local objectivesFrame: Frame
local captionsFrame: Frame
local commitFrame: Frame
local commitFill: Frame
local commitLabel: TextLabel
local notePanel: Frame
local noteTitle: TextLabel
local noteBody: TextLabel
local noteScroll: ScrollingFrame
local chapterTitle: TextLabel
local chapterSub: TextLabel
local keenLabel: TextLabel
local keenShade: Frame
local hurtFlash: Frame
local overlay: Frame
local overlayText: TextLabel
local helpPanel: Frame

local noteOpenAt: Vector3? = nil
local keenInfo: { [string]: any }? = nil
local lastHits = 0
local screenKind = ""

local function new(className: string, props: { [string]: any }, parent: Instance?): any
	local inst = Instance.new(className)
	for k, v in props do
		(inst :: any)[k] = v
	end
	if parent then
		inst.Parent = parent
	end
	return inst
end

local function text(props: { [string]: any }, parent: Instance): TextLabel
	local defaults = {
		BackgroundTransparency = 1,
		Font = BODY_FONT,
		TextColor3 = PAPER,
		TextSize = 20,
		TextWrapped = true,
	}
	for k, v in props do
		defaults[k] = v
	end
	return new("TextLabel", defaults, parent)
end

local function build()
	gui = new("ScreenGui", {
		Name = "AshgroveHud",
		ResetOnSpawn = false,
		IgnoreGuiInset = true,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
	}, player:WaitForChild("PlayerGui"))

	local battery = new("Frame", {
		Name = "Battery",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 28, 1, -32),
		Size = UDim2.fromOffset(160, 6),
		BackgroundColor3 = INK,
		BackgroundTransparency = 0.3,
		BorderSizePixel = 0,
	}, gui)
	batteryFill = new("Frame", {
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = PAPER,
		BorderSizePixel = 0,
	}, battery)
	text({
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 0, 0, -4),
		Size = UDim2.fromOffset(160, 18),
		Text = "TORCH",
		TextXAlignment = Enum.TextXAlignment.Left,
		TextColor3 = DIM,
		TextSize = 14,
	}, battery)
	goldLabel = text({
		Name = "Gold",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.new(0, 28, 1, -64),
		Size = UDim2.fromOffset(240, 20),
		TextXAlignment = Enum.TextXAlignment.Left,
		TextColor3 = Color3.fromRGB(214, 180, 90),
		TextSize = 16,
		Visible = false,
	}, gui)

	objectivesFrame = new("Frame", {
		Name = "Objectives",
		Position = UDim2.fromOffset(28, 28),
		Size = UDim2.fromOffset(420, 200),
		BackgroundTransparency = 1,
	}, gui)
	new("UIListLayout", { Padding = UDim.new(0, 4), SortOrder = Enum.SortOrder.LayoutOrder }, objectivesFrame)

	captionsFrame = new("Frame", {
		Name = "Captions",
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.new(0.5, 0, 1, -110),
		Size = UDim2.new(0.6, 0, 0, 200),
		BackgroundTransparency = 1,
	}, gui)
	new("UIListLayout", {
		Padding = UDim.new(0, 2),
		SortOrder = Enum.SortOrder.LayoutOrder,
		VerticalAlignment = Enum.VerticalAlignment.Bottom,
		HorizontalAlignment = Enum.HorizontalAlignment.Center,
	}, captionsFrame)

	commitFrame = new("Frame", {
		Name = "Commit",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.new(0.5, 0, 0.62, 0),
		Size = UDim2.fromOffset(260, 6),
		BackgroundColor3 = INK,
		BackgroundTransparency = 0.3,
		BorderSizePixel = 0,
		Visible = false,
	}, gui)
	commitFill = new("Frame", { Size = UDim2.fromScale(0, 1), BackgroundColor3 = PAPER, BorderSizePixel = 0 }, commitFrame)
	commitLabel = text({
		AnchorPoint = Vector2.new(0.5, 1),
		Position = UDim2.new(0.5, 0, 0, -6),
		Size = UDim2.fromOffset(400, 22),
		TextSize = 18,
	}, commitFrame)

	chapterTitle = text({
		Name = "ChapterTitle",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.3),
		Size = UDim2.new(0.8, 0, 0, 60),
		Font = TITLE_FONT,
		TextSize = 48,
		TextTransparency = 1,
	}, gui)
	chapterSub = text({
		Name = "ChapterSub",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.new(0.5, 0, 0.3, 46),
		Size = UDim2.new(0.8, 0, 0, 30),
		Font = TITLE_FONT,
		TextSize = 24,
		TextColor3 = DIM,
		TextTransparency = 1,
	}, gui)

	keenShade = new("Frame", {
		Name = "KeenShade",
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = Color3.new(0, 0, 0),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ZIndex = 0,
	}, gui)
	keenLabel = text({
		Name = "Keen",
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.new(0.5, 0, 0, 34),
		Size = UDim2.new(0.6, 0, 0, 30),
		Font = TITLE_FONT,
		TextSize = 26,
		TextColor3 = Config.banshee.colour,
		Visible = false,
	}, gui)

	hurtFlash = new("Frame", {
		Name = "Hurt",
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = Color3.fromRGB(120, 0, 0),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
	}, gui)

	notePanel = new("Frame", {
		Name = "Note",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.48),
		Size = UDim2.fromOffset(560, 460),
		BackgroundColor3 = Color3.fromRGB(30, 28, 24),
		BackgroundTransparency = 0.05,
		BorderSizePixel = 0,
		Visible = false,
		ZIndex = 10,
	}, gui)
	new("UISizeConstraint", { MaxSize = Vector2.new(560, 460) }, notePanel)
	new("UIPadding", {
		PaddingTop = UDim.new(0, 20),
		PaddingBottom = UDim.new(0, 20),
		PaddingLeft = UDim.new(0, 24),
		PaddingRight = UDim.new(0, 24),
	}, notePanel)
	new("UIStroke", { Color = DIM, Transparency = 0.6 }, notePanel)
	noteTitle = text({
		Size = UDim2.new(1, 0, 0, 32),
		Font = TITLE_FONT,
		TextSize = 26,
		TextXAlignment = Enum.TextXAlignment.Left,
		ZIndex = 11,
	}, notePanel)
	noteScroll = new("ScrollingFrame", {
		Position = UDim2.fromOffset(0, 44),
		Size = UDim2.new(1, 0, 1, -76),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ScrollBarThickness = 4,
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		CanvasSize = UDim2.new(),
		ZIndex = 11,
	}, notePanel)
	noteBody = text({
		Size = UDim2.new(1, -8, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		TextSize = 20,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		LineHeight = 1.15,
		ZIndex = 11,
	}, noteScroll)
	text({
		AnchorPoint = Vector2.new(1, 1),
		Position = UDim2.fromScale(1, 1),
		Size = UDim2.fromOffset(200, 20),
		Text = "[Q] put it down",
		TextColor3 = DIM,
		TextSize = 16,
		TextXAlignment = Enum.TextXAlignment.Right,
		ZIndex = 11,
	}, notePanel)

	overlay = new("Frame", {
		Name = "Overlay",
		Size = UDim2.fromScale(1, 1),
		BackgroundColor3 = Color3.new(0, 0, 0),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		ZIndex = 20,
	}, gui)
	overlayText = text({
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.new(0.7, 0, 0, 200),
		Font = TITLE_FONT,
		TextSize = 32,
		TextTransparency = 1,
		ZIndex = 21,
	}, overlay)

	helpPanel = new("Frame", {
		Name = "Help",
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.new(1, -28, 0, 28),
		Size = UDim2.fromOffset(300, 260),
		BackgroundColor3 = Color3.fromRGB(20, 19, 17),
		BackgroundTransparency = 0.2,
		BorderSizePixel = 0,
		Visible = false,
	}, gui)
	new("UIPadding", {
		PaddingTop = UDim.new(0, 12),
		PaddingLeft = UDim.new(0, 14),
		PaddingRight = UDim.new(0, 14),
	}, helpPanel)
	text({
		Size = UDim2.fromScale(1, 1),
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		TextSize = 18,
		Text = table.concat({
			"WASD   move",
			"Shift  sprint (loud)",
			"C      crouch (silent)",
			"F      torch",
			"R      reload (your torch goes off)",
			"G      raise the gold, if you have it",
			"E      interact",
			"Q      put a note down",
			"H      this help",
			"",
			"Crouch near her while she grieves.",
		}, "\n"),
	}, helpPanel)
end

------------------------------------------------------------------ calls

local captionOrder = 0
function Hud.caption(message: string, seconds: number?, style: string?)
	captionOrder += 1
	local colour = if style == "sound" then DIM elseif style == "hint" then Color3.fromRGB(180, 196, 210) else PAPER
	local label = text({
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Text = message,
		TextColor3 = colour,
		TextSize = if style == "sound" then 19 else 21,
		Font = if style == "sound" then Enum.Font.SourceSansItalic else BODY_FONT,
		TextStrokeTransparency = 0.6,
		LayoutOrder = captionOrder,
	}, captionsFrame)
	local labels = {}
	for _, child in captionsFrame:GetChildren() do
		if child:IsA("TextLabel") then
			table.insert(labels, child)
		end
	end
	table.sort(labels, function(a, b)
		return a.LayoutOrder < b.LayoutOrder
	end)
	while #labels > 5 do
		local oldest = table.remove(labels, 1)
		if oldest then
			oldest:Destroy()
		end
	end
	task.delay(seconds or 4, function()
		if label.Parent then
			local fade = TweenService:Create(label, TweenInfo.new(0.8), { TextTransparency = 1, TextStrokeTransparency = 1 })
			fade:Play()
			fade.Completed:Wait()
			label:Destroy()
		end
	end)
end

function Hud.setObjectives(list: { { text: string, done: boolean? } })
	for _, child in objectivesFrame:GetChildren() do
		if child:IsA("TextLabel") then
			child:Destroy()
		end
	end
	for i, objective in list do
		text({
			Size = UDim2.new(1, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			Text = (if objective.done then "x  " else "-  ") .. objective.text,
			TextColor3 = if objective.done then DIM else PAPER,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextSize = 18,
			TextStrokeTransparency = 0.7,
			LayoutOrder = i,
		}, objectivesFrame)
	end
end

function Hud.chapter(title: string, subtitle: string)
	chapterTitle.Text = title
	chapterSub.Text = subtitle
	for _, label in { chapterTitle, chapterSub } do
		label.TextTransparency = 1
		TweenService:Create(label, TweenInfo.new(1.5), { TextTransparency = 0 }):Play()
	end
	task.delay(5, function()
		for _, label in { chapterTitle, chapterSub } do
			TweenService:Create(label, TweenInfo.new(2), { TextTransparency = 1 }):Play()
		end
	end)
end

function Hud.showNote(noteId: string)
	local note = Notes[noteId]
	if not note then
		return
	end
	noteTitle.Text = note.title
	noteBody.Text = note.body
	noteScroll.CanvasPosition = Vector2.zero
	notePanel.Visible = true
	local character = player.Character
	local root = character and character:FindFirstChild("HumanoidRootPart")
	noteOpenAt = if root then (root :: BasePart).Position else nil
end

function Hud.closeNote()
	notePanel.Visible = false
	noteOpenAt = nil
end

function Hud.isNoteOpen(): boolean
	return notePanel.Visible
end

function Hud.toggleHelp()
	helpPanel.Visible = not helpPanel.Visible
end

function Hud.keen(state: string, info: { [string]: any })
	if state == "start" then
		keenInfo = info
		keenLabel.Visible = true
		keenLabel.Text = if info.target == player.UserId then "She is facing you." else `She is facing {info.targetName}.`
	else
		keenInfo = nil
		keenLabel.Visible = false
		TweenService:Create(keenShade, TweenInfo.new(2), { BackgroundTransparency = 1 }):Play()
	end
end

-- Full-screen states: "wipe", "end", "clear".
function Hud.screen(kind: string, message: string)
	screenKind = if kind == "clear" then "" else kind
	if kind == "clear" then
		TweenService:Create(overlay, TweenInfo.new(1.5), { BackgroundTransparency = 1 }):Play()
		TweenService:Create(overlayText, TweenInfo.new(1), { TextTransparency = 1 }):Play()
		return
	end
	overlayText.Text = message
	TweenService:Create(overlay, TweenInfo.new(if kind == "end" then 4 else 1.5), { BackgroundTransparency = 0 }):Play()
	TweenService:Create(overlayText, TweenInfo.new(2), { TextTransparency = 0 }):Play()
end

------------------------------------------------------------------ per frame

local function update()
	local battery = (player:GetAttribute("Battery") or 0) / Config.flashlight.maxBattery
	batteryFill.Size = UDim2.fromScale(math.clamp(battery, 0, 1), 1)
	batteryFill.BackgroundTransparency = if player:GetAttribute("LightOn") then 0 else 0.6

	if player:GetAttribute("HasGold") then
		goldLabel.Visible = true
		local readyAt = player:GetAttribute("WardReadyAt") or 0
		local wait = readyAt - workspace:GetServerTimeNow()
		goldLabel.Text = if player:GetAttribute("WardRaised")
			then "GOLD raised"
			elseif wait > 0 then `GOLD  {math.ceil(wait)}s`
			else "GOLD  [G]"
	else
		goldLabel.Visible = false
	end

	local label = player:GetAttribute("CommitLabel")
	if label then
		commitFrame.Visible = true
		commitLabel.Text = label
		local length = player:GetAttribute("CommitLength") or 1
		local ends = player:GetAttribute("CommitEnds") or 0
		local progress = 1 - math.clamp((ends - workspace:GetServerTimeNow()) / length, 0, 1)
		commitFill.Size = UDim2.fromScale(progress, 1)
	else
		commitFrame.Visible = false
	end

	-- The one she faces sees the dark close in as the window runs out.
	if keenInfo and keenInfo.target == player.UserId then
		local left = math.clamp((keenInfo.endsAt - workspace:GetServerTimeNow()) / keenInfo.length, 0, 1)
		keenShade.BackgroundTransparency = 0.45 + 0.55 * left
	end

	local hits = player:GetAttribute("Hits") or 0
	if hits > lastHits then
		hurtFlash.BackgroundTransparency = 0.55
		TweenService:Create(hurtFlash, TweenInfo.new(0.8), { BackgroundTransparency = 1 }):Play()
	end
	lastHits = hits

	if screenKind ~= "wipe" and screenKind ~= "end" then
		if player:GetAttribute("Taken") then
			overlay.BackgroundTransparency = 0.15
			overlayText.TextTransparency = 0
			overlayText.Text = "Taken.\n\nYou'll come back when the others reach somewhere safe.\n(Click to watch someone else.)"
		elseif player:GetAttribute("Downed") then
			overlay.BackgroundTransparency = 0.55
			overlayText.TextTransparency = 0
			overlayText.Text = "You're down.\nA crewmate can get you up."
		elseif overlay.BackgroundTransparency < 1 then
			overlay.BackgroundTransparency = 1
			overlayText.TextTransparency = 1
		end
	end

	if noteOpenAt then
		local character = player.Character
		local root = character and character:FindFirstChild("HumanoidRootPart")
		if not root or ((root :: BasePart).Position - noteOpenAt).Magnitude > 10 then
			Hud.closeNote()
		end
	end
end

function Hud.start()
	build()
	RunService.RenderStepped:Connect(update)
end

return Hud
]=] },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, path = {"AshgroveClient", "Torch"}, class = "ModuleScript", source = [=[
--[[
	Torch: the player's own torch, drawn locally so it follows the camera
	without lag (the server's copy on your head, which everyone else sees,
	is hidden on your screen). Also reports to the server:
	  - where you're looking, ten times a second (the torch beam that
	    monsters react to)
	  - each left click with a tool out (your gun): monsters hear the shot,
	    and Shots uses the ray to tell which body part you hit.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Config = require(Shared:WaitForChild("Config"))
local Net = require(Shared:WaitForChild("Net"))

local player = Players.LocalPlayer

local Torch = {}

function Torch.start()
	local torch = Instance.new("Part")
	torch.Name = "AshLocalTorch"
	torch.Anchored = true
	torch.CanCollide = false
	torch.CanQuery = false
	torch.CanTouch = false
	torch.Transparency = 1
	torch.Size = Vector3.one * 0.2
	local light = Instance.new("SpotLight")
	light.Angle = Config.flashlight.angle
	light.Range = Config.flashlight.range
	light.Brightness = Config.flashlight.brightness
	light.Color = Color3.fromRGB(255, 240, 220)
	light.Shadows = true
	light.Face = Enum.NormalId.Front
	light.Enabled = false
	light.Parent = torch
	torch.Parent = workspace.CurrentCamera

	RunService:BindToRenderStep("AshgroveTorch", Enum.RenderPriority.Camera.Value + 1, function()
		local camera = workspace.CurrentCamera
		if torch.Parent ~= camera then
			torch.Parent = camera
		end
		torch.CFrame = camera.CFrame * CFrame.new(0.4, -0.5, 0)
		light.Enabled = player:GetAttribute("LightOn") == true
		local character = player.Character
		local head = character and character:FindFirstChild("Head")
		local attachment = head and head:FindFirstChild("AshFlashlight")
		local serverLight = attachment and attachment:FindFirstChild("AshFlashlight")
		if serverLight and serverLight:IsA("SpotLight") then
			serverLight.Enabled = false
		end
	end)

	local lastClick = 0
	UserInputService.InputBegan:Connect(function(input, processed)
		if processed or input.UserInputType ~= Enum.UserInputType.MouseButton1 then
			return
		end
		local character = player.Character
		if not character or not character:FindFirstChildOfClass("Tool") then
			return
		end
		local now = os.clock()
		if now - lastClick < 0.1 then
			return
		end
		lastClick = now
		local camera = workspace.CurrentCamera
		Net.event("Shot"):FireServer(camera.CFrame.Position, camera.CFrame.LookVector)
	end)

	task.spawn(function()
		local aimRemote = Net.unreliable("Aim")
		while true do
			task.wait(0.1)
			aimRemote:FireServer(workspace.CurrentCamera.CFrame.LookVector)
		end
	end)
end

return Torch
]=] },
}

local function child(parent: Instance, name: string): Instance
	local found = parent:FindFirstChild(name)
	assert(found, `[Ashgrove] expected {parent:GetFullName()}.{name} (paste the parts in order, starting from part 1)`)
	return found :: Instance
end

local function serviceAt(names: { string }): Instance
	local node: Instance = game:GetService(names[1])
	for i = 2, #names do
		node = child(node, names[i])
	end
	return node
end

local function install()
	local ChangeHistoryService = game:GetService("ChangeHistoryService")
	local ok, recording = pcall(function()
		return ChangeHistoryService:TryBeginRecording("Install Ashgrove House")
	end)
	if not ok then
		recording = nil
	end

	-- Remove older installs first.
	if REMOVE_OLD then
		for _, r in ROOTS do
			local old = serviceAt(r.service):FindFirstChild(r.name)
			if old then
				old:Destroy()
			end
		end
	end

	for _, f in FILES do
		local parent = serviceAt(f.service)
		for i = 1, #f.path - 1 do
			parent = child(parent, f.path[i])
		end
		local existing = parent:FindFirstChild(f.path[#f.path])
		if existing then
			existing:Destroy()
		end
		local inst = Instance.new(f.class)
		inst.Name = f.path[#f.path]
		if f.source then
			(inst :: any).Source = f.source
		end
		inst.Parent = parent
	end

	if FINISH then
		for _, name in { "Baseplate", "SpawnLocation" } do
			local leftover = workspace:FindFirstChild(name)
			if leftover and leftover:IsA("BasePart") then
				leftover:Destroy()
			end
		end
		if not workspace:FindFirstChild("AshgroveHouse") then
			require(game:GetService("ServerScriptService").Ashgrove.House).build()
		end
	end

	if recording then
		pcall(function()
			ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
		end)
	end
	print(DONE_MESSAGE)
end

if plugin then
	local toolbar = plugin:CreateToolbar("Ashgrove")
	local button = toolbar:CreateButton("Install", "Install or update Ashgrove House in this place", "")
	button.ClickableWhenViewportHidden = true
	button.Click:Connect(install)
else
	install()
end
