--[[
	ASHGROVE HOUSE installer, PART 7 OF 8.
	Generated by ashgrove/tools/build_installer.py. Don't edit by hand.

	Paste the parts into Studio's Command Bar IN ORDER (1, 2, 3 ...),
	pressing Enter after each. Wait for the Output window to say
	"part 7 of 8 done" before pasting the next one.
	Next: part 8.
]]

local REMOVE_OLD = false
local FINISH = false
local DONE_MESSAGE = "[Ashgrove] part 7 of 8 done. Now paste part 8."
local ROOTS = {
	{ service = {"ReplicatedStorage"}, name = "Ashgrove" },
	{ service = {"ServerScriptService"}, name = "Ashgrove" },
	{ service = {"StarterPlayer", "StarterPlayerScripts"}, name = "AshgroveClient" },
}

local FILES = {
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Map"}, class = "ModuleScript", source = [=[
--[[
	Map: what the gameplay knows about the house. Everything is looked up
	from workspace.AshgroveHouse by folder, name and attribute, so the
	greybox can be swapped for art without touching any system.

	Wings are the unit the Banshee and the entities care about:
	  Grounds, Van, Hall, Gallery, ServantsWing, Vault
	Rooms are finer, for the bell board and story triggers.
]]

local Debris = game:GetService("Debris")

local Map = {}

export type Zone = {
	name: string,
	wing: string,
	room: string,
	priority: number,
	part: BasePart,
}

local root: Model? = nil
local zones: { Zone } = {}

function Map.root(): Model
	if not root then
		local found = workspace:WaitForChild("AshgroveHouse") :: Model
		root = found
		for _, p in found:WaitForChild("Zones"):GetChildren() do
			if p:IsA("BasePart") then
				table.insert(zones, {
					name = p.Name,
					wing = p:GetAttribute("Wing") or p.Name,
					room = p:GetAttribute("Room") or p.Name,
					priority = p:GetAttribute("Priority") or 0,
					part = p,
				})
			end
		end
		table.sort(zones, function(a, b)
			return a.priority > b.priority
		end)
	end
	return root :: any
end

local function inside(p: BasePart, position: Vector3): boolean
	local rel = p.CFrame:PointToObjectSpace(position)
	local half = p.Size / 2
	return math.abs(rel.X) <= half.X and math.abs(rel.Y) <= half.Y and math.abs(rel.Z) <= half.Z
end

function Map.zoneAt(position: Vector3): Zone?
	Map.root()
	for _, z in zones do
		if inside(z.part, position) then
			return z
		end
	end
	return nil
end

function Map.wingAt(position: Vector3): string?
	local z = Map.zoneAt(position)
	return z and z.wing
end

function Map.roomAt(position: Vector3): string?
	local z = Map.zoneAt(position)
	return z and z.room
end

-- Sanctuary is read live: the hall stops being one when its lamp fails.
function Map.isSanctuary(position: Vector3): boolean
	local z = Map.zoneAt(position)
	return z ~= nil and z.part:GetAttribute("Sanctuary") == true
end

function Map.isExterior(position: Vector3): boolean
	local z = Map.zoneAt(position)
	return z ~= nil and z.part:GetAttribute("Exterior") == true
end

-- Across a threshold: somewhere the Banshee's keen can't follow.
function Map.isThreshold(position: Vector3): boolean
	return Map.isSanctuary(position) or Map.isExterior(position)
end

function Map.zonesWithAttribute(name: string, value: any): { BasePart }
	Map.root()
	local out = {}
	for _, z in zones do
		if z.part:GetAttribute(name) == value then
			table.insert(out, z.part)
		end
	end
	return out
end

function Map.marker(name: string): BasePart
	local m = Map.root():WaitForChild("Markers"):FindFirstChild(name)
	assert(m and m:IsA("BasePart"), `AshgroveHouse is missing marker "{name}"`)
	return m
end

function Map.markers(prefix: string): { BasePart }
	local out = {}
	for _, m in Map.root():WaitForChild("Markers"):GetChildren() do
		if m:IsA("BasePart") and string.sub(m.Name, 1, #prefix) == prefix then
			table.insert(out, m)
		end
	end
	table.sort(out, function(a, b)
		return a.Name < b.Name
	end)
	return out
end

function Map.interact(name: string): Instance
	return Map.root():WaitForChild("Interact"):WaitForChild(name)
end

-- Everything that counts as "light" for entities that care: powered lamps
-- and temporary glows (a dropped head, a dead Lamp-shy).
function Map.lightSources(): { BasePart }
	local out = {}
	for _, folderName in { "Lamps", "Glows" } do
		for _, p in Map.interact(folderName):GetChildren() do
			if p:IsA("BasePart") and (p:GetAttribute("LightRadius") or 0) > 0 and p:GetAttribute("Powered") ~= false then
				table.insert(out, p)
			end
		end
	end
	return out
end

-- A temporary light source. `follow` keeps it on a moving part.
function Map.addGlow(position: Vector3, radius: number, seconds: number, colour: Color3, follow: BasePart?): BasePart
	local p = Instance.new("Part")
	p.Name = "Glow"
	p.Anchored = follow == nil
	p.CanCollide = false
	p.CanQuery = false
	p.CanTouch = false
	p.Transparency = 1
	p.Size = Vector3.one * 0.5
	p.Position = position
	p:SetAttribute("LightRadius", radius)
	local light = Instance.new("PointLight")
	light.Range = radius * 1.4
	light.Brightness = 1.2
	light.Color = colour
	light.Parent = p
	if follow then
		local weld = Instance.new("WeldConstraint")
		weld.Part0 = follow
		weld.Part1 = p
		p.Position = follow.Position
		weld.Parent = p
		p.Massless = true
	end
	p.Parent = Map.interact("Glows")
	Debris:AddItem(p, seconds)
	return p
end

-- Random point on the floor of a zone part (top of the floor at its bottom).
function Map.randomPointIn(zonePart: BasePart, height: number?): Vector3
	local half = zonePart.Size / 2
	local local_ = Vector3.new((math.random() * 2 - 1) * (half.X - 3), -half.Y + 1 + (height or 0), (math.random() * 2 - 1) * (half.Z - 3))
	return zonePart.CFrame:PointToWorldSpace(local_)
end

return Map
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Models"}, class = "ModuleScript", source = [=[
--[[
	Models: uses your monster models when they exist, the greybox bodies
	when they don't.

	WHERE TO PUT YOUR MODELS. Any of these work (checked in this order):
	  ServerStorage.AshgroveModels.<name>
	  ReplicatedStorage.AshgroveModels.<name>
	  anywhere in Workspace or ServerStorage
	with <name> one of Config.models[id].names (case, spaces, "_" and "-"
	ignored), e.g. "Dullahan", "AH_Ent_Dullahan", "Banshee". A model left
	standing in the Workspace is moved to ServerStorage.AshgroveModels when
	the game starts, so it doesn't stand in the level in a T-pose.

	WHAT A MODEL NEEDS
	  - Rigged (Humanoid + HumanoidRootPart): used as it is. Its front must
	    be the root's -Z (the usual Roblox export).
	  - Not rigged (just meshes): it's carried on an invisible root and
	    Humanoid that Ashgrove adds. Its front must face -Z.
	  - The Dullahan's carried head: a part named Config.models.Dullahan.
	    headPart ("CarriedHead"), or failing that any part with "head" in
	    its name. It's what he sees through and his weak point.
	  - Hit parts: anything with "head" in its name counts as a head hit,
	    everything else as body, unless you set a Hitbox attribute
	    ("Head" / "Body") yourself.
	  - Animations: optional ids in Config.models[id].animations.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local ServerStorage = game:GetService("ServerStorage")

local Config = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Config"))

local Models = {}

local cache: { [string]: Model | false } = {}

local function normal(name: string): string
	return string.lower((string.gsub(name, "[%s_%-]", "")))
end

local function storageFolder(): Folder
	local f = ServerStorage:FindFirstChild("AshgroveModels")
	if not f then
		f = Instance.new("Folder")
		f.Name = "AshgroveModels"
		f.Parent = ServerStorage
	end
	return f :: Folder
end

local function isExcluded(inst: Instance): boolean
	local house = workspace:FindFirstChild("AshgroveHouse")
	if house and inst:IsDescendantOf(house) then
		return true
	end
	for _, player in game:GetService("Players"):GetPlayers() do
		if player.Character and inst:IsDescendantOf(player.Character) then
			return true
		end
	end
	return false
end

-- The template model for an entity id, or nil.
function Models.find(id: string): Model?
	local cached = cache[id]
	if cached ~= nil then
		return if cached then cached else nil
	end
	local cfg = (Config.models :: any)[id]
	if not cfg then
		cache[id] = false
		return nil
	end
	local wanted: { [string]: boolean } = {}
	for _, name in cfg.names do
		wanted[normal(name)] = true
	end
	local function search(list: { Instance }): Model?
		for _, inst in list do
			if inst:IsA("Model") and wanted[normal(inst.Name)] and not isExcluded(inst) then
				return inst
			end
		end
		return nil
	end
	local found: Model? = nil
	for _, holder in { ServerStorage, ReplicatedStorage } do
		local folder = holder:FindFirstChild("AshgroveModels")
		if folder and not found then
			found = search(folder:GetChildren())
		end
	end
	found = found or search(workspace:GetDescendants()) or search(ServerStorage:GetDescendants())
	if found and found:IsDescendantOf(workspace) then
		found.Parent = storageFolder()
	end
	cache[id] = found or false
	return found
end

-- Look for every configured model now (moves any out of the Workspace).
function Models.collect()
	for id in Config.models :: any do
		local found = Models.find(id)
		if found then
			print(`[Ashgrove] Using your model "{found.Name}" for {id}.`)
		end
	end
end

function Models.configureHumanoid(humanoid: Humanoid)
	humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	humanoid.HealthDisplayType = Enum.HumanoidHealthDisplayType.AlwaysOff
	humanoid.BreakJointsOnDeath = false
	humanoid.RequiresNeck = false
	humanoid.MaxHealth = 1e6
	humanoid.Health = 1e6
	humanoid.UseJumpPower = true
	humanoid.JumpPower = 0
	humanoid.WalkSpeed = 0
	humanoid:SetStateEnabled(Enum.HumanoidStateType.FallingDown, false)
	humanoid:SetStateEnabled(Enum.HumanoidStateType.Ragdoll, false)
	humanoid:SetStateEnabled(Enum.HumanoidStateType.Climbing, false)
	humanoid:SetStateEnabled(Enum.HumanoidStateType.Jumping, false)
	humanoid:SetStateEnabled(Enum.HumanoidStateType.Dead, false)
end

local function isHeadName(name: string): boolean
	return string.find(string.lower(name), "head", 1, true) ~= nil
end

local function findHead(model: Model, preferred: string?): BasePart?
	if preferred then
		local exact = model:FindFirstChild(preferred, true)
		if exact and exact:IsA("BasePart") then
			return exact
		end
	end
	for _, p in model:GetDescendants() do
		if p:IsA("BasePart") and isHeadName(p.Name) then
			return p
		end
	end
	return nil
end

-- A spawnable copy of your creature model, ready for the AI. Returns nil
-- when there's no model for this id.
function Models.creature(id: string): (Model?, BasePart?, Humanoid?, BasePart?)
	local template = Models.find(id)
	if not template then
		return nil, nil, nil, nil
	end
	local cfg = (Config.models :: any)[id]
	local model = template:Clone()
	model.Name = id
	local humanoid = model:FindFirstChildOfClass("Humanoid")
	local root = (model:FindFirstChild("HumanoidRootPart") or model.PrimaryPart) :: BasePart?

	if humanoid and root then
		for _, p in model:GetDescendants() do
			if p:IsA("BasePart") then
				p.Anchored = false
			end
		end
	else
		-- Not rigged: carry the meshes on a root and a Humanoid of our own.
		local box, size = model:GetBoundingBox()
		local newRoot = Instance.new("Part")
		newRoot.Name = "HumanoidRootPart"
		newRoot.Size = Vector3.new(2, 2, 1)
		newRoot.Transparency = 1
		newRoot.CanCollide = true
		newRoot.CFrame = CFrame.new(box.Position) * model:GetPivot().Rotation
		for _, p in model:GetDescendants() do
			if p:IsA("BasePart") then
				p.Anchored = false
				p.CanCollide = false
				p.Massless = true
				local weld = Instance.new("WeldConstraint")
				weld.Part0 = newRoot
				weld.Part1 = p
				weld.Parent = p
			end
		end
		newRoot.Parent = model
		model.PrimaryPart = newRoot
		local newHumanoid = Instance.new("Humanoid")
		newHumanoid.RigType = Enum.HumanoidRigType.R15
		newHumanoid.HipHeight = math.max(0.2, size.Y / 2 - newRoot.Size.Y / 2)
		newHumanoid.Parent = model
		humanoid, root = newHumanoid, newRoot
	end
	local finalRoot = root :: BasePart
	model.PrimaryPart = finalRoot
	finalRoot:SetAttribute("Hitbox", "Body")
	Models.configureHumanoid(humanoid :: Humanoid)

	for _, p in model:GetDescendants() do
		if p:IsA("BasePart") and p:GetAttribute("Hitbox") == nil then
			p:SetAttribute("Hitbox", if isHeadName(p.Name) then "Head" else "Body")
		end
	end
	return model, finalRoot, humanoid, findHead(model, cfg and cfg.headPart)
end

-- The joint that holds a part, made turnable and detachable. Converts a
-- WeldConstraint into a Weld; makes one to the root if there's none.
function Models.jointFor(model: Model, root: BasePart, part: BasePart): JointInstance
	for _, d in model:GetDescendants() do
		if d:IsA("JointInstance") and (d.Part1 == part or d.Part0 == part) then
			return d
		end
	end
	for _, d in model:GetDescendants() do
		if d:IsA("WeldConstraint") and (d.Part0 == part or d.Part1 == part) then
			local other = if d.Part0 == part then d.Part1 else d.Part0
			if other then
				local weld = Instance.new("Weld")
				weld.Part0 = other
				weld.Part1 = part
				weld.C0 = other.CFrame:Inverse() * part.CFrame
				d:Destroy()
				weld.Parent = part
				return weld
			end
		end
	end
	local weld = Instance.new("Weld")
	weld.Part0 = root
	weld.Part1 = part
	weld.C0 = root.CFrame:Inverse() * part.CFrame
	weld.Parent = part
	return weld
end

-- Your Banshee, prepared to be shown and hidden: an invisible "Root" at
-- her feet as the pivot. Returns the model, the part used as her face
-- (torch-on-face check) and the part her keen and light come from.
function Models.banshee(): (Model?, BasePart?, BasePart?)
	local template = Models.find("Banshee")
	if not template then
		return nil, nil, nil
	end
	local model = template:Clone()
	model.Name = "Banshee"
	local box, size = model:GetBoundingBox()
	local rotation = model:GetPivot().Rotation
	local hrp = model:FindFirstChild("HumanoidRootPart") :: BasePart?
	local jointed = (model:FindFirstChildOfClass("Humanoid") or model:FindFirstChildOfClass("AnimationController")) ~= nil
		and model:FindFirstChildWhichIsA("Motor6D", true) ~= nil

	local face, chest, highest = nil, nil, nil
	for _, p in model:GetDescendants() do
		if p:IsA("BasePart") then
			p.CanCollide = false
			p.CanQuery = false
			p.CanTouch = false
			p.Anchored = not jointed or p == hrp
			p:SetAttribute("BaseTransparency", p.Transparency)
			local lower = string.lower(p.Name)
			if not face and (string.find(lower, "face", 1, true) or string.find(lower, "head", 1, true)) then
				face = p
			end
			if not chest and (lower == "chest" or lower == "uppertorso" or lower == "torso") then
				chest = p
			end
			if not highest or p.Position.Y > highest.Position.Y then
				highest = p
			end
		end
	end
	local humanoid = model:FindFirstChildOfClass("Humanoid")
	if humanoid then
		humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
		humanoid.HealthDisplayType = Enum.HumanoidHealthDisplayType.AlwaysOff
	end

	local root = Instance.new("Part")
	root.Name = "Root"
	root.Anchored = true
	root.CanCollide = false
	root.CanQuery = false
	root.CanTouch = false
	root.Transparency = 1
	root.Size = Vector3.one * 0.5
	root.CFrame = CFrame.new(box.X, box.Y - size.Y / 2, box.Z) * rotation
	root.Parent = model
	model.PrimaryPart = root
	return model, face or highest, chest or root
end

------------------------------------------------------------------ animation

export type Animations = {
	loop: (name: string) -> (),
	action: (name: string) -> (),
}

local FALLBACK = {
	run = "walk",
	blind = "idle",
	keen = "idle",
	mourn = "idle",
}

local NO_ANIMATIONS: Animations = {
	loop = function() end,
	action = function() end,
}

-- Plays the ids in Config.models[id].animations on a model. `loop` keeps
-- one looping animation going (idle, walk, run, keen...); `action` plays
-- a one-off on top (attack). Missing ids are ignored.
function Models.animations(model: Model, id: string): Animations
	local cfg = (Config.models :: any)[id]
	local ids = cfg and cfg.animations
	local controller = model:FindFirstChildOfClass("Humanoid") or model:FindFirstChildOfClass("AnimationController")
	if not ids or not controller then
		return NO_ANIMATIONS
	end
	local animator = controller:FindFirstChildOfClass("Animator")
	if not animator then
		animator = Instance.new("Animator")
		animator.Parent = controller
	end
	local tracks: { [string]: AnimationTrack } = {}
	local function track(name: string): AnimationTrack?
		if tracks[name] then
			return tracks[name]
		end
		local animId = ids[name]
		if not animId or animId == "" then
			return nil
		end
		local animation = Instance.new("Animation")
		animation.AnimationId = animId
		local ok, loaded = pcall(function()
			return (animator :: Animator):LoadAnimation(animation)
		end)
		if ok and loaded then
			tracks[name] = loaded
			return loaded
		end
		return nil
	end
	local current: string? = nil
	return {
		loop = function(wanted: string)
			-- A missing animation falls back to a close one (run -> walk).
			local name = wanted
			if not track(name) and FALLBACK[name] then
				name = FALLBACK[name]
			end
			if current == name then
				return
			end
			local nextTrack = track(name)
			if not nextTrack then
				return
			end
			if current and tracks[current] then
				tracks[current]:Stop(0.25)
			end
			current = name
			nextTrack.Looped = true
			nextTrack:Play(0.25)
		end,
		action = function(name: string)
			local t = track(name)
			if t then
				t.Looped = false
				t:Play(0.1)
			end
		end,
	}
end

return Models
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Noise"}, class = "ModuleScript", source = [=[
--[[
	Noise: anything an entity could hear. Footsteps, gunshots, a dropped
	head. Entities listen to Noise.emitted and decide for themselves.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Signal = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Signal"))

export type Noise = {
	position: Vector3,
	radius: number,
	kind: string, -- "footsteps" | "gunshot" | "impact"
	source: Player?,
}

local Noise = {}

Noise.emitted = Signal.new()

function Noise.emit(position: Vector3, radius: number, kind: string, source: Player?)
	if radius <= 0 then
		return
	end
	Noise.emitted:Fire({ position = position, radius = radius, kind = kind, source = source } :: Noise)
end

return Noise
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Pickups"}, class = "ModuleScript", source = [=[
--[[
	Pickups: ammo, batteries and the gold ward. Ammo goes to YOUR gun
	through Hooks.giveAmmo; until that's wired (Hooks.ammoPickups), ammo
	pickups stay out of the map.

	Each pickup part has Kind ("ammo" | "battery" | "gold"), Group and
	Always. Always pickups are always there. For the rest, each group puts
	Config.pickups.groups[Group] of its candidates in the world per run
	(plus extra per extra player), chosen at random so routes can't be
	memorised. Supply is deliberately short of "fight everything".
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))

local Crew = require(script.Parent.Crew)
local Hooks = require(script.Parent.Hooks)
local Map = require(script.Parent.Map)
local Say = require(script.Parent.Say)

local Pickups = {}

local LABELS = {
	ammo = { action = "Take", object = "Ammunition" },
	battery = { action = "Take", object = "Torch batteries" },
	gold = { action = "Take", object = "Gold sovereign" },
}

local goldPart: BasePart? = nil

local function show(p: BasePart, visible: boolean)
	p.Transparency = if visible then 0 else 1
	p.CanQuery = false
	local prompt = p:FindFirstChildOfClass("ProximityPrompt")
	if prompt then
		prompt.Enabled = visible
	end
	p:SetAttribute("Live", visible)
end

-- Ammo only appears once Hooks.giveAmmo is wired to your gun.
local function allowed(p: BasePart): boolean
	return p:GetAttribute("Kind") ~= "ammo" or Hooks.ammoPickups == true
end

local function take(p: BasePart, player: Player)
	if not p:GetAttribute("Live") or not Crew.isActive(player) then
		return
	end
	local kind = p:GetAttribute("Kind")
	if kind == "ammo" then
		if not Hooks.giveAmmo(player, Config.pickups.ammoAmount) then
			Say.to(player, "No room for more rounds.", 2, "hint")
			return
		end
		Say.to(player, `+{Config.pickups.ammoAmount} rounds`, 2, "hint")
	elseif kind == "battery" then
		if not Crew.addBattery(player, Config.pickups.batteryAmount) then
			Say.to(player, "Your torch is already full.", 2, "hint")
			return
		end
		Say.to(player, "Fresh batteries.", 2, "hint")
	elseif kind == "gold" then
		Crew.giveGold(player)
	end
	Audio.play("pickup", p, 0.5)
	show(p, false)
end

-- Picks which candidates are live this run. Call once the party is in.
function Pickups.roll()
	local partySize = math.max(1, #Players:GetPlayers())
	local byGroup: { [string]: { BasePart } } = {}
	for _, p in Map.interact("Pickups"):GetChildren() do
		-- Always pickups were set out by setup (and may be taken already).
		if p:IsA("BasePart") and not p:GetAttribute("Always") and allowed(p) then
			show(p, false)
			local group = p:GetAttribute("Group") or "Default"
			byGroup[group] = byGroup[group] or {}
			table.insert(byGroup[group], p)
		end
	end
	for group, candidates in byGroup do
		local base = Config.pickups.groups[group] or 1
		local count = math.min(#candidates, base + math.floor(Config.pickups.extraPerPlayer * (partySize - 1) + 0.5))
		for _ = 1, count do
			local i = math.random(1, #candidates)
			show(table.remove(candidates, i) :: BasePart, true)
		end
	end
end

function Pickups.setup()
	for _, p in Map.interact("Pickups"):GetChildren() do
		if p:IsA("BasePart") then
			local kind = p:GetAttribute("Kind")
			local labels = LABELS[kind] or LABELS.ammo
			local prompt = Instance.new("ProximityPrompt")
			prompt.ActionText = labels.action
			prompt.ObjectText = labels.object
			prompt.HoldDuration = 0.2
			prompt.MaxActivationDistance = 7
			prompt.RequiresLineOfSight = false
			prompt.Parent = p
			prompt.Triggered:Connect(function(player)
				take(p, player)
			end)
			if kind == "gold" then
				goldPart = p
			end
			-- Until the run's roll (Director, once the party is in), only the
			-- Always pickups are out.
			show(p, p:GetAttribute("Always") == true and allowed(p))
		end
	end
	-- If whoever had the gold leaves, it goes back in its case.
	Crew.goldLost:Connect(function()
		if goldPart then
			show(goldPart, true)
		end
	end)
end

return Pickups
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Reading"}, class = "ModuleScript", source = [=[
--[[
	Reading: notes, catalogue cards and voice memos. A part with a NoteId
	attribute gets a "Read" prompt that opens the note on that player's
	screen (text in ReplicatedStorage.Ashgrove.Notes).

	RequiresMourning notes can only be read while the Banshee grieves over
	them (Banshee calls Reading.reveal); once revealed they stay readable.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Net = require(Shared:WaitForChild("Net"))
local Notes = require(Shared:WaitForChild("Notes"))
local Signal = require(Shared:WaitForChild("Signal"))

local Map = require(script.Parent.Map)

local Reading = {}

Reading.read = Signal.new() -- (noteId, player)

local prompts: { [string]: ProximityPrompt } = {}
local readBy: { [string]: { [Player]: boolean } } = {}

function Reading.reveal(noteId: string)
	local prompt = prompts[noteId]
	if prompt then
		prompt.Enabled = true
	end
end

function Reading.hasBeenRead(noteId: string): boolean
	return readBy[noteId] ~= nil and next(readBy[noteId]) ~= nil
end

function Reading.setup()
	for _, p in Map.interact("Notes"):GetChildren() do
		local noteId = p:GetAttribute("NoteId")
		if p:IsA("BasePart") and noteId then
			local note = Notes[noteId]
			local prompt = Instance.new("ProximityPrompt")
			prompt.ActionText = if p.Size.Y > 0.2 then "Play" else "Read"
			prompt.ObjectText = if note then note.title else noteId
			prompt.HoldDuration = 0
			prompt.MaxActivationDistance = 7
			prompt.RequiresLineOfSight = false
			prompt.Enabled = p:GetAttribute("RequiresMourning") ~= true
			prompt.Parent = p
			prompts[noteId] = prompt
			prompt.Triggered:Connect(function(player)
				Net.event("Note"):FireClient(player, noteId)
				readBy[noteId] = readBy[noteId] or {}
				readBy[noteId][player] = true
				Reading.read:Fire(noteId, player)
			end)
		end
	end
end

return Reading
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Retrieval"}, class = "ModuleScript", source = [=[
--[[
	Retrieval: the objective grammar. Each story is a list of collection
	objects to secure where they're found.

	An object part has ObjectId, Label, Securable and (optionally)
	EntityId. Securing is a committed action of Config.commit.secure
	seconds, or secureWhileEntityActive if its entity is up and about:
	kill it first and the window opens. Securing removes the entity for
	the rest of the story and closes the object's warded crate.

	Non-securable objects (the sealed box) can only be inspected.
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))
local Signal = require(Shared:WaitForChild("Signal"))

local Crew = require(script.Parent.Crew)
local Map = require(script.Parent.Map)
local Registry = require(script.Parent.Entities.Registry)
local Say = require(script.Parent.Say)

local Retrieval = {}

Retrieval.secured = Signal.new() -- (objectId, player)
Retrieval.inspected = Signal.new() -- (objectId, player)

local objects: { [string]: BasePart } = {}
local done: { [string]: boolean } = {}
local enabled: { [string]: boolean } = {}

function Retrieval.isDone(objectId: string): boolean
	return done[objectId] == true
end

function Retrieval.setEnabled(objectId: string, on: boolean)
	enabled[objectId] = on
	local p = objects[objectId]
	local prompt = p and p:FindFirstChildOfClass("ProximityPrompt")
	if prompt and not done[objectId] then
		prompt.Enabled = on
	end
end

local function closeCrate(objectId: string)
	for _, crate in Map.interact("Crates"):GetChildren() do
		if crate:GetAttribute("CrateFor") == objectId then
			local lid = crate:FindFirstChild("Lid")
			if lid and lid:IsA("BasePart") then
				lid.Transparency = 0
				lid.CanCollide = true
			end
		end
	end
end

local function secure(objectId: string, player: Player?)
	if done[objectId] then
		return
	end
	done[objectId] = true
	local p = objects[objectId]
	local prompt = p:FindFirstChildOfClass("ProximityPrompt")
	if prompt then
		prompt.Enabled = false
	end
	TweenService:Create(p, TweenInfo.new(0.6), { Transparency = 1 }):Play()
	p.CanCollide = false
	p.CanQuery = false
	closeCrate(objectId)
	Audio.play("secure", p, 0.7)
	local entityId = p:GetAttribute("EntityId")
	local entity = entityId and Registry.get(entityId)
	if entity then
		entity:secure()
	end
	Say.all(`{p:GetAttribute("Label")} secured.`, 4, "story")
	Retrieval.secured:Fire(objectId, player)
end

-- Studio debug: secure an object as if someone had done it.
function Retrieval.forceSecure(objectId: string)
	if objects[objectId] then
		secure(objectId, nil)
	end
end

function Retrieval.setup()
	for _, p in Map.interact("Objects"):GetChildren() do
		if p:IsA("BasePart") and p:GetAttribute("ObjectId") then
			local objectId = p:GetAttribute("ObjectId") :: string
			objects[objectId] = p
			local securable = p:GetAttribute("Securable") == true
			local prompt = Instance.new("ProximityPrompt")
			prompt.ActionText = if securable then "Secure" else "Inspect"
			prompt.ObjectText = p:GetAttribute("Label") or objectId
			prompt.HoldDuration = 0.25
			prompt.MaxActivationDistance = 8
			prompt.RequiresLineOfSight = false
			prompt.Enabled = false
			prompt.Parent = p
			prompt.Triggered:Connect(function(player)
				if done[objectId] or not enabled[objectId] then
					return
				end
				if not securable then
					done[objectId] = true
					prompt.Enabled = false
					Retrieval.inspected:Fire(objectId, player)
					return
				end
				local entityId = p:GetAttribute("EntityId")
				local entity = entityId and Registry.get(entityId)
				local busy = entity ~= nil and entity.status == "active"
				local seconds = if busy then Config.commit.secureWhileEntityActive else Config.commit.secure
				if busy then
					Say.to(player, "It's still up. This will take longer.", 3, "hint")
				end
				Crew.commit(player, seconds, `Securing {prompt.ObjectText}`, function()
					secure(objectId, player)
				end)
			end)
		end
	end
end

return Retrieval
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Rites"}, class = "ModuleScript", source = [=[
--[[
	Rites: the wake custom that answers a keen.

	A rite site is a Model under Interact/Rites with a Wing attribute and
	three step parts (RiteStep = "clock" | "mirror" | "window"). Its prompts
	only work while the Banshee is keening in that wing. Each step is a
	short committed action; when all three are done, Rites.completed fires
	and the Banshee is answered.

	Each site keeps the custom once. The room stays changed afterwards
	(the clock stopped, the mirror covered, the window open).
]]

local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Shared = ReplicatedStorage:WaitForChild("Ashgrove")
local Audio = require(Shared:WaitForChild("Audio"))
local Config = require(Shared:WaitForChild("Config"))
local Signal = require(Shared:WaitForChild("Signal"))

local Crew = require(script.Parent.Crew)
local Map = require(script.Parent.Map)
local Say = require(script.Parent.Say)

local Rites = {}

Rites.completed = Signal.new() -- (siteName, wing, player)

local STEP_TEXT = {
	clock = { action = "Stop the clock", done = "The clock stops." },
	mirror = { action = "Cover the mirror", done = "The glass is covered." },
	window = { action = "Open the window", done = "The window is open." },
}

type Site = {
	model: Model,
	wing: string,
	used: boolean,
	steps: { [BasePart]: boolean },
}

local sites: { Site } = {}

local function applyStep(part: BasePart, step: string)
	if step == "mirror" then
		local cloth = part:FindFirstChild("Cloth")
		if cloth and cloth:IsA("BasePart") then
			cloth.Transparency = 0
		end
	elseif step == "window" then
		part.Transparency = 0.95
		part.CanCollide = false
	elseif step == "clock" then
		part:SetAttribute("Stopped", true)
	end
end

local function siteDone(site: Site): boolean
	for _, isDone in site.steps do
		if not isDone then
			return false
		end
	end
	return true
end

function Rites.hasUnusedSite(wing: string): boolean
	for _, site in sites do
		if site.wing == wing and not site.used then
			return true
		end
	end
	return false
end

-- Turns the prompts on (during a keen in that wing) or off.
function Rites.setActive(wing: string, on: boolean)
	for _, site in sites do
		if site.wing == wing then
			for part, isDone in site.steps do
				local prompt = part:FindFirstChildOfClass("ProximityPrompt")
				if prompt then
					prompt.Enabled = on and not site.used and not isDone
				end
			end
		end
	end
end

function Rites.setup()
	for _, model in Map.interact("Rites"):GetChildren() do
		if model:IsA("Model") then
			local site: Site = {
				model = model,
				wing = model:GetAttribute("Wing") or "",
				used = false,
				steps = {},
			}
			table.insert(sites, site)
			for _, part in model:GetChildren() do
				local step = part:GetAttribute("RiteStep")
				if part:IsA("BasePart") and step and STEP_TEXT[step] then
					site.steps[part] = false
					local prompt = Instance.new("ProximityPrompt")
					prompt.ActionText = STEP_TEXT[step].action
					prompt.ObjectText = "The wake custom"
					prompt.HoldDuration = 0.2
					prompt.MaxActivationDistance = 8
					prompt.RequiresLineOfSight = false
					prompt.Enabled = false
					prompt.Parent = part
					prompt.Triggered:Connect(function(player)
						if site.used or site.steps[part] then
							return
						end
						Crew.commit(player, Config.commit.rite, STEP_TEXT[step].action, function()
							if site.used or site.steps[part] then
								return
							end
							site.steps[part] = true
							prompt.Enabled = false
							applyStep(part, step)
							Audio.play("riteStep", part, 0.6)
							Say.near(part.Position, 40, STEP_TEXT[step].done, 3, "story")
							if siteDone(site) then
								site.used = true
								Rites.completed:Fire(model.Name, site.wing, player)
							end
						end)
					end)
				end
			end
		end
	end
end

return Rites
]=] },
	{ service = {"ServerScriptService"}, path = {"Ashgrove", "Say"}, class = "ModuleScript", source = [=[
--[[
	Say: on-screen captions. Every sound that carries information has one,
	so the game reads correctly with no audio and for deaf players.

	Styles: "sound" for [bracketed sound captions], "story" for lines the
	player should notice, "hint" for teaching text.
]]

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")

local Net = require(ReplicatedStorage:WaitForChild("Ashgrove"):WaitForChild("Net"))

local captionRemote = Net.event("Caption")

local Say = {}

function Say.to(player: Player, text: string, seconds: number?, style: string?)
	captionRemote:FireClient(player, text, seconds or 4, style or "story")
end

function Say.all(text: string, seconds: number?, style: string?)
	captionRemote:FireAllClients(text, seconds or 4, style or "story")
end

-- Everyone whose character is within `radius` of `position`.
function Say.near(position: Vector3, radius: number, text: string, seconds: number?, style: string?)
	for _, player in Players:GetPlayers() do
		local character = player.Character
		local root = character and character:FindFirstChild("HumanoidRootPart")
		if root and ((root :: BasePart).Position - position).Magnitude <= radius then
			Say.to(player, text, seconds, style)
		end
	end
end

function Say.except(skip: Player, text: string, seconds: number?, style: string?)
	for _, player in Players:GetPlayers() do
		if player ~= skip then
			Say.to(player, text, seconds, style)
		end
	end
end

return Say
]=] },
}

local function child(parent: Instance, name: string): Instance
	local found = parent:FindFirstChild(name)
	assert(found, `[Ashgrove] expected {parent:GetFullName()}.{name} (paste the parts in order, starting from part 1)`)
	return found :: Instance
end

local function serviceAt(names: { string }): Instance
	local node: Instance = game:GetService(names[1])
	for i = 2, #names do
		node = child(node, names[i])
	end
	return node
end

local function install()
	local ChangeHistoryService = game:GetService("ChangeHistoryService")
	local ok, recording = pcall(function()
		return ChangeHistoryService:TryBeginRecording("Install Ashgrove House")
	end)
	if not ok then
		recording = nil
	end

	-- Remove older installs first.
	if REMOVE_OLD then
		for _, r in ROOTS do
			local old = serviceAt(r.service):FindFirstChild(r.name)
			if old then
				old:Destroy()
			end
		end
	end

	for _, f in FILES do
		local parent = serviceAt(f.service)
		for i = 1, #f.path - 1 do
			parent = child(parent, f.path[i])
		end
		local existing = parent:FindFirstChild(f.path[#f.path])
		if existing then
			existing:Destroy()
		end
		local inst = Instance.new(f.class)
		inst.Name = f.path[#f.path]
		if f.source then
			(inst :: any).Source = f.source
		end
		inst.Parent = parent
	end

	if FINISH then
		for _, name in { "Baseplate", "SpawnLocation" } do
			local leftover = workspace:FindFirstChild(name)
			if leftover and leftover:IsA("BasePart") then
				leftover:Destroy()
			end
		end
		if not workspace:FindFirstChild("AshgroveHouse") then
			require(game:GetService("ServerScriptService").Ashgrove.House).build()
		end
	end

	if recording then
		pcall(function()
			ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
		end)
	end
	print(DONE_MESSAGE)
end

if plugin then
	local toolbar = plugin:CreateToolbar("Ashgrove")
	local button = toolbar:CreateButton("Install", "Install or update Ashgrove House in this place", "")
	button.ClickableWhenViewportHidden = true
	button.Click:Connect(install)
else
	install()
end
