#!/usr/bin/env python3
"""Builds AshgroveInstaller.lua: one file to paste into Roblox Studio's
Command Bar. It recreates the same instance tree Rojo builds from
default.project.json, so the two install routes always match.

    python3 tools/build_installer.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "AshgroveInstaller.lua"

# (service path, instance name, source directory)
TREES = [
    (["ReplicatedStorage"], "Ashgrove", ROOT / "src/shared/Ashgrove"),
    (["ServerScriptService"], "Ashgrove", ROOT / "src/server/Ashgrove"),
    (["StarterPlayer", "StarterPlayerScripts"], "AshgroveClient", ROOT / "src/client/AshgroveClient"),
]


def script_class(path: pathlib.Path):
    name = path.name
    if name.endswith(".server.luau"):
        return "Script", name[: -len(".server.luau")]
    if name.endswith(".client.luau"):
        return "LocalScript", name[: -len(".client.luau")]
    return "ModuleScript", name[: -len(".luau")]


def walk(service, parent_path, name, directory, entries):
    """Rojo rules: a directory with init.*.luau becomes that script, its
    other files become children; a directory without one is a Folder."""
    init = None
    for candidate in ("init.server.luau", "init.client.luau", "init.luau"):
        if (directory / candidate).exists():
            init = directory / candidate
    here = parent_path + [name]
    if init:
        cls, _ = script_class(init)
        entries.append((service, here, cls, init.read_text()))
    else:
        entries.append((service, here, "Folder", None))
    for child in sorted(directory.iterdir()):
        if child == init:
            continue
        if child.is_dir():
            walk(service, here, child.name, child, entries)
        elif child.suffix == ".luau":
            cls, child_name = script_class(child)
            entries.append((service, here + [child_name], cls, child.read_text()))


def long_string(text: str) -> str:
    level = 1
    while "]" + "=" * level + "]" in text:
        level += 1
    eq = "=" * level
    # A newline right after the opening bracket is dropped by Lua, so add one
    # to keep the source's first line intact.
    return f"[{eq}[\n{text}]{eq}]"


def lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    entries = []
    for service, name, directory in TREES:
        walk(service, [], name, directory, entries)

    lines = []
    lines.append("""--[[
	ASHGROVE HOUSE: one-paste installer for Roblox Studio.
	Generated by ashgrove/tools/build_installer.py from ashgrove/src. Don't
	edit this file; edit the source and run the script again.

	HOW TO USE
	  1. Open a place in Studio (File > New > Baseplate is fine).
	  2. View > Command Bar.
	  3. Paste this whole file into the Command Bar and press Enter.
	  4. Press Play.

	It creates (replacing older copies):
	  ReplicatedStorage.Ashgrove                       shared modules
	  ServerScriptService.Ashgrove                     server Script + modules
	  StarterPlayer.StarterPlayerScripts.AshgroveClient  client LocalScript
	and builds the house as Workspace.AshgroveHouse, removing the
	template's Baseplate and SpawnLocation (the Baseplate fills the cellar).
	One Ctrl+Z undoes the whole install.

	If the Command Bar won't take a paste this long: paste it into a new
	Script in ServerStorage instead, right-click the Script, choose
	"Save as Local Plugin...", then click Plugins > Ashgrove > Install.
]]

local FILES = {""")
    for service, path, cls, source in entries:
        svc = "{" + ", ".join(lua_string(s) for s in service) + "}"
        p = "{" + ", ".join(lua_string(s) for s in path) + "}"
        src = long_string(source) if source is not None else "nil"
        lines.append(f"\t{{ service = {svc}, path = {p}, class = {lua_string(cls)}, source = {src} }},")
    lines.append("}")
    lines.append("""
local function child(parent: Instance, name: string): Instance
	local found = parent:FindFirstChild(name)
	assert(found, `[Ashgrove] expected {parent:GetFullName()}.{name}`)
	return found :: Instance
end

local function serviceAt(names: { string }): Instance
	local node: Instance = game:GetService(names[1])
	for i = 2, #names do
		node = child(node, names[i])
	end
	return node
end

local function install()
	local ChangeHistoryService = game:GetService("ChangeHistoryService")
	local ok, recording = pcall(function()
		return ChangeHistoryService:TryBeginRecording("Install Ashgrove House")
	end)
	if not ok then
		recording = nil
	end

	-- Remove older installs first.
	for _, f in FILES do
		if #f.path == 1 then
			local old = serviceAt(f.service):FindFirstChild(f.path[1])
			if old then
				old:Destroy()
			end
		end
	end

	for _, f in FILES do
		local parent = serviceAt(f.service)
		for i = 1, #f.path - 1 do
			parent = child(parent, f.path[i])
		end
		local inst = Instance.new(f.class)
		inst.Name = f.path[#f.path]
		if f.source then
			(inst :: any).Source = f.source
		end
		inst.Parent = parent
	end

	for _, name in { "Baseplate", "SpawnLocation" } do
		local leftover = workspace:FindFirstChild(name)
		if leftover and leftover:IsA("BasePart") then
			leftover:Destroy()
		end
	end
	if not workspace:FindFirstChild("AshgroveHouse") then
		require(game:GetService("ServerScriptService").Ashgrove.House).build()
	end

	if recording then
		pcall(function()
			ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
		end)
	end
	print("[Ashgrove] Installed. Press Play. (Studio keys: F6 next chapter, F7 keen, F8 refill.)")
end

if plugin then
	local toolbar = plugin:CreateToolbar("Ashgrove")
	local button = toolbar:CreateButton("Install", "Install or update Ashgrove House in this place", "")
	button.ClickableWhenViewportHidden = true
	button.Click:Connect(install)
else
	install()
end
""")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB, {len(entries)} instances)")


if __name__ == "__main__":
    main()
