#!/usr/bin/env python3
"""Builds AshgroveInstaller.lua: one file to paste into Roblox Studio's
Command Bar. It recreates the same instance tree Rojo builds from
default.project.json, so the two install routes always match.

    python3 tools/build_installer.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "AshgroveInstaller.lua"

# (service path, instance name, source directory)
TREES = [
    (["ReplicatedStorage"], "Ashgrove", ROOT / "src/shared/Ashgrove"),
    (["ServerScriptService"], "Ashgrove", ROOT / "src/server/Ashgrove"),
    (["StarterPlayer", "StarterPlayerScripts"], "AshgroveClient", ROOT / "src/client/AshgroveClient"),
]


def script_class(path: pathlib.Path):
    name = path.name
    if name.endswith(".server.luau"):
        return "Script", name[: -len(".server.luau")]
    if name.endswith(".client.luau"):
        return "LocalScript", name[: -len(".client.luau")]
    return "ModuleScript", name[: -len(".luau")]


def walk(service, parent_path, name, directory, entries):
    """Rojo rules: a directory with init.*.luau becomes that script, its
    other files become children; a directory without one is a Folder."""
    init = None
    for candidate in ("init.server.luau", "init.client.luau", "init.luau"):
        if (directory / candidate).exists():
            init = directory / candidate
    here = parent_path + [name]
    if init:
        cls, _ = script_class(init)
        entries.append((service, here, cls, init.read_text()))
    else:
        entries.append((service, here, "Folder", None))
    for child in sorted(directory.iterdir()):
        if child == init:
            continue
        if child.is_dir():
            walk(service, here, child.name, child, entries)
        elif child.suffix == ".luau":
            cls, child_name = script_class(child)
            entries.append((service, here + [child_name], cls, child.read_text()))


def long_string(text: str) -> str:
    level = 1
    while "]" + "=" * level + "]" in text:
        level += 1
    eq = "=" * level
    # A newline right after the opening bracket is dropped by Lua, so add one
    # to keep the source's first line intact.
    return f"[{eq}[\n{text}]{eq}]"


def lua_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


RUNTIME = """
local function child(parent: Instance, name: string): Instance
	local found = parent:FindFirstChild(name)
	assert(found, `[Ashgrove] expected {parent:GetFullName()}.{name} (paste the parts in order, starting from part 1)`)
	return found :: Instance
end

local function serviceAt(names: { string }): Instance
	local node: Instance = game:GetService(names[1])
	for i = 2, #names do
		node = child(node, names[i])
	end
	return node
end

local function install()
	local ChangeHistoryService = game:GetService("ChangeHistoryService")
	local ok, recording = pcall(function()
		return ChangeHistoryService:TryBeginRecording("Install Ashgrove House")
	end)
	if not ok then
		recording = nil
	end

	-- Remove older installs first.
	if REMOVE_OLD then
		for _, r in ROOTS do
			local old = serviceAt(r.service):FindFirstChild(r.name)
			if old then
				old:Destroy()
			end
		end
	end

	for _, f in FILES do
		local parent = serviceAt(f.service)
		for i = 1, #f.path - 1 do
			parent = child(parent, f.path[i])
		end
		local existing = parent:FindFirstChild(f.path[#f.path])
		if existing then
			existing:Destroy()
		end
		local inst = Instance.new(f.class)
		inst.Name = f.path[#f.path]
		if f.source then
			(inst :: any).Source = f.source
		end
		inst.Parent = parent
	end

	if FINISH then
		for _, name in { "Baseplate", "SpawnLocation" } do
			local leftover = workspace:FindFirstChild(name)
			if leftover and leftover:IsA("BasePart") then
				leftover:Destroy()
			end
		end
		if not workspace:FindFirstChild("AshgroveHouse") then
			require(game:GetService("ServerScriptService").Ashgrove.House).build()
		end
	end

	if recording then
		pcall(function()
			ChangeHistoryService:FinishRecording(recording, Enum.FinishRecordingOperation.Commit)
		end)
	end
	print(DONE_MESSAGE)
end

if plugin then
	local toolbar = plugin:CreateToolbar("Ashgrove")
	local button = toolbar:CreateButton("Install", "Install or update Ashgrove House in this place", "")
	button.ClickableWhenViewportHidden = true
	button.Click:Connect(install)
else
	install()
end
"""

HEADER_FULL = """--[[
	ASHGROVE HOUSE: one-paste installer for Roblox Studio.
	Generated by ashgrove/tools/build_installer.py from ashgrove/src. Don't
	edit this file; edit the source and run the script again.

	HOW TO USE
	  1. Open your place in Studio (or File > New > Baseplate).
	  2. View > Command Bar.
	  3. Select ALL of this file (Ctrl+A), copy it (Ctrl+C), click in the
	     Command Bar, paste (Ctrl+V) and press Enter.
	  4. Press Play.

	It creates (replacing older copies):
	  ReplicatedStorage.Ashgrove                         shared modules
	  ServerScriptService.Ashgrove                       server Script + modules
	  StarterPlayer.StarterPlayerScripts.AshgroveClient  client LocalScript
	and builds the house as Workspace.AshgroveHouse, removing a template
	Baseplate and SpawnLocation (the Baseplate fills the cellar).
	One Ctrl+Z undoes the whole install.

	Too long for the Command Bar? Use the smaller files in
	ashgrove/installer-parts/ instead: paste part 1, press Enter, then
	part 2, and so on, in order.
]]
"""

HEADER_PART = """--[[
	ASHGROVE HOUSE installer, PART {i} OF {n}.
	Generated by ashgrove/tools/build_installer.py. Don't edit by hand.

	Paste the parts into Studio's Command Bar IN ORDER (1, 2, 3 ...),
	pressing Enter after each. Wait for the Output window to say
	"part {i} of {n} done" before pasting the next one.
	{last}
]]
"""


def render(header: str, entries, roots, remove_old: bool, finish: bool, done: str) -> str:
    lines = [header]
    lines.append("local REMOVE_OLD = " + ("true" if remove_old else "false"))
    lines.append("local FINISH = " + ("true" if finish else "false"))
    lines.append("local DONE_MESSAGE = " + lua_string(done))
    lines.append("local ROOTS = {")
    for service, name in roots:
        svc = "{" + ", ".join(lua_string(x) for x in service) + "}"
        lines.append(f"\t{{ service = {svc}, name = {lua_string(name)} }},")
    lines.append("}")
    lines.append("")
    lines.append("local FILES = {")
    for service, path, cls, source in entries:
        svc = "{" + ", ".join(lua_string(x) for x in service) + "}"
        pth = "{" + ", ".join(lua_string(x) for x in path) + "}"
        src = long_string(source) if source is not None else "nil"
        lines.append(f"\t{{ service = {svc}, path = {pth}, class = {lua_string(cls)}, source = {src} }},")
    lines.append("}")
    lines.append(RUNTIME)
    return "\n".join(lines)


PART_LIMIT = 40 * 1024  # bytes of source per part


def main():
    entries = []
    for service, name, directory in TREES:
        walk(service, [], name, directory, entries)
    roots = [(service, name) for service, name, _ in TREES]
    finished = "[Ashgrove] Installed. Press Play. (Studio keys: F6 next chapter, F7 keen, F8 refill.)"

    OUT.write_text(render(HEADER_FULL, entries, roots, True, True, finished))
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB, {len(entries)} instances)")

    # The same install, split into parts small enough for any Command Bar.
    chunks, current, size = [], [], 0
    for e in entries:
        weight = len(e[3] or "") + 200
        if current and size + weight > PART_LIMIT:
            chunks.append(current)
            current, size = [], 0
        current.append(e)
        size += weight
    chunks.append(current)
    parts_dir = ROOT / "installer-parts"
    parts_dir.mkdir(exist_ok=True)
    for old in parts_dir.glob("*.lua"):
        old.unlink()
    n = len(chunks)
    for i, chunk in enumerate(chunks, 1):
        last = "This is the LAST part: it also builds the house. Then press Play." if i == n else f"Next: part {i + 1}."
        done = finished if i == n else f"[Ashgrove] part {i} of {n} done. Now paste part {i + 1}."
        text = render(HEADER_PART.format(i=i, n=n, last=last), chunk, roots, i == 1, i == n, done)
        (parts_dir / f"Ashgrove_Part{i}_of_{n}.lua").write_text(text)
    sizes = ", ".join(f"{(parts_dir / f'Ashgrove_Part{i}_of_{n}.lua').stat().st_size // 1024} KB" for i in range(1, n + 1))
    print(f"wrote {n} parts in installer-parts/ ({sizes})")


if __name__ == "__main__":
    main()
